### ISSUE TITLE
Make Factor work with multi-epoch observations

### ISSUE THREAD

**Issue by AHorneffer** [lofar-astron/factor#1]
Factor should also work with multi-epoch data, e.g. interleaved observations, but also long observations taken at different nights.

**Comment by AHorneffer** [comment]
I'll start with changing the **Band** class to use a list for the measurement set names.

**Comment by darafferty** [comment]
Sounds good. I created a new branch called "multi-epoch" for this.

**Comment by darafferty** [comment]
Sorry, accidentally closed the issue!

**Comment by AHorneffer** [comment]
Done. ;-)
