### ISSUE TITLE
Checkfactor should show reimaging progress (partially fixed)

### ISSUE THREAD

**Issue by mhardcastle** [lofar-astron/factor#100]
Checkfactor doesn't show progress with reimaging. I have pushed a change to master that makes the colors of facets successively darker green as more operations complete beyond the first two, retaining the light green for facetselfcal + facetsub. (This isn't represented in the legend -- ideally plot_state would know whether the config file called for reimaging and provide the extra colors and descriptions if necessary, but I haven't implemented that yet.)

**Comment by darafferty** [comment]
Very nice! Somewhat related to this, I've just changed the response of the "i" key so that it allows you to pick the image that you want to open. (This also makes it easy to open several images of a facet in different frames in ds9.)

**Comment by mhardcastle** [comment]
Excellent, that was also on my wish list...

**Comment by mhardcastle** [comment]
I have now pushed a fix so that the legend contains colors for the reimage step.

Also, I've changed the coloring algorithm so that facets that have a current operation that hasn't started yet don't go yellow (because the effect of the changes in the scheduler discussed in #97 is that all facets that are to be reimaged have a current operation, so they all went yellow).

**Comment by mhardcastle** [comment]
Closing this as no-one has complained (-:
