### ISSUE TITLE
Second reimage parameters are wrong!

### ISSUE THREAD

**Issue by mhardcastle** [lofar-astron/factor#102]
In my second, low-resolution reimage (with casa) the imaging is being done with the same imaging parameters as for the first image, although the file and operation names report the correct parameters and the image sizes are appropriate for the specified cell size.

I guess the problem should be fairly obvious; I'll try to find it, then reset the whole operation which should provide a nice test of some of the new changes (-:

**Comment by darafferty** [comment]
That's strange: the parameter values used to set the operation name should be propagated (through the set_imcal_paramters() method of the direction object) directly to the pipeline.parset for the operation (so if the operation name is OK, the values in the parset should be too). So, indeed, it must be something fairly obvious, but I can't spot anything wrong yet on a cursory inspection of the code.

**Comment by AHorneffer** [comment]
Martin: can you check in the pipeline parset of the reimage steps what is put in there?

**Comment by mhardcastle** [comment]
It's wrong, as I guess it had to be. Looks like the taper is right but the cellsize and robust are wrong. Here's the relevant part:

<pre>
# image the virtual concatenated data, length = 1
casa_image_full1.control.type                     =   casa_clean
casa_image_full1.control.mapfiles_in              =   [virtual_concat_averaged.output.mapfile,premask.o
utput.mapfile]
casa_image_full1.control.inputkeys                =   [clean.vis,clean.mask]
casa_image_full1.control.outputkey                =   clean.imagename
casa_image_full1.control.arguments                =   [--nologger,--nogui,-c]
casa_image_full1.argument.clean.wprojplanes       =   256
casa_image_full1.argument.clean.uvrange           =   '>80.0lambda'
casa_image_full1.argument.clean.nterms            =   2
casa_image_full1.argument.clean.niter             =   9797
casa_image_full1.argument.clean.threshold         =   '0mJy'
casa_image_full1.argument.clean.imsize            =   [1890, 1890]
casa_image_full1.argument.clean.cell              =   ['1.5arcsec', '1.5arcsec']
casa_image_full1.argument.clean.robust            =   -1.0
casa_image_full1.argument.clean.multiscale        =   [0]
casa_image_full1.argument.clean.selectdata        =   True
casa_image_full1.argument.clean.gridmode          =   'widefield'
casa_image_full1.argument.clean.interactive       =   False
casa_image_full1.argument.clean.mode              =   'mfs'
casa_image_full1.argument.clean.gain              =   0.1
casa_image_full1.argument.clean.psfmode           =   'clark'
casa_image_full1.argument.clean.imagermode        =   'csclean'
casa_image_full1.argument.clean.ftmachine         =   'mosaic'
casa_image_full1.argument.clean.mosweight         =   False
casa_image_full1.argument.clean.scaletype         =   'SAULT'
casa_image_full1.argument.clean.weighting         =   'briggs'
casa_image_full1.argument.clean.pbcor             =   False
casa_image_full1.argument.clean.minpb             =   0.2
casa_image_full1.argument.clean.npixels           =   0
casa_image_full1.argument.clean.npercycle         =   100
casa_image_full1.argument.clean.cyclefactor       =   2.5
casa_image_full1.argument.clean.cyclespeedup      =   -1
casa_image_full1.argument.clean.chaniter          =   False
casa_image_full1.argument.clean.flatnoise         =   True
casa_image_full1.argument.clean.allowchunk        =   False
casa_image_full1.argument.clean.uvtaper           =   True
casa_image_full1.argument.clean.outertaper        =   ['20.0arcsec']
</pre>

and for second image:

<pre>
# image the virtual concatenated data with the updated mask, length = 1
casa_image_full2.control.type                     =   casa_clean
casa_image_full2.control.mapfiles_in              =   [virtual_concat_averaged.output.mapfile,mask.output.mapfile,mask.output.threshold_5sig.mapfile]
casa_image_full2.control.inputkeys                =   [clean.vis,clean.mask,clean.threshold]
casa_image_full2.control.outputkey                =   clean.imagename
casa_image_full2.control.arguments                =   [--nologger,--nogui,-c]
casa_image_full2.argument.clean.wprojplanes       =   256
casa_image_full2.argument.clean.uvrange           =   '>80.0lambda'
casa_image_full2.argument.clean.nterms            =   2
casa_image_full2.argument.clean.niter             =   58787
casa_image_full2.argument.clean.imsize            =   [1890, 1890]
casa_image_full2.argument.clean.cell              =   ['1.5arcsec', '1.5arcsec']
casa_image_full2.argument.clean.robust            =   -1.0
casa_image_full2.argument.clean.multiscale        =   [0]
casa_image_full2.argument.clean.selectdata        =   True
casa_image_full2.argument.clean.gridmode          =   'widefield'
casa_image_full2.argument.clean.interactive       =   False
casa_image_full2.argument.clean.mode              =   'mfs'
casa_image_full2.argument.clean.gain              =   0.1
casa_image_full2.argument.clean.psfmode           =   'clark'
casa_image_full2.argument.clean.imagermode        =   'csclean'
casa_image_full2.argument.clean.ftmachine         =   'mosaic'
casa_image_full2.argument.clean.mosweight         =   False
casa_image_full2.argument.clean.scaletype         =   'SAULT'
casa_image_full2.argument.clean.weighting         =   'briggs'
casa_image_full2.argument.clean.pbcor             =   False
casa_image_full2.argument.clean.minpb             =   0.2
casa_image_full2.argument.clean.npixels           =   0
casa_image_full2.argument.clean.npercycle         =   100
casa_image_full2.argument.clean.cyclefactor       =   2.5
casa_image_full2.argument.clean.cyclespeedup      =   -1
casa_image_full2.argument.clean.chaniter          =   False
casa_image_full2.argument.clean.flatnoise         =   True
casa_image_full2.argument.clean.allowchunk        =   False
casa_image_full1.argument.clean.uvtaper           =   True
casa_image_full1.argument.clean.outertaper        =   ['20.0arcsec']
</pre>

(Note the 'full1' at the end here.)

**Comment by darafferty** [comment]
Hi Martin -- there is something strange going on, as I fixed the 'full1' typo a week or so ago (see 6ffbb0f68f2a1b956f114d6e686ff56d1d56e2a4). Perhaps your version is somehow out of sync with the current master?

**Comment by darafferty** [comment]
I see now that I also fixed the parameters with the same commit. I thought your problem sounded somewhat familiar...

**Comment by mhardcastle** [comment]
Ah, well, of course I hadn't pulled the new code at the point that this happened -- I'd been running the same version for a month. But that explains my inability to find the problem in the current code.

OK, what is the best way of resetting just this reimage operation without having to redo the high-res one?

**Comment by darafferty** [comment]
If it's just for a few facets, you can do something like:

`runfactor factor.parset -r facet_name1,facet_name2 -o facetimage_5.0r-1.0t15.0u80.0`

If you want to reset all of your facets, this should still work but is a bit tedious. Perhaps we could make it so that if only the '-o' flag is given but no '-r' one, all directions are reset?

**Comment by mhardcastle** [comment]
OK, running again now.
