### ISSUE TITLE
Automatic rejection of flagged groups

### ISSUE THREAD

**Issue by nudomarinero** [lofar-astron/factor#103]
In some cases, more than 50% of the data is flagged for some input MS and this could cause problems (see #20 ).
Currently, if there is a frequency group with no data, after rejecting the chunks with less than 50% of the data flagged, factor stops. This is good in the sense that makes you aware that there could be a problem with the frequency coverage. The bad MS can be manually removed and factor rerun. However, this approach does not work well if an automatic running of factor is needed.
Ideally factor would make clear to the user the problem with the frequency coverage and continue with the run automatically discarding the bad MS. As the issue is major, it could be useful to output the problem as one of the main data products and not just in the log file. Perhaps as part of an additional file describing the major issues, and maybe in a machine and human readable format (json?).

**Comment by AHorneffer** [comment]
I believe this is something to be included when archiving the results: #89

**Comment by darafferty** [comment]
I added an option for this ("exit_on_bad_band" under [global]). By default, this is false and Factor will continue if there is a bad band (> 50% flagged) and print a warning.

**Comment by nudomarinero** [comment]
Great! Is the data used despite the flagging or discarded and treated like a gap in the frequency coverage?

**Comment by darafferty** [comment]
It's discarded (since otherwise the slow-gain solve could have too little S/N).
