### ISSUE TITLE
remove facet images?

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/factor#104]
In an attempt to save a very large amount of time when running factor how about removing the facet imaging step? 

This would mean that only the calibrator source (or region of sources) is accurately subtracted from the data which will perhaps make the calibration of the faintest calibrators a bit harder but maybe not impossible. The field could then be imaged just by doing the reimaging (using appropriate solutions for the field and the calibrator sources).

**Comment by darafferty** [comment]
The option to skip the facet imaging during selfcal is now available on the master branch. Enable it with "skip_facet_imaging = True" under [imaging].

**Comment by twshimwell** [comment]
Excellent! Did this already get tested to the stage where the facet images were made using different solutions for the facet sources and calibrator sources?

**Comment by darafferty** [comment]
Yes, Alexander has tested it for ~ a dozen facets, I believe.

**Comment by twshimwell** [comment]
Great.
