### ISSUE TITLE
wsclean_ft started with too high max-memory

### ISSUE THREAD

**Issue by AHorneffer** [lofar-astron/factor#105]
in the facetimage pipeline wsclean_ft will typically be started with a few processes in parallel. (Otherwise one will get into a "too many open files" issue.) But each process is started with "-mem" set to "wsclean_fmem" / "num_pipelines_per_node". Thus wsclean can (try to) take more memory than the machine has.

**Comment by darafferty** [comment]
This issue should (hopefully) be fixed, as Factor will now divide the memory automatically between parallel WSClean jobs.
