### ISSUE TITLE
Source avoidance caused a facet to be divided

### ISSUE THREAD

**Issue by Joshuaalbert** [lofar-astron/factor#108]
Source avoidance has caused a facet to be divided into multiple parts. 
seperation_max_arcmin = 6.0 (instead of 7.0) could this be the cause?

How does the source avoidance decide what radius to avoid by?

**Comment by darafferty** [comment]
The radius is determined by the size of the source, with a minimum value that scales with the flux as 25 arcsec \* min(10.0, max(2.0, sqrt(flux_jy/0.01))) to ensure we use large enough avoidance regions to capture any artifacts that were picked up in the model.

**Comment by Joshuaalbert** [comment]
Okay, well seperation_max_arcmin sets the minimum distance between calibrators, so it also in some way sets the smallest size of facets. However near vertices it is possible that a facet boundary tries to avoid a source with a radius of 250arcsec = 4arcin in which case the facet could be split. 
There is not an easy solution, however maybe just putting a try except clause in there so that it tries to avoid unless it splits a facet in which case it tries something else or doesn't avoid the source.

**Comment by darafferty** [comment]
I've changed the behavior so that it will just skip trying to avoid the source that causes the problem. At least this will allow a run to continue even if the facets aren't optimal...
