### ISSUE TITLE
Convert all imaging to WSClean

### ISSUE THREAD

**Issue by darafferty** [lofar-astron/factor#109]
Currently, Factor uses casa for all selfcal imaging. It would be nice to move to WSClean and so remove the dependency on casa, particularly with the upcoming improvements to WSClean that should make it much faster than casa.

Besides the channels_out issue (need to be careful to keep it a divisor of the number of channels in the data used for calibration) and the need to add extra padding, are there any other issues to keep in mind? Reinout, I think you mentioned the predict may need to be altered -- can we not use the predict mode of WSClean as is?

**Comment by rvweeren** [comment]
WSClean is in principle ok, but again we need to be careful to keep it a divisor of the number of channels in the data used for calibration. (because more averaging is done just before the selfcal imaging)

**Comment by soumyajitmandal** [comment]
I was wondering if there is an option in factor parset to do the selfcal imaging with wsclean?

**Comment by rvweeren** [comment]
David made a special "wsclean" branch for that (still in development) but you could have a try.

**Comment by soumyajitmandal** [comment]
I am getting this error while running Factor with the new wsclean. Did anyone have the same?

2016-08-17 10:54:11 WARNING node.para11.strw.leidenuniv.nl.executable_args.L123835_SBgr004-10_uv.dppp.pre-cal_chunk13_1226E698Ft_0g.concat0: /net/para10/data1/shimwell/wsclean-1.12a/build/wsclean stderr: terminate called after throwing an instance of 'std::runtime_error'
  what():  CFITSIO reported error when performing IO on file '/net/para12/data2/mandal/A1914/ddecal/Factor/Factortestrun/FACTOR_fullBW_15/workingdir/results/facetselfcal/facet_patch_534/L123835_SBgr004-10_uv.dppp.pre-cal_chunk13_1226E698Ft_0g.wsclean_image01-MFS-image.mask0':error reading from FITS file (Error reading data buffer from file:/net/para12/data2/mandal/A1914/ddecal/Factor/Factortestrun/FACTOR_fullBW_15/workingdir/results/facetselfcal/facet_patch_534/L123835_SBgr004-10_uv.dppp.pre-cal_chunk13_1226E698Ft_0g.wsclean_image01-MFS-image.mask0ffopen could not interpret primary array header of file: /net/para12/data2/mandal/A1914/ddecal/Factor/Factortestrun/FACTOR_fullBW_15/workingdir/results/facetselfcal/facet_patch_534/L123835_SBgr004-10_uv.dppp.pre-cal_chunk13_1226E698Ft_0g.wsclean_image01-MFS-image.mask0)

**Comment by rvweeren** [comment]
Disk full ?

Or check the mask. Error suggests it cannot read the mask (maybe the masking failed?)

**Comment by soumyajitmandal** [comment]
Disk size is not an issue. also mask was made properly (I gave a region file in the direction.txt). I could open the mask as region file too. "more" on the mask gives this: 
#CRTFv0 CASA Region Text Format version 0
poly [[14:26:11.11771, +037.50.59.9026], [14:26:20.05035, +037.49.04.4152], [14:26:16.35364, +037.43.56.1258], [14:25:41.11675, +037.43.10.8007], [14:25:33.60478, +037.47.09.0766
], [14:25:38.69556, +037.51.24.4962], [14:26:02.17661, +037.52.30.7568], [14:26:11.27706, +037.50.54.2264]] coord=J2000, corr=[I], linewidth=1, linestyle=-, symsize=1, symthick=1
, color=magenta, font="DejaVu Sans", fontsize=11, fontstyle=normal, usetex=false

am trying now with default settings (without any region file) just to check.

**Comment by soumyajitmandal** [comment]
Now the flux scale is getting messed up: Flux from sum of (non-blank) pixels are of the order of 10^22 Jy so masking fails.

**Comment by darafferty** [comment]
Jit, are you using the wsclean branch or the master one?

**Comment by soumyajitmandal** [comment]
this is the wsclean branch. I wanted to use wsclean for the self-cal imaging.

**Comment by darafferty** [comment]
How did selfcal go for this facet? I suspect that selfcal had problems, and therefore the imaging of the full facet is going wrong.

There seems to be some problem with wideband clean/predict during selfcal, but I wasn't able to identify it yet. I will have another look at it soon.

**Comment by soumyajitmandal** [comment]
this is actually image01, not the facet imaging. :/

**Comment by wndywllms** [comment]
I saw a similar bad image01 (before masking) only when doing multiresolution selfcal with wsclean

Could it be the spectral poly fit that isn't commented in the taper parset (https://github.com/lofar-astron/factor/commit/c7995fb7425d66f79c0dff9fcabb2854cee265e5)?

**Comment by darafferty** [comment]
Ah yes, I should have realized it was image01. 

Good idea, Wendy -- I did not test the taper parset yet, so I would try it only with multires_selfcal = False.

**Comment by aroffringa** [comment]
I hope it's ok if I post a comment :) ? I was reading the Factor docs to apply it on EoR data, and came across this bug. I notice that you used -fit-spectral-log-pol , is that correct? I wouldn't advise that for the general pipeline. Rather use -fit-spectral-pol. The first option fits every component to a power law or higher-termed logarithmic function. That's fine for strong sources, but when cleaning picks up some partly-negative artefacts, it can create bad results and fail (Imagine one value negative and others positive, and fitting a power law through that). CASA also doesn't fit logarithmic polynomials, it fits normal polynomials, so its behaviour would be similar to -fit-spectral-pol. Maybe I should also make this more clear in the docs.

**Comment by rvweeren** [comment]
Andre: Good point. I've tried -fit-spectral-log-pol before and abandoned it (because of negative clean components).

**Comment by darafferty** [comment]
Yeah, -fit-spectral-log-pol is not being used any more (except in the unfinished taper parset, as I haven't yet updated that to remove it). I'm working now to fix the predict issue that I mentioned above (I think I've found the error), but without any fit-spectral options. Once I'm sure it's working, I will experiment with -fit-spectral-pol.

**Comment by rvweeren** [comment]
I think we can close this for now.
