### ISSUE TITLE
check input bands flagging percentages

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#11]
see https://github.com/lofar-astron/prefactor/issues/8

(maybe it is most natural to let factor do this)

**Comment by AHorneffer** [comment]
That's already in there. (It's the slow taql part at startup in the current master.) A time-chunk with less than 10% unflagged data is discarded.

**Comment by rvweeren** [comment]
Thanks for clarifying that and good to hear. Note that 10% is equivalent to calibration on 0.05 Jy of flux (with the default flux requirements of ~0.5 Jy) so that violates S/N requirements and can lead to unstable calibration. Would be much saver to put this to 40-50% or so. (optionally, make it a variable that can be set by the user, if you think there are situations that you want to calibrate with < 50% of data unfledged, not sure if that ever should happen though….?).

**Comment by AHorneffer** [comment]
Hmmm...
We don't solve on single time-chunks of single bands, but concatenate the data in frequency. My assumption was that there are single time-frequency blocks with lots of flagged data. (E.g. due to A-team clipping, or because a certain time-window was flagged.)

How would you deal with a case where in a 20min MS the first 8 min were nearly fully flagged. (In all frequency bands?) A simple check like we are doing now wouldn't catch that.

**Comment by rvweeren** [comment]
I was mainly concerned with the slow A&P solve, which solves in groups of 10 SB (but you're right that there could be more complicated situations). My main point is to increase at least from the 10% we've now to a more reasonable/save value (for a block of certain length containing 10SB). Luckily for the majority of the data the percentage of flags is low so this should only affect a small number of blocks.

(We might have to think a bit more about these more complicated case, maybe one has to build up a "master" view of flags across the full dataset. Anyway, for now I suggest just to increase from the 10% to a more save value).

**Comment by AHorneffer** [comment]
The new default is to kick out a time-chunk if there is less than 50% unflagged data in there.
So I guess we can close this issue.
