### ISSUE TITLE
utilise baseline dependent averaging in wsclean

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/factor#110]
Andre has put this option in the latest version of wsclean. Tests by Reinout and Andre show it will give a big speedup (maybe ~7) in the imaging. To use this the nwavelengths option needs computing somewhere in factor.

**Comment by darafferty** [comment]
I've added an option (on the master branch) to use the baseline-dependent averaging: activate it with "wsclean_bl_averaging = True" under [imaging]. Factor will calculate nwavelengths for a given cellsize (which gives the resolution assuming normal sampling of the restoring beam) and image size (which along with the "max_peak_smearing" option sets the amount of allowed time averaging).

**Comment by twshimwell** [comment]
Nice, ill have a go with this today. Perhaps we can use the same calculation to get nwavelengths in the initsubtract

**Comment by rvweeren** [comment]
Have been running it for quite many facets and so far no problems with "wsclean_bl_averaging = True".

In terms of speed: On a single 24 CPU machine on average factor can selfcal and image 3 facets per day for the full bandwidth (also using the NDPPP TEC solve). So 30 facets will take about 10 days (this does not including re-imaging).

**Comment by twshimwell** [comment]
Wow, that is fast. Excellent!
