### ISSUE TITLE
default multi-scale clean parameters

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/factor#111]
In the self calibration casa imaging the multi-scale (default scales 0, 3, 7, 25, 60 and 150)  clean of the facet images can take a long time. Tests by Reinout indicated that this can be substantially reduced by decreasing the number of scales. 

Maybe the first image (which isn't using multi-scale) can be used to determine the size of the synthesised beam (in pixels) and then the scales can be determined from that. Maybe by default factor we should use a courser grid of scales and just use scales 0, 1times synthesised beam, 5 times synthesised beam and 25 times synthesized beam (this is very large at ~2arcmin so for most cases the masking will probably exclude this one anyway). If the calibrator is very complex the user can always input different scales in the parset.

**Comment by darafferty** [comment]
Yes, that sounds like the way to do it. For now, I changed it to simply use only the first two scales (so 0 and 3) unless atrous_do has be activated for the calibrator (either set by the user in the directions file or set by Factor when the calibrator size > 6 arcmin).
