### ISSUE TITLE
multiscale always used in facet imaging ?

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#116]
My facet contains mostly point sources. I notice that multiscale is used in facet imaging with wsclean (slowing things down considerably for large image sizes). My question: Is multiscale always used in facet imaging with WSClean ?

**Comment by darafferty** [comment]
Multiscale should only be activated (for both casa and wsclean) when Factor finds a source in the facet larger than 6 arcmin. So, it should rarely be used (if the size calculation is working correctly, of course).

**Comment by rvweeren** [comment]
Hmm weird, I do not see a single extended source larger than 1arcmin, still it was triggered.

**Comment by rvweeren** [comment]
I think the multiscale trigger was caused by the artifacts around 3C295. So these sort of cases should be rare, for other facets multiscale is not triggered so I think there not really an error here. 3C295 is just very bright...
