### ISSUE TITLE
facet imaged twice ?

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#118]
My facet image was made (after peeling).

Now factor is imaging again in a directory "facet image_c1.5.r-0.25t0.0"

It seems this is some re-image step but reimage_selfcaled= False

Some bug ?

(I did not set different facet output settings)

In addition, the image contains weird (double?) subtracted sources and other strange artifacts.
(something screwed up in combination with the peeling it seems).

BTW This is just my first facet and I used ndir_process=1 (because I want to double check my first facet is ok)

**Comment by darafferty** [comment]
Hmm. I think somehow it is getting confused and thinks the imaging parameters are different than the ones used in the first imaging run. I'll look into it.

Did the facet image made in "facetpeelimage" look strange too, or just the one in "facet image_c1.5.r-0.25t0.0"?

**Comment by rvweeren** [comment]
facetpeelimage looked fine.

**Comment by rvweeren** [comment]
facetimage_c1.5.r-0.25t0.0 (left) vs facetimage (right)

Pretty messed up...

(factor does not give any errors….)

<img width="634" alt="tf" src="https://cloud.githubusercontent.com/assets/3879473/17078915/17ce6822-50cf-11e6-9075-728ec37ff353.png">

**Comment by rvweeren** [comment]
Here is the parset I was using:

[Factor2.parset.gz](https://github.com/lofar-astron/factor/files/380652/Factor2.parset.gz)

**Comment by rvweeren** [comment]
I started from a clean parset and the problem disappeared, but internally there still seems to be some confusion in the code. I think this is related to peeling facets. My peeling facet gets a green color as if it was re-imaged.

<img width="420" alt="cf" src="https://cloud.githubusercontent.com/assets/3879473/17258838/c4886b5a-5596-11e6-8d55-b749cd93093a.png">

**Comment by mhardcastle** [comment]
Yeah, the code I put in there to do the colour coding for reimaging does not know about peeling, and so probably assumes the extra step involved in peeling is a reimage step. (And since I don't have a dataset where peeling is used, it may be a bit difficult for me to fix that...)

**Comment by rvweeren** [comment]
Close since issue has not appeared again (I think it was related to some restart in combination with a factor update)
