### ISSUE TITLE
missing pad_model_images.padsize.mapfile error when reimaging

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/factor#119]
After doing the self calibration for all the calibrators and getting into the reimaging for every direction I get an error like:

[Errno 2] No such file or directory: '/net/para10/data1/shimwell/pipeline/Pre-Facet-Cal/products/FACTOR_P209_55/factor-auto-40sb/results/facetselfcal/facet_patch_1883/mapfiles/pad_model_images.padsize.mapfile'

Maybe this is because I used skip_facet_imaging = True and skipped the facet imaging which would have created the pad_model_images.padsize.mapfile

**Comment by wndywllms** [comment]
I saw the same thing when I tried to switch from using casa in my first factor run to using wsclean for the reimaging step.

**Comment by martadzielak-wongapl** [comment]
I have the same problem as Tim.

**Comment by darafferty** [comment]
Indeed, this problem was due to some missing steps when skip_facet_imaging = True and WSClean was used for imaging (it worked if CASA was used for imaging). Should be fixed now.

**Comment by twshimwell** [comment]
Excellent. Thanks! I guess this fix is in the master branch.

**Comment by darafferty** [comment]
Yes, in both master and tecsolve branches.

**Comment by twshimwell** [comment]
Seems to be producing images now. Thanks
