### ISSUE TITLE
restart to try to optimize facet layout is unnecessarily slow?  (run taql in parallel?)

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#12]
Checking input bands in not done in parallel when restarting factor (making a restart slow when I try to optimize the facet layout parameters, basically have to wait 20+ min before I get a new facet layout)

Note that I already run this part before and the splitting already completed, then I exited with: 

"Facet and DDE calibrator regions saved. Please check that they are OK before continuing.
Continue processing (y/n)? n"

The restart gives
2016-03-16 20:32:02,175 - INFO - factor - Checking input bands...
2016-03-16 20:32:03,753 - DEBUG - factor:Band_124.31MHz - Band name is Band_124.31MHz
2016-03-16 20:32:03,753 - DEBUG - factor:Band_124.31MHz - Missing channels: []
2016-03-16 20:32:08,113 - DEBUG - factor:Band_124.31MHz - Spliting /data6/rvanweeren/P214+52_results/L343226_SBgr026-10_uv.dppp
.pre-cal.ms into 13 chunks...

The slow part seems to be the taql part:
user  1494  0.0  0.0   4444   656 pts/23   S+   23:36   0:00 /bin/sh -c taql 'CALC sum([select nfalse(FLAG) from /p3600/rvweeren/P214_52/chunks/Band_132.13MHz/L343226_SBgr030-10_uv.dppp.pre-cal_chunk9.ms]) / sum([select nelements(FLAG) from /p3600/rvweeren/P214_52/chunks/Band_132.13MHz/L343226_SBgr030-10_uv.dppp.pre-cal_chunk9.ms])

I think that the taql can run in parallel here speeding up a restart (I am running from a very fast disk so running a dozen taql in parallel is not an issue). Might need a parameter of the number of parallel taql allowed, different from ncpu, if disks I/O is problematic for some) ?

**Comment by AHorneffer** [comment]
Have a look at the AH-experimental branch, there this part is handled different (test for too little unflagged data is done before writing out a time-chunk). As soon as someone tested it, I can merge it into master.

**Comment by AHorneffer** [comment]
The current version doesn't do the unflagged data check before chunking, but it does run taql in parallel. For data that doesn't need chunking it is only checked once.

So I guess we can close this issue.
