### ISSUE TITLE
Different names for average and unaverage calibrated ms sets and no mosaic being created

### ISSUE THREAD

**Issue by eretana** [lofar-astron/factor#120]
Dear all,

I notice that in my factor runs the files corresponding to unaverage calibrated ms sets are left on the facet directory despite I use in the parset the option keep_unavg_facet_data = False. 

Inspecting these files, I see they have the name sequence: 
L400135_SB400_uv.dppp_1271D10E0t_047g.pre-cal_chunk3.shift_empty1

Factor deletes the files specified on mapfiles/shift_empty.mapfile. However when I open the file, the name sequence is:
L400135_SB400_uv.dppp_1271D10E0t_047g.pre-cal_chunk3.shift_empty

It does not have the '1' at the end. What does cause the '1'  to be added? This naming occurs in all the facets I have done.

Also, I try to create a mosaic with the facets I have done, but it does not even tries to create the mosaic directory. Could be these two issues related?

Edwin.

**Comment by darafferty** [comment]
I'm not sure what caused this issue, but I don't believe it exists any longer in the current master. Please reopen this issue if it occurs again.
