### ISSUE TITLE
final mosaic identical for 2 sets of reimaging parameters

### ISSUE THREAD

**Issue by wndywllms** [lofar-astron/factor#122]
My factor run finished after 2 reimaging steps in the parset:

> facet_imager = casa 
> facet_cellsize_arcsec = [1.5, 4.0]
> facet_taper_arcsec = [0, 20]
> facet_robust = [-0.5, -1.0]

but the mosaics produced in the results directories 
fieldmosaic_c1.5r-0.5t0.0u80.0
fieldmosaic_c4.0r-1.0t20.0u80.0
were both of the low resolution images (i.e. the last facet images produced).

The lists of facet images in the pipeline.parset's in each of these directories are both of the low resolution images, so somehow the high resolution mosaic is not getting the list of images to mosaic correct. Probably just a minor bug somewhere...

**Comment by darafferty** [comment]
I believe this is fixed on the wsclean branch. I will now work to fix it on master as well.

**Comment by darafferty** [comment]
I never fixed this on the old master, but it should work now on the new one. Reopen if not.
