### ISSUE TITLE
Force factor to make mosaic

### ISSUE THREAD

**Issue by eretana** [lofar-astron/factor#123]
Hello. I made just one facet at the time with factor. I have done a few a few facets, but I would like to create a incomplete mosaic with these facets. I use the option make_mosaic=True, but it does not try to create the mosaic. It just simply says is finish.

Is there any option that needs to be set up to make the mosaic?

Edwin.

**Comment by eretana** [comment]
Which images does use factor to create the mosaic? Are the ones in the directory WORKINGDIR/results/facetimage_cXXX/?

**Comment by darafferty** [comment]
I think this case now works on the new master. Reopen if not.
