### ISSUE TITLE
Facet cleaning conditions

### ISSUE THREAD

**Issue by duyhoang-astro** [lofar-astron/factor#127]
Hello,

One of my factor run passed the selfcal test (exit_on_selfcal_failure = True, skip_selfcal_check = False). It could produce facet image without mask (_full1_) (using CASA). But failed on getting image with mask (_full2_). The cleaning of full2 image diverged. Unfortunately, I deleted the facet directory. So I can't check if it was because of the masking or the cleaning conditions (threshold, niter, etc.) that was too deep or something else. I am wondering (i) if there is an option in parset file that we can specify niter or threshold for facet imaging and (ii) if there is a further check the residual after the facet subtraction?

Thanks,
Duy

**Comment by darafferty** [comment]
> (i) is there is an option in parset file that we can specify niter or threshold for facet imaging?

No, the cleaning of the full2 image is always done to a threshold of 1 sigma (as determined by PyBDSM from the full1 image). To change this, you could alter the pipeline.parset file in the facetselfcal directory for that facet to set the threshold or number of iterations by hand.

> (ii) if there is a further check the residual after the facet subtraction?

There are plans to add some further checks (e.g., to check that the noise in the full2 image is reasonable, which would likely have caught your issue), but for now it just checks the residuals at low resolution.

**Comment by duyhoang-astro** [comment]
Thanks David. I will manually edit the threshold or niter in the parset then.
