### ISSUE TITLE
Factor error - no beam information in fits file

### ISSUE THREAD

**Issue by amisk** [lofar-astron/factor#128]
Hello,

I ran factor after the proper prefacet and initial subtract pipelines. Right at the first facet, it rand vor a couple of hours and then stoppen because of an error. Apparently, in a fits file created by factor itself, there is no beam information, but it needs the beam information to continue.

Here's also the log file (compressed, the original is 30mb and too big for github).
Thx.

[facet_patch_328.out.log.tar.gz](https://github.com/lofar-astron/factor/files/432196/facet_patch_328.out.log.tar.gz)

**Comment by darafferty** [comment]
This error seems to be caused by using an old version on WSClean. Reopen if not.
