### ISSUE TITLE
check_edges option also needs to check mask_high/low masks from Initial-Subtract.parset

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#13]
When avoiding sources with check_edges (or even in general) one needs to check that the facet boundaries do not cross a region where the clean mask eq 1 (both for the "high" and "low" masks). For example, in the low-res images a somewhat extended mask on top of a source and the surrounding artifacts could have been used. Then it might happen that these clean components are not properly added back to the correct facet because some of are located across the facet boundary (even with check_edges= True), while they belonged to the same source region when wsclean was doing the deconvolution. 

So for optimal results the final facet boundaries need to be checked against all the mask_high and mask_low images and not cross regions where mask == 1.0. (unless for example it results the mask in growing beyond an acceptable limit,  to catch rare cases with extremely extended sources, which cannot fit in a single facet).

**Comment by darafferty** [comment]
We might be able to handle this issue during the initial subtraction by grouping clean components in the merged skymodels by islands in the masks and then defining sources for the facet boundary adjustment based on these groups (instead of the way it's done now of convolving the clean components with a Gaussian and finding islands through thresholding).

**Comment by rvweeren** [comment]
Yes. I guess if we move to making one wideband image in the Initial-Subtract.parset this will become easier (less bookkeeping with all the masks from the different blocks)

**Comment by AHorneffer** [comment]
Reinout: Actually a step in the pipeline is a step in the pipeline, not matter on how many files it is executed. So the bookkeeping will be the same.

David: With multiscale clean there would be the issue that using clean-masks with the usual casapy2bbs.py only those parts of the multiscale-clean-components that are within the mask will be would be taken into the skymodel file. 
Currently InitialSubtract doesn't use multiscale clean so it isn't an issue right now. But we should keep that in mind.
