### ISSUE TITLE
Re-image facet outside FACTOR

### ISSUE THREAD

**Issue by duyhoang-astro** [lofar-astron/factor#130]
Hi,

This is more like a question, rather than an issue.

I notice that FACTOR can re-image facets with different imaging options. However, if I want to take out calibrated measurement sets to re-image outside FACTOR, which measurement sets should be taken out? There are *chunk?.average5, *mssort_average5, *concat_pre_averaged_CONCAT, *.concat_pre_averaged in the facetselfcal directories. Which ones and which data column are used for facet imaging? I took the *.concat_pre_averaged, as suggested by clean.last without success.

Thanks,
Duy

**Comment by duyhoang-astro** [comment]
I copied all the measurement sets *mssort_average5, *concat_pre_averaged_CONCAT, and *.concat_pre_averaged (not copying *chunk?.average5) to another directory and re-imaged with CASA. The input measurement set for CLEAN task is *.concat_pre_averaged which links to *concat_pre_averaged_CONCAT and *mssort_average5. It seems to work...

**Comment by darafferty** [comment]
Yes, those are the correct files (as per http://www.astron.nl/citt/facet-doc/operations.html#facetselfcal).
