### ISSUE TITLE
DPPP failing due to caltype=tec

### ISSUE THREAD

**Issue by sabourke** [lofar-astron/factor#132]
It looks like facetselfcal is using NDPPP gaincal with caltype = "tec" which doesn't seem to be allowed. NDPPP from Lofar 2.17.5

factor fails with:

```
ERROR - factor:scheduler - Operation facetselfcal failed due to an error (direction: facet_patch_533)
ERROR - factor:scheduler - One or more operations failed due to an error. Exiting...
```

from the logs:

```
LOFAR Exception detected: [AssertError: Assertion: itsMode=="diagonal" || itsMode=="phaseonly" || itsMode=="fulljones" || itsMode=="scalarphase" || itsMode=="amplitudeonly" || itsMode=="scalaramplitude"]
in function LOFAR::DPPP::GainCal::GainCal(LOFAR::DPPP::DPInput*, const LOFAR::ParameterSet&, const std::string&)
(/c3se/priv/c3-oso/sbsw/src/LOFAR-Release-2_17_5/CEP/DP3/DPPP/src/GainCal.cc:123)
```

from the parset in use at the time:

```
solvetec.caltype=tec
solvetec.type=gaincal
solvetec.usemodelcolumn=True
steps=[uvcut,solvetec]
```

**Comment by tammojan** [comment]
For now, you'll have to use the LOFAR trunk to use the tec solver.

**Comment by darafferty** [comment]
Ah yes -- I didn't realize that the TEC fitter is not yet in a release. You can use the trunk as Tammo Jan said or you can roll Factor back to commit bd6cb1c.

**Comment by twshimwell** [comment]
we don't have trunk here in leiden either, any timeline for when this will go into trunk tammo or is it a little uncertain?

**Comment by tammojan** [comment]
It will be in the next release, which be in a timescale of a couple of weeks.

On a related note: as there is / will be a new calibration type for 'tec only', I'm planning to rename `caltype=tec` to `caltype=tecandphase`. Will that give problems in Factor? In summary, in the new proposed version:
- `caltype=tec` gives `TEC`
- `caltype=tecandphase` give `TEC` and `CommonScalarPhase`

Currently `caltype=tec` gives `TEC` and `CommonScalarPhase` so that would be changed..

**Comment by darafferty** [comment]
Shouldn't be a problem -- I can update Factor as soon as you've made the change. Factor likely needs the TEC-only solver too (when we start pre-applying dir-dependent solutions from the first DDE calibrator to subsequent ones, `CommonScalarPhase` shouldn't be needed).

**Comment by tammojan** [comment]
Committed now (r35242):
- `caltype=tec` gives `TEC`
- `caltype=tecandphase` gives `TEC` and `CommonScalarPhase`
