### ISSUE TITLE
Incorrect number of Bytes read error? 

### ISSUE THREAD

**Issue by soumyajitmandal** [lofar-astron/factor#134]
Did anyone see this error? I got this at the full2 image step. I am using the baseline based averaging and wsclean branch. 

Backtrace follows:
#0  0x7fe3d27c1c84 in LOFAR::Exception::terminate() at Exception.cc:89
#1  0x7fe3d018e936 in std::rethrow_exception(std::__exception_ptr::exception_ptr) at ??:0
#2  0x7fe3d018e981 in std::terminate() at ??:0
#3  0x7fe3d018eb99 in __cxa_throw at ??:0
#4  0x7fe3d3f7830c in casa::FilebufIO::readBlock(long long, char*, bool) at ??:0
#5  0x7fe3d3f78405 in casa::FilebufIO::read(long long, void*, bool) at ??:0
#6  0x7fe3d3f7555e in casa::CanonicalIO::read(unsigned long, unsigned int*) at ??:0
#7  0x7fe3d3f6a317 in casa::AipsIO::operator>>(unsigned int&) at ??:0
#8  0x7fe3d3f6af5b in casa::AipsIO::getNextType() at ??:0
#9  0x7fe3d55cc77c in casa::Table::open(casa::String const&, casa::String const&, int, casa::TableLock const&, casa::TSMOption const&) at ??:0
#10 0x7fe3d55ccc23 in casa::Table::Table(casa::String const&, casa::TableLock const&, casa::Table::TableOption, casa::TSMOption const&) at ??:0
#11 0x7fe3d67bb6c0 in casa::MSTable<casa::MSMainEnums::PredefinedColumns, casa::MSMainEnums::PredefinedKeywords>::MSTable(casa::String const&, casa::TableLock const&, casa::Table::TableOption) at ??:0
#12 0x7fe3d672d459 in casa::MeasurementSet::MeasurementSet(casa::String const&, casa::TableLock const&, casa::Table::TableOption) at ??:0
#13 0x7fe3d81ffcf5 in LOFAR::DPPP::MSReader::MSReader(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, LOFAR::ParameterSet const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) at MSReader.cc:99
#14 0x7fe3d8199423 in LOFAR::DPPP::DPRun::makeSteps(LOFAR::ParameterSet const&) at DPRun.cc:269
#15 0x7fe3d819b838 in LOFAR::DPPP::DPRun::execute(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, char**) at DPRun.cc:132
#16 0x404fb9 in main at NDPPP.cc:87

terminate called after throwing an instance of 'casa::AipsError'
  what():  FilebufIO::readBlock - **incorrect number of bytes read for file** /net/para14/data2/mandal/factor_281008/workingdir/results/facetselfcal/facet_patch_999/L281008_SBgr000-10_uv.dppp.pre-cal_chunk4_12608E368t_0g.mssort_into_Groups/table.dat

2016-09-04 18:01:53 WARNING node.para12.strw.leidenuniv.nl.executable_args.L281008_SBgr000-10_uv.dppp.pre-cal_chunk9_126091249t_0g.mssort_into_Groups: /net/para34/data1/oonk/lof_jun2016_2_16_4/lofar/bin/$
 uncaught exception

**Comment by AHorneffer** [comment]
Looks like `/net/para14/data2/mandal/factor_281008/workingdir/results/facetselfcal/facet_patch_999/L281008_SBgr000-10_uv.dppp.pre-cal_chunk4_12608E368t_0g.mssort_into_Groups/table.dat` is somehow corrupted. (Probably too short.)
- Is it the same size as the corresponding file in the other MSs of the same step?
- Was there some issue with the file-system? (FS full, a disk damaged or so?)

**Comment by darafferty** [comment]
Closing for now -- reopen if this problem reoccurs.
