### ISSUE TITLE
Issue with DPPP scalarphase

### ISSUE THREAD

**Issue by tammojan** [lofar-astron/factor#135]
I think I found a bug in DPPP `scalarphase` calibration which makes it ignore half the data during calibration. This also affects `tec` and `tecandphase` calibration. See https://support.astron.nl/lofar_issuetracker/issues/9834

**Comment by mhardcastle** [comment]
@tammojan Can you confirm that this is fixed in the trunk now?

**Comment by tammojan** [comment]
Yes. Also in the release branch 2.18 that is due to be released next Monday.
