### ISSUE TITLE
Fail selfcal with NDPPP, switch back to BBS?

### ISSUE THREAD

**Issue by duyhoang-astro** [lofar-astron/factor#136]
I'm using the up-to-date version of master branch. The pipeline.parset suggests that the calibration is in DPPP, instead of BBS. And it crashes at step solve_phaseonly1 which I believe does not work in DPPP version 2.15_0 (which we have in Leiden now). Is there any option to force the selfcal to use BBS? Thanks.

**Comment by darafferty** [comment]
No, you have to go back to commit bd6cb1c (see issue #132). Version 2.15 is pretty old -- I would encourage you to update. The DPPP solver is much faster and does not have the TEC instabilities that the BBS solver has.

**Comment by tammojan** [comment]
Lofar Release 2.18 of next Monday may be a nice opportunity for upgrading.

**Comment by duyhoang-astro** [comment]
Thanks. Yeh, it's not too long to wait. Better to upgrade our LOFAR software here.
