### ISSUE TITLE
unhelpful error message if original mss are not writable

### ISSUE THREAD

**Issue by mhardcastle** [lofar-astron/factor#138]
If you don't have write access to the original MSs then the creation of a virtual column AZEL column in band.py fails. The code catches RuntimeError and assumes it means the column is already present, leading to an unhelpful error message a couple of lines later. Ideally the code should check whether the column is already present explicitly and then not catch RuntimeError allowing what would (presumably) be a more useful error message through to the user.. Very minor but I thought I'd flag it up...

**Comment by darafferty** [comment]
There is now a check for the AZEL column in the current master that should hopefully produce a more helpful error message when there's no write access to the MS files. Please reopen if it not.
