### ISSUE TITLE
Step type avg is unknown and no shared library libavg or libdppp_avg found in (DY)LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/factor#139]
We have the new 2.18 software but when running factor I get the error below. I am using the latest factor master branch version but perhaps I have something else wrong somewhere without realising...

2016-09-16 16:32:18 DEBUG   node.para13.strw.leidenuniv.nl.executable_args.L226343_SB040-049.2ch10s_chunk5_12469B362t_0g.mssort_into_Groups: /net/para34/data1/oonk/lof_sep2016_2_18_0/lofar/bin/DPPP stdout: DEBUG - Step type avg is unknown and no shared library libavg or libdppp_avg found in (DY)LD_LIBRARY_PATH

2016-09-16 16:32:18 WARNING node.para13.strw.leidenuniv.nl.executable_args.L226343_SB040-049.2ch10s_chunk5_12469B362t_0g.mssort_into_Groups: /net/para34/data1/oonk/lof_sep2016_2_18_0/lofar/bin/DPPP stderr: LOFAR Exception detected: [Exception: Step type avg is unknown and no shared library libavg or libdppp_avg found in (DY)LD_LIBRARY_PATH]
in function static LOFAR::DPPP::DPStep::ShPtr (\* LOFAR::DPPP::DPRun::findStepCtor(const string&))(LOFAR::DPPP::DPInput*, const LOFAR::ParameterSet&, const string&)
(/net/para34/data1/oonk/lof_sep2016_2_18_0/lofar/src/CEP/DP3/DPPP/src/DPRun.cc:96)
Backtrace follows:
#0  0x7f60f8805e53 in LOFAR::DPPP::DPRun::findStepCtor(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) at DPRun.cc:94
#1  0x7f60f880a6c7 in LOFAR::DPPP::DPRun::makeSteps(LOFAR::ParameterSet const&) at DPRun.cc:324
#2  0x7f60f880aaec in LOFAR::DPPP::DPRun::execute(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, char**) at DPRun.cc:132
#3  0x404fb6 in main at NDPPP.cc:88

**Comment by tammojan** [comment]
Apparently DPPP is called with a step 'avg' where avg.type is not defined.

**Comment by twshimwell** [comment]
yes looking in the parset I see that apply_phaseonly2.argument.steps contains a avg but this is never defined.

**Comment by twshimwell** [comment]
I removed the avg steps from apply_phaseonly2 and seems to be running again.

**Comment by darafferty** [comment]
Ah. I think I fixed this on the wsclean branch but not the master. I will try to port all the bug fixes over...

**Comment by shulevski** [comment]
I have hit the same issue. David, did you port the fix, or should I do what Tim did? I have initially cloned the branch a while back, that's why I am asking.

**Comment by darafferty** [comment]
Ah -- thanks for the reminder. Should be fixed it on the master branch now.

**Comment by shulevski** [comment]
It works now, the error does not appear. The issue can be closed.
