### ISSUE TITLE
multiscale_selfcal=True and  cell size when switching to lower resolution

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#14]
It can be dangerous to clean with a beam that is highly oversampled, which seems to happen when multiscale_selfcal=True (i..e, 1.5 arcsec pixels with ~20 arcsec beam size). The minor cycle can get unstable in this case because it cuts down the psf image to 80x80 pixels for image-plane deconvolution (hardcoded in casapy clean). Tapering to 20 arcsec would require 3 arcsec beam, on the other hand one has to be careful with the FFT if the cell size does match the resolution of the longest baseline. So for that reason keeping a cell size of 1.5 arcsec is useful.

Forcing multiscale (when imaging with such highly oversampled beam might resolve this). Maybe this is already enforced ? (another option could be to switch to psfmode='hogbom' for this special case, which apparently happens when multiscale clean is used according to http://casa.nrao.edu/docs/TaskRef/clean-task.html#x13-120000.1.10).

**Comment by darafferty** [comment]
Ah, I wasn't aware of this issue. We do enforce multiscale (it's always on during selfcal -- not sure if we really should do this, though).

**Comment by rvweeren** [comment]
Ok, if we keep using multiscale we should be fine (although it slows things down, but the imaging part is probably not a major bottleneck anyway). BTW I think a similar thing I think happens with wsclean, so for the re-imaging of facets at lower resolution the pixel size should be adjusted (but I think you already planned to change the cell size there accordingly).
