### ISSUE TITLE
 No data left after checking input files for band

### ISSUE THREAD

**Issue by manuorru** [lofar-astron/factor#141]
Hi guys, 
does anyone knows how to skip a band who is apparently too noisy? Mi factor run crashes at the beginning when it checks the ms. 

FO - factor - Setting up cluster/node parameters...
INFO - factor - Using cluster setting: "local" (Single node).
INFO - factor - Checking input bands...
ERROR - factor:Band_115.92MHz - No data left after checking input files for band: Band_115.92MHz. Probably too little unflagged data.
INFO - factor:Band_115.92MHz - Exiting!

Can someone help? 
thanks

**Comment by duyhoang-astro** [comment]
Hi Manu. Perhaps remove the input ms file that has the central frequency of 115.92MHz out of your input ms directory (dir_ms)?

**Comment by manuorru** [comment]
well should I remove all 10 SBs around it or only the one entered on 115.92 MHz?

**Comment by darafferty** [comment]
The whole MS (= 10 subbands); however, the wsclean branch should now skip such bands automatically.

**Comment by manuorru** [comment]
Hi David, I just check with Duy the data and the group 115.92 MHz is totally missing . 
SBgr00 is centred at 114.989   and SBgr01 is at 116.942. So I would expect factor not to create that.

**Comment by manuorru** [comment]
I can install the wsclean branch but I am not sure if the version we have in cep3 is the correct one.

**Comment by darafferty** [comment]
The band name should correspond to the "CtrFreq" value returned by msoverview. Can you check the files again?

The version on CEP3 is now the wsclean branch, as I'd like to have it tested since I intend to merge it into master soon.

**Comment by manuorru** [comment]
yes david you are right. the ctrFreq is 115.92 MHz. 

I can test the new version. I need to download a branch or just sourcing your dir I will get the right code?

**Comment by darafferty** [comment]
OK, good. For CEP3, just sourcing the init_factor script in my home directory will set you up to use the  wsclean version.

**Comment by manuorru** [comment]
perfect. I am going to try right now.

**Comment by manuorru** [comment]
It still gives the same error. Shall I delete the SBgr00?

**Comment by darafferty** [comment]
It should give the error (which I will change to a warning) but then it should keep on going. If it stopped, then yes the easiest thing is to remove the offending band.

**Comment by manuorru** [comment]
I post you here the error because it is different then the one I've posted above. 

INFO - factor - Using cluster setting: "local" (Single node).
INFO - factor - Checking input bands...
ERROR - factor:Band_115.92MHz - No data left after checking input files for band: Band_115.92MHz. Probably too little unflagged data.
Traceback (most recent call last):
  File "/home/rafferty/LOFAR/factor/bin/runfactor", line 70, in <module>
    reset_operations)
  File "/home/rafferty/LOFAR/factor/factor/process.py", line 69, in run
    bands = _set_up_bands(parset, test_run)
  File "/home/rafferty/LOFAR/factor/factor/process.py", line 451, in _set_up_bands
    self.log.info('Skipping {} in further processing'.format(band.name))
NameError: global name 'self' is not defined

**Comment by darafferty** [comment]
Ah -- thanks (a stupid copy-and-paste error). Should be fixed now.

**Comment by manuorru** [comment]
I just removed the SB...but it is easy to get it back I am going to counter test.

**Comment by manuorru** [comment]
That's what you wanted: 
INFO - factor - Checking input bands...
WARNING - factor:Band_115.92MHz - No data left after checking input files for band: Band_115.92MHz. Probably too little unflagged data.
INFO - factor - Skipping Band_115.92MHz in further processing

Issue can be closed

**Comment by nudomarinero** [comment]
For future reference. This is related to #103
