### ISSUE TITLE
merge_parmdbs_in_time not working?

### ISSUE THREAD

**Issue by duyhoang-astro** [lofar-astron/factor#142]
My factor run stops at step smooth_amp1. It says "smooth_amps_spline failed"  in the pipeline.log. Further checking the .merge_amp_parmdbs1, I tried to plot it with parmdbplot.py, but nothing is plotted. This seems that something is wrong with it, although its size is 8.8 MB. And the parmdbplot.py log says "RuntimeError: Assertion: domains.size() % nx == 0".

As the individual parmdbs (instrument_slow) seems to be ok, there seems to be something wrong with the merge script (merge_parmdbs_in_time). Anyone knows how to fix this? Does it relate to some packages that I need to update?

Thanks,
Duy

**Comment by darafferty** [comment]
The merge_parmdbs_in_time script basically just copies the values from each individual parmdb into a merged one. Likely there is an issue with two entries overlapping in time or frequency. Some versions of DPPP would write the last time interval to fill the solution interval, which could make it overlap with the next time chunk. Which version of DPPP are you using?

**Comment by duyhoang-astro** [comment]
The DPPP version I am using is 2.18_0.

DPPP: version = 2.18_0 (in CMakeLists.txt: 1.0)
 branch = tags/LOFAR-Release-2_18_0
 overall revision  = 35375
 package revision  = 35301 (last change in package)
 built on para33.strw.leidenuniv.nl by oonk at Sep 16 2016 13:49:52

**Comment by rvweeren** [comment]
Closed due to inactivity. Re-open if necessary.
