### ISSUE TITLE
Source avoidance has caused a facet to be divided into multiple parts....

### ISSUE THREAD

**Issue by manuorru** [lofar-astron/factor#143]
Hi David, I am running the wsclean version of factor. When I keep the direction file and the same order that factor decides the selfcal will start. 
When I try to change the order of the first facet I get the following. 

INFO - factor:directions - Adjusting facets to avoid sources...
ERROR - factor:directions - Source avoidance has caused a facet to be divided into multple parts. Please adjust the parameters (e.g., if a target source is specified, reduce its radius if possible)

Is this a bug?

**Comment by duyhoang-astro** [comment]
Perhaps I had similar problem before. Can you post an image of the field and the facet regions here? The field image can be one of the high-res image in the subtraction step. The regions are in the file regions/facets_ds9.reg.

**Comment by manuorru** [comment]
Hi Duy I am only seeing this message now. Please find the filed and the facets. 
![screen shot 2016-09-27 at 10 57 50](https://cloud.githubusercontent.com/assets/22393901/18866682/5e3ab918-84a1-11e6-82ff-a979c0d8d92d.png)
![screen shot 2016-09-27 at 10 57 36](https://cloud.githubusercontent.com/assets/22393901/18866685/5e51c7fc-84a1-11e6-9d51-a865815340a0.png)

**Comment by manuorru** [comment]
Let me know if you had the same problem. I have to correct my statement above saying that in any case the pipeline gives this error also when I do not change the order of the directions.

**Comment by duyhoang-astro** [comment]
Sorry. It seems that we have different problems. In my case, I specify the target region with a radius. And FACTOR creates regions, one of  which does not belong to any facet nor calibrator associates with. FACTOR gives the same error as yours. I change the radius of the target region and the number of facets and rerun FACTOR until it stops complaining. Unfortunately I don't have the old facet layout to post here. But your facet layout does not show similar problem and may cause by a different error. David may know this more...

**Comment by darafferty** [comment]
Manu, can you send me your directions file and the sky model of your highest-frequency band? I will try to understand what's going wrong. In the meantime, you can disable source avoidance (check_edges = False under [directions]).

**Comment by manuorru** [comment]
Hi David, 

I am traveling until Monday I will show it to you on Tuesday. 

Thanks
Manu

Sent from my iPhone

**Comment by manuorru** [comment]
Hi David do you need the .model or the image.fits?

**Comment by manuorru** [comment]
Please find : on CEP3 in  lhd001:/data/scratch/orru 
L161554_SBgr030-10_uv.dppp.MS.pre-cal.wsclean_high2\* 
factor_directions.txt  
factor.log

**Comment by manuorru** [comment]
Hi David any update? I am planning to run refactor deep, but can you please check what could have caused this error?

**Comment by darafferty** [comment]
I think I’ve now fixed (or at least avoided) the problem. Manu, can you try it again and see if it works?

**Comment by manuorru** [comment]
Hi David, I am now re-running initsbutract deep. It should finish at end of this week I hope. Then I will test factor again. Thanks

**Comment by darafferty** [comment]
Hi Manu,

I think I’ve fixed (or at least avoided) the problem with the facets. Can you try it again and see if it works now?

Cheers,
-David

**Comment by darafferty** [comment]
Closing for now. Please reopen if this issue occurs again.
