### ISSUE TITLE
Moving factor run to new directory

### ISSUE THREAD

**Issue by eretana** [lofar-astron/factor#145]
Dear all.

I moved one factor run from a node to another one.

I just copy the WORKINGDIR, reset the facet that was incomplete, and edit the state files in addition to the parset to able to start the selfcal for the facet. The original MS files used to created the chunk files are in the same location.

It turns out that that the calibrator is not improving at all  in the selfcalibration. It looks like much in each selfcal image. The selfcal reports an error at the end of the step, but nothing in the middle that gives you an idea if a file or missing or something

I was wondering if there is an  path that must be edited somewhere to make it work again.

Looking at the self cal images for the facet in the original location, they look normal, the calibrator images does improve in each selfcal cycle. So, it discards the possibility that the data is not good at all.

Thanks for your help, Edwin.

**Comment by AHorneffer** [comment]
Factor uses a lot of (map-)files that store the absolute path to the files that is uses. So changing the working-directory is complicated. (Aka next to impossible.)

Maybe we can include this with the archiver/de-archiver: #89

**Comment by eretana** [comment]
Yes. but when a new facet is started, the absolute path must be taken from somewhere. So, it this path(s) are changed then it should be possible to start that direction.

**Comment by twshimwell** [comment]
maybe you can get around this with symbolic links Edwin?

**Comment by duyhoang-astro** [comment]
Symbolic links of 'chunks' and 'products' directories work for me.

**Comment by rvweeren** [comment]
Closed due to inactivity (fixed?). Re-open if necessary.
