### ISSUE TITLE
"i" keystroke option broken in wsclean branch 

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#150]
I do not see the facet image when I press "i" in checkfactor.

**Comment by darafferty** [comment]
Should be fixed now. Note that the facet image from selfcal is made with a max of 6 bands (should this be adjustable?), so won't be as deep as the final image (produced after all directions are selfcaled) if you have more bands than 6.

**Comment by rvweeren** [comment]
Huh, are you saying your are making the selfcal image only with 6 bands (if more are available?). So the model that is FFT'ed after selfcal also comes from these 6 bands only ??

**Comment by rvweeren** [comment]
Or are you making the facet image with less bands. But then how can you do the subtract properly for the full bandwidth ? (maybe I'm confused....)

**Comment by darafferty** [comment]
The model is interpolated between the 6 bands (they're spread over the full bandwidth) and then predicted with DPPP (all done just to remove the brightest sources that affect the neighboring facets)

**Comment by rvweeren** [comment]
For the selfcal imaging part (so the "tiny" images shown with keystroke "c") you do use all the bandwidth in wsclean when imaging?

**Comment by darafferty** [comment]
Yes, for selfcal all the data are used, with ~2 bands per wsclean channel image. Wsclean is and used for the predict

**Comment by rvweeren** [comment]
Ok I understand. My concern here is about the consistency of the amplitude-scale in the selfcal and the facet imaging. I presume do you a "smooth" low order interpolation in the facet imaging. However, during the selfcal the amplitudes are not scaled smoothly, but "jump" per block of ~2 bands. (or are you also interpolating the models yourself in the selfcal imaging when you do the FFTs?). Then when you subtract the facet model (smoothly interpolated model) with the DDE solutions (which forces discrete jumps in the flux-scale per ~2 bands) you could get mismatches which might get problematic for bright sources.

So maybe during the selfcal we should image with something like:
-deconvolution-channels 6 -fit-spectral-pol [a] --channelsout [b]

-with [a] ~3 (I guess somewhere between 2 and 5, maybe even more to get capture the power-law scaling of the fluxes)
- [b] the full frequency resolution the input dataset to WSClean (so 30~120 or so depending on the amount of averaging)

In that way we introduce a "smooth" flux-scale along the frequency axis (not sure though how expensive this is in terms of computations). And [a] should be the same at the moment when you interpolate the models in the facet imaging.

Anyway these are just some ideas. Maybe the mismatch is rather small and we can all ignore this and continue as it is.

>  max of 6 bands (should this be adjustable?)

Yes, that would be useful. BTW What sort of interpolation is done here ? (linear interpolation ? what order? (How) Does the order depends on the number of input bands?)

**Comment by darafferty** [comment]
Ah, that's a good point. The calibrator is treated separately from the other sources in the facet, in that the model is made using the selfcal images rather than the facet images, but I now realize that indeed the way the interpolation is done (it's always linear) will result in the mismatch you describe (except for peeling, where of course the input peeling model is used). I have changed it now so that the calibrator model is made using nearest interpolation, which should (I think) result in frequency blocks that match those used for selfcal.

**Comment by darafferty** [comment]
I also added an option ("nbands_selfcal_facet_image" under [imaging]) that allows one to specify the number of bands used to make the facet image during the selfcal operation.

**Comment by darafferty** [comment]
Just fixed a bug I introduced with the new "nbands_selfcal_facet_image" option (even if you don't set the option, the bug is still present). If you run into it, update Factor and restart and it should work

**Comment by rvweeren** [comment]
ok, just updated.
