### ISSUE TITLE
cleanup of facetsubreset

### ISSUE THREAD

**Issue by AHorneffer** [lofar-astron/factor#155]
When looking at the values below, then I get the impression that the cleanup of the facetsubreset directories is not as good as it is for the facetselfcal directories. (FYI: there were two interrupted facets in facetselfcal, and both facetsubreset pipelines were finished.)

> lofard4:Factor-IC324> du -sh work-second/results/*
> 149G    work-second/results/facetselfcal
> 31M     work-second/results/facetsub
> 522G    work-second/results/facetsubreset
> lofard4:Factor-IC324> du -sh work-second/results/facetsubreset/*
> 261G    work-second/results/facetsubreset/facet_patch_247
> 261G    work-second/results/facetsubreset/facet_patch_413
>

**Comment by darafferty** [comment]
Should be fixed now.
