### ISSUE TITLE
re-starting pipelines when using a ram-disk

### ISSUE THREAD

**Issue by AHorneffer** [lofar-astron/factor#156]
In my last run I set `dir_local_selfcal` to `/dev/shm`. One facetselfcal pipeline failed because the machine ran out of memory. Afterwards the temporary directory `/dev/shm/facet_patch_651m_df96a7` was gone (which I believe is a good thing), and when I re-started factor, DPPP complained that the data in `/dev/shm/facet_patch_651m_5cec2e` does not exist.

If the two `sync_*_data_to_local` are supposed to be executed at every pipeline re-start, then they need to be defined as plugins of the genericpipeline. (And this is actually considered more a bug than a feature of the genericpipeline...)

**Comment by darafferty** [comment]
Well, there is no easy way to resume from such a crash, as the files in `/dev/shm` could differ from those on the shared disk (the ones in `/dev/shm` are updated after each selfcal cycle but those on the shared disk are not). Perhaps Factor could automatically roll back the pipeline state to the `sync_files` step? This is what I do by hand to restart after a crash during selfcal.

**Comment by AHorneffer** [comment]
That is also what I did by hand...

In the prefactor repository, there is the `bin/statefile_manipulation.py` tool, that does exactly this. The relevant code from there could be included in Factor. If I find time, I can look into that.

**Comment by darafferty** [comment]
As suggested by @adrabent, I've changed the scheduler to automatically restart when error 123456 occurs (it's apparently due to some race condition in the pipeline framework). As part of this, I also implemented the reset of the statefile when a ram disk is used, so resetting by hand should no longer be needed.
