### ISSUE TITLE
Solve.CellSize.Freq setting

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#16]
David, how do you determine the grouping for TEC+scalarphase for Solve.CellSize.Freq ?

For example if I have 25 "blocks" (=25 channels in the DDE selfcal), then Solve.CellSize.Freq=8 would result in the last block of 1 channel being solved for separately for TEC+scalarphase (which is not what you want).

CellSize.Freq=7 would be more appropriate, as the last part would contain 4 channels. (which is much better than 1). (BTW CellSize.Freq=5 would not result in any rounding issue for this particular example, but there are prime numbers of course for which rounding problems are unavoidable)

Just checking there are no issues here and that the code takes care of it and computes Solve.CellSize.Freq in a smart way.

**Comment by darafferty** [comment]
The interval is calculated in set_averaging_steps_and_solution_intervals() of [direction.py](https://github.com/lofar-astron/factor/blob/master/factor/lib/direction.py) as:

```
num_cal_blocks = np.ceil(nchan * nbands * chan_width_hz/1e6  / 20.0)
self.solint_freq_p = int(np.ceil(num_chan_per_band_after_avg * nbands / num_cal_blocks))
```

So, in your example of 25 blocks (assuming 2 MHz per block), we would get 3 groups (ceil(50/20) = 3) and the cellsize.freq would be set to 9, which I guess is OK? However, we could definitely be a bit smarter, particularly if we allow a range of group bandwidth (from 10 -- 20 MHz?). In this case, we could set a minimum number of bands per block, and use the largest block for which this limit is met that fits in the allowed range of bandwidth.

**Comment by rvweeren** [comment]
Yes, 9 would be ok for this example. The way it is coded now the rounding works fine. If I am correct the smallest number of blocks/bands for which one solves TEC  is 6 blocks (12 MHz). (unless one has less than 12 MHz of bandwidth). Would be useful though for the future if we could set a minimum number of bands per block (so we can tune the smallest possible amount of bandwidth for which TEC+scalarphase will be solved for).

(It is still unclear what the optimum number of bandwidth is for solving TEC, the more the better you would say but the BBS solver seems to get unstable when you provide too much bandwidth (pi jumps))

**Comment by rvweeren** [comment]
Would be very useful if we can specific this.

I think that the current settings are not optimal (causing TEC fitting instabilities, even for high S/N cases) and we have to lower it (for that reason would be good to have this as a parameter).  I am leaning towards going for Solve.CellSize.Freq=4-6 (not the current 6-10), this number depends on the actual dTEC values (it seems when the corresponding TEC phases wrap within the bandwidth that the solutions do not converge, providing less bandwidth avoids the wrapping. (Francesco also noted these sorts of issues in LBA data). Ultimately we need a stable TEC fitter, but for now at least we can experiment with decreasing bandwidth.

**Comment by darafferty** [comment]
I've now added an option called TEC_block_MHz to the [global] section of the parset that specifies the desired bandwidth per TEC block. The default is 10 MHz (so Solve.CellSize.Freq=5). It will try to adjust the Solve.CellSize.Freq setting so that a block gets at least 8 MHz (e.g., for 22 bands of 2 MHz each and TEC_block_MHz=10, it should choose Solve.CellSize.Freq=6 so that the last block has 4 bands).

**Comment by rvweeren** [comment]
Thanks. Closed.
