### ISSUE TITLE
Mosaic-ing fails

### ISSUE THREAD

**Issue by soumyajitmandal** [lofar-astron/factor#161]
I am doing the final mosaic with Factor (quite an old one, probably 3 months earlier version). I am having this

error: node.para14.strw.leidenuniv.nl.python_plugin: Header update sequence item #0 is invalid; the item must either be a 2-tuple containing a keyword and value, or a 3-tuple containing a keyword, value, and comment string

Has anyone seen this? I guess now it is trying to make the fits image? Because in the fieldmosaic/field directory, the file:

L281008_SBgr000-10_uv.dppp.pre-cal_chunk12_126092E6Bt_0g.wsclean_image_full2-MFS-image.make_mosaic
already exists.

**Comment by soumyajitmandal** [comment]
I have attached the pipeline.log this time. 
The primary beam correction has not been done. I think it failed at the make_mosaic stage where it creates the Fits image. Should I just do the primary beam correction on the image: L281008_SBgr000-10_uv.dppp.pre-cal_chunk12_126092E6Bt_0g.wsclean_image_full2-MFS-image.make_mosaic manually?

[pipeline.docx](https://github.com/lofar-astron/factor/files/603733/pipeline.docx)

**Comment by darafferty** [comment]
Likely your problem is due to using an outdated version of the `mosaic_images.py` script (in `factor/scripts/`). You could try updating just this script to the latest version and see if that fixes your problem.

**Comment by soumyajitmandal** [comment]
I know this is an older version of Factor (a couple of months) which might have an issue, but I am still trying with this version in order to complete the last stage of the reduction. Thanks :-)

I tried updating with the new version of the code <code>mosaic_images.py</code>. It seems to go further and now failed at this stage: 

ERROR   node.para14.strw.leidenuniv.nl.python_plugin: Directory: [/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_800_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_398_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_276_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_476_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_999_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_441_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_729_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_222_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_569_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_704_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_314_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_359_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_699_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_427_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_716_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_497_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_429_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_395_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_241_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_582_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_302_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_419_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_310_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_606_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_649_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_780_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_752_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_560_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_641_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_279_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_702_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_658_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_272_save.pkl,/net/para14/data2/mandal/factor_281008/workingdir/state does not exist and cannot be created

the files (eg: /net/para14/data2/mandal/factor_281008/workingdir/state/facet_patch_780_save.pkl) do exist. Any idea what might the reason be?

**Comment by rvweeren** [comment]
Closed due to inactivity. Re-open if necessary.
