### ISSUE TITLE
faceting_skymodel option fails

### ISSUE THREAD

**Issue by Joshuaalbert** [lofar-astron/factor#162]
I produced my own skymodel by combined all the sub bands of the direction independent high res models then using pybdsm with bbs_patches='source' to avoid sources that only pop up at fainter end and lower frequencies but it fails. The last line in the log file is:

```
INFO - factor - Using /net/para34/data1/albert/products/goods-n-prefactor-results/FullBand-Combined.skymodel as sky model for source avoidance and DDE calibrator selection (if desired)
```

**Comment by darafferty** [comment]
After printing that line, it tries to load the sky model (see line 568 of https://github.com/lofar-astron/factor/blob/master/factor/process.py) -- can you load it with lsmtool outside of Factor?

**Comment by Joshuaalbert** [comment]
Hey David sorry I just noticed your reply to this.  I'll try when I'm back from travels Monday.

**Comment by Joshuaalbert** [comment]
@darafferty  it works but there is something wrong with it:
```
In [3]: lsmtool.load('FullBand-Combined.skymodel')
WARNING: Couldn't write lextab module u'angle_lextab'. [Errno 13] Permission denied: u'/software/local/lib64/python2.7/site-packages/astropy/coordinates/angle_lextab.py'
WARNING: Couldn't create u'angle_parsetab'. [Errno 13] Permission denied: u'/software/local/lib64/python2.7/site-packages/astropy/coordinates/angle_parsetab.py'
Out[3]: <lsmtool.skymodel.SkyModel at 0x7f7340c48dd0>
```

**Comment by Joshuaalbert** [comment]
Also this is a different issue than #178.

**Comment by AHorneffer** [comment]
> WARNING: Couldn't write lextab module u'angle_lextab'. [Errno 13] Permission denied: u'/software/local/lib64/python2.7/site-packages/astropy/coordinates/angle_lextab.py'
> WARNING: Couldn't create u'angle_parsetab'. [Errno 13] Permission denied: u'/software/local/lib64/python2.7/site-packages/astropy/coordinates/angle_parsetab.py'
> 

Did you check if you are allowed to read and execute these files? And if the `*.pyc` files exists and you are allowed to read and execute them? And that they are newer than the `*.py` files?

**Comment by Joshuaalbert** [comment]
No I'm only able to read *.py and *.pyc files in that folder. Should I have +x access?

**Comment by AHorneffer** [comment]
Ah, not, execute access doesn't seem to be needed for these files.

Can you do:
`import astropy.coordinates.angle_parsetab`
from another python shell?

**Comment by Joshuaalbert** [comment]
I am able to import that.

**Comment by darafferty** [comment]
Looks a lot like the error here: https://github.com/voidlinux/void-packages/issues/1695

**Comment by darafferty** [comment]
Actually, I reread your earlier post and it could be that these really are warnings and not errors, as it does seem that lsmtool loads the sky model successfully. If that's the case, I don't know why it doesn't work inside Factor. Can you try it again with Factor, in case something changed since you ran it the first time?

**Comment by Joshuaalbert** [comment]
Now there are no issues... running that. There are several changes in the paracluster at leiden though. We had a fedora upgrade to 25, and the lofar software I'm sourcing is for 23. The lsmtool is most recent from github. Either way, this seems not to be an issue at the moment.

**Comment by darafferty** [comment]
OK. Reopen if there are still problems.
