### ISSUE TITLE
oscillating convergency on selfcal - TEC is the same for all RS

### ISSUE THREAD

**Issue by manuorru** [lofar-astron/factor#163]
Hi David, 
I find this very weird behaviour on one relatively simple facet. 
As you can see the convergency oscillate and the TEC sol are all the same for all RS while they vary for CS. The gains for RS are nearly zero. 

The run was started today. Please take a look. 

![screen shot 2016-11-25 at 10 49 08](https://cloud.githubusercontent.com/assets/22393901/20621908/c45f6922-b300-11e6-87bb-cf7341e0be27.png)

![screen shot 2016-11-25 at 10 56 23](https://cloud.githubusercontent.com/assets/22393901/20621916/ceeb1530-b300-11e6-94b2-b0648f9d2f47.png)

![screen shot 2016-11-25 at 10 53 24](https://cloud.githubusercontent.com/assets/22393901/20621929/dc7b4c74-b300-11e6-80da-2b4acd7dc9da.png)

**Comment by manuorru** [comment]
The next facet crashed because of this: 
![screen shot 2016-11-25 at 12 13 20](https://cloud.githubusercontent.com/assets/22393901/20623614/b1860b5a-b308-11e6-9797-5d115c6feea8.png)

**Comment by darafferty** [comment]
I believe this issue has been solved with better subtraction. Reopen if not.
