### ISSUE TITLE
mosaic image beam missing from header

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/factor#165]
The mosaic image produced at the end of factor doesnt seem to have any beam information in the header as far as I can tell.

**Comment by wndywllms** [comment]
I do have the beam BMAJ, BMIN, and BPA in my factor mosaic headers, not sure why you don't?

**Comment by twshimwell** [comment]
Oh ok, well thats good. Maybe its just the version that was used to create this mosaic which is several months old now. I guess this is a non issue then. Thanks.
