### ISSUE TITLE
Factor fails to recognise the "ndir_process" parameter

### ISSUE THREAD

**Issue by bn-w** [lofar-astron/factor#167]
During the execution on CEPIII, I noticed that factor prints out this message (while loading the parameters):

WARNING - factor:parset - Option "ndir_process" was given in the [directions] section of the parset but is not a valid directions optionWARNING - factor:parset - Option "ndir_process" was given in the [directions] section of the parset but is not a valid directions option

I was wondering if it could be that some of the newer versions does not support it anymore?

**Comment by darafferty** [comment]
I can't reproduce this issue -- are you using the latest master? If not, please update and see if it still occurs.

**Comment by rvweeren** [comment]
Closed due to inactivity (and failure to reproduce the error). Re-open if necessary.
