### ISSUE TITLE
factor control stuck in a loop? 

### ISSUE THREAD

**Issue by wndywllms** [lofar-astron/factor#168]
I pulled the latest changes from 09/12 (hoping to use the changes mentioned in https://github.com/lofar-astron/factor/issues/156 ) but now the facetselfcal steps keep on restarting again and again but they have actually been successful so it doesn't need to restart.  If I kill the runfactor process and restart it it will move on to the next direction/group.

Some of the factor log (repeating the 3 directions in the group) below. While I slept it re-ran the facetselfcal pipelines >350 times, each time ending successfully because all the steps are already complete.

INFO - factor:scheduler - <-- Operation facetselfcal started (direction: facet_patch_455)
INFO - factor:scheduler - <-- Operation facetselfcal started (direction: facet_patch_133)
INFO - factor:scheduler - <-- Operation facetselfcal started (direction: facet_patch_147)
INFO - factor:scheduler - --> Operation facetselfcal completed (direction: facet_patch_147)
DEBUG - factor:facetselfcal - Cleaning up files (direction: facet_patch_147)
INFO - factor:scheduler - --> Operation facetselfcal completed (direction: facet_patch_133)
DEBUG - factor:facetselfcal - Cleaning up files (direction: facet_patch_133)
INFO - factor:scheduler - --> Operation facetselfcal completed (direction: facet_patch_455)
DEBUG - factor:facetselfcal - Cleaning up files (direction: facet_patch_455)
DEBUG - factor:scheduler - Time for operation: 0:01:49.956257
QPID support NOT enabled! Will NOT connect to any broker, and messages will be lost!
QPID support NOT enabled! Will NOT connect to any broker, and messages will be lost!
QPID support NOT enabled! Will NOT connect to any broker, and messages will be lost!
INFO - factor:scheduler - <-- Operation facetselfcal started (direction: facet_patch_455)
INFO - factor:scheduler - <-- Operation facetselfcal started (direction: facet_patch_147)
INFO - factor:scheduler - <-- Operation facetselfcal started (direction: facet_patch_133)
INFO - factor:scheduler - --> Operation facetselfcal completed (direction: facet_patch_133)
DEBUG - factor:facetselfcal - Cleaning up files (direction: facet_patch_133)
INFO - factor:scheduler - --> Operation facetselfcal completed (direction: facet_patch_147)
DEBUG - factor:facetselfcal - Cleaning up files (direction: facet_patch_147)
INFO - factor:scheduler - --> Operation facetselfcal completed (direction: facet_patch_455)
DEBUG - factor:facetselfcal - Cleaning up files (direction: facet_patch_455)
DEBUG - factor:scheduler - Time for operation: 0:01:50.551289
QPID support NOT enabled! Will NOT connect to any broker, and messages will be lost!
QPID support NOT enabled! Will NOT connect to any broker, and messages will be lost!
QPID support NOT enabled! Will NOT connect to any broker, and messages will be lost!
INFO - factor:scheduler - <-- Operation facetselfcal started (direction: facet_patch_455)
INFO - factor:scheduler - <-- Operation facetselfcal started (direction: facet_patch_147)
INFO - factor:scheduler - <-- Operation facetselfcal started (direction: facet_patch_133)
INFO - factor:scheduler - --> Operation facetselfcal completed (direction: facet_patch_147)
DEBUG - factor:facetselfcal - Cleaning up files (direction: facet_patch_147)
INFO - factor:scheduler - --> Operation facetselfcal completed (direction: facet_patch_133)
DEBUG - factor:facetselfcal - Cleaning up files (direction: facet_patch_133)
INFO - factor:scheduler - --> Operation facetselfcal completed (direction: facet_patch_455)
DEBUG - factor:facetselfcal - Cleaning up files (direction: facet_patch_455)
DEBUG - factor:scheduler - Time for operation: 0:01:50.362046

**Comment by nudomarinero** [comment]
I have the same problem

**Comment by darafferty** [comment]
Should be fixed now.

**Comment by rvweeren** [comment]
Think this is fixed, problem does not appear in today's version (we can re-open if necessary)
