### ISSUE TITLE
niter=1000 hardcoded in DDE selfcal

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#17]
For very complex calibrators (for example A2256) niter=1000 is not enough. Should we do something about this (working with a clean depth threshold instead, or does that slow down casapy clean too much?) ?

**Comment by darafferty** [comment]
I haven't experimented with using a threshold during selfcal, but it's easy to implement (we already get an estimate of the rms from the masking step). I can make it an option for testing purposes.

**Comment by twshimwell** [comment]
I see similar for a complex field I am looking at. The _full2-MFS_image.fits is cleaned much deeper than the self calibration image and looks much better as a result. Is there an option we can change in the parset?

**Comment by rvweeren** [comment]
Yes, would be useful to test this option and put in a threshold (and increase niter to ~10.000), then it  should automatically clean much deeper for complex calibrator fields.

**Comment by darafferty** [comment]
I've added an option ("selfcal_clean_threshold" under [imaging]) to use a clean threshold instead of a set number of iterations. This option is only available on the reimage branch until it's been tested.

**Comment by rvweeren** [comment]
Thanks. I'll move to the reimage branch to test the many(!) new features as soon as the current run finishes.

**Comment by rvweeren** [comment]
It does use the threshold, but it forgets to change niter. It (niter) should be increased to ~10.000 if selfcal_clean_threshold=True

niter              =  1000
gain               =  0.1
threshold          =  "0.000758192062456Jy"

**Comment by darafferty** [comment]
Should be fixed now. There was a duplicate entry in most of the imaging steps that was setting niter back to 1000.
