### ISSUE TITLE
Get rid of LOFAR_FULL_RES_FLAG (unnecessarily blows up the data size)

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#18]
This columns takes up a significant amount of space and is never used (or going to be used) in factor.

Remove this column when writing the chunks from the input data.

(msout.writefullresflag = True, by default in NDPPP, we should explicitly set it to False in the preprocessing)

**Comment by rvweeren** [comment]
some example code how to remove columns:

import glob
import pyrap.tables as pt

mslist = glob.glob('L343226_SBgr*-10_uv.dppp.pre-cal.ms')

for ms in mslist:
 print 'Removing LOFAR_FULL_RES_FLAG from', ms
 t = pt.table(ms, readonly=False)
 t.removecols('LOFAR_FULL_RES_FLAG')
 t.flush()
 t.close()

**Comment by darafferty** [comment]
I've added LOFAR_FULL_RES_FLAG to the columns to remove during chunking, so it should not be copied any longer.

**Comment by AHorneffer** [comment]
Files that don't need chunking are not copied. That means that the LOFAR_FULL_RES_FLAG column is not removed from the input files. On the other hand I don't like modifying the input files more than needed (maybe the user wants to keep that column for some strange reason), so I don't think we should explicitly remove it in this case. (And by not copying the input files in the first place we save a lot more disk space than by making a copy that is a bit smaller.)

**Comment by rvweeren** [comment]
I never meant to remove it from the input files in factor (btw pre factor should not write these in the first place) but do remove them from the files copied over when factor starts (or not copy them over). In addition, every (N)DPPP write that does averaging ideally has msout.writefullresflag = False. Each time there is averaging DPPP tries to create this column (which is not necessary).

**Comment by AHorneffer** [comment]
O.K. so we agree.
In in the NDPPP calls in the parsets inside Factor that I looked at the "writefullresflag = False" was set, so I guess we can close this issue.
