### ISSUE TITLE
Facet Selfcalibration Failed

### ISSUE THREAD

**Issue by amisk** [lofar-astron/factor#181]
Hello,

I am trying to use factor. My galaxy is rather small and I decided I only want to process three neighboring facets. But now the problem is, that for each of the facets, apparently the facet self calibration fails. But I did find the reason for it, since the output is not very specific. Is there a way to find more information, or anything I can do about it?

Thx.

**Comment by botteon** [comment]
Are the calibrators good? If I've understood correctly there is a check on the residual after the selfcal, if they increase the selfcal fails (check my comment in #173). There are a number of way to deal with that (Sec 9.2.6 in the cookbook).

I have a similar behaviour in some runs: good calibrator but selfcal failed (and also deep negatives #180)
How many bands are you using?

**Comment by amisk** [comment]
Im not really sure how to judge if the calibrators are good.
These are the facets I chose, since I am only interested in the main target.
![facets](https://cloud.githubusercontent.com/assets/19927617/22213092/3428a3de-e193-11e6-8614-69dab1d3990e.png)

These are the selfcal images of facet 324.
![selfcal_324](https://cloud.githubusercontent.com/assets/19927617/22213137/55557410-e193-11e6-8cbd-ea23073003d8.png)

I am using 320 or so subbands.

I am trying it again with multires selfcal and selfcal adaptive threshold..
This is now my parset

[global]
dir_working = /aux/amisk/usb/work
dir_ms = /aux/amisk/usb/prefactor-results_all/

[directions]
flux_min_jy = 0.5
size_max_arcmin = 2.0
separation_max_arcmin = 5.0
minimize_nonuniformity = False
target_ra = 10h52m31
target_dec = +36d37m08
target_radius_arcmin=5
max_radius_deg = 6
allow_reordering = True
directions_file = /aux/amisk/usb/directions3.txt
ndir_selfcal = 16
ndir_process = 16
target_has_own_facet = True
faceting_radius_deg = 0.5

[calibration]
exit_on_selfcal_failure = false
multires_selfcal = True
max_selfcal_loops = 5

[imaging]
make_mosaic = False
image_target_only = True
selfcal_adaptive_threshold = True

[cluster]
ndir_per_node = 1
dir_local_selfcal = /dev/shm
ncpu=16

**Comment by darafferty** [comment]
Indeed, it doesn't look from the images like selfcal is improving things. Your parset looks fine and it doesn't look like masking has gone wrong (a common reason for failed selfcal). Check the selfcal solutions (TEC+scalarphase and gain) for problem stations, times, or bands (you can use the "t" and "g" keys in checkfactor to display the solutions).

**Comment by darafferty** [comment]
It could also be that these calibrators are too faint to start immediately calibrating on them. What are their fluxes? If they are below a Jy or so, you will likely need to first process the brightest sources in the field to reduce the noise in these facets.

**Comment by rvweeren** [comment]
Looks like the calibrator is too faint and in general the approach you are taking is risky with a higher chance of calibration failure and/or problems. This is asking for trouble, because you ignore the rest of the field (which probably has bright sources with strong artifacts that are not properly calibrated in the first place). I suggest to first run the full normal FoV with a limited number of blocks (6-8) and a proper facet layout. Then you can decide what needs to be done and what shortcuts you can take.

**Comment by rvweeren** [comment]
I close this for now because it does not look to be a factor issue/error/bug, but reopen if needed.
