### ISSUE TITLE
Stop after processing a certain number of directions or groups?

### ISSUE THREAD

**Issue by AHorneffer** [lofar-astron/factor#188]
Before I implement something and most of you think that is a bad idea: how about adding a command-line option that stops Factor after processing a specified number of groups?

I often want Factor to stop after processing only a certain number of directions, to save the time to reset directions if something went not the way I wanted. 
Also on a machine where a job is only allowed to run for a certain time before being kicked out, it would be better to stop voluntarily at some time than risk being kicked out during a `facetsub` step.

One can limit the number of directions that are processed with the `ndir_process` parset parameter. but using this is a) cumbersome and b) will cause Factor to start imaging the target if not killed in time.

(Well, and finally such an option would be easy to implement. ;-) )

**Comment by eretana** [comment]
Hi. It would be very useful as it means that it can possible to process certain problematic facets and stop, and decide to make changes without to wait for a unnecessary re-imaging.

**Comment by AHorneffer** [comment]
O.K. That makes two of us. :-)

So I went ahead and implemented it.
