### ISSUE TITLE
typo in filename ?

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#19]
At some point files like these are written with a ' and ] in the filename:

L343226_SBgr047-10_uv.dppp.pre-cal_chunk9.shift_cal'].parset

Probably a typo somewhere ?

**Comment by AHorneffer** [comment]
Nope. It's not a bug, it's a feature. Of the genericpipeline. It automatically generates output filesnames, and when a process gets a list of files as input (e.g. when using NDPPP for concatenation) then it generates these filenames.
