### ISSUE TITLE
Table DataManager error: Data Manager class WEIGHT_SPECTRUM_dm is not registered

### ISSUE THREAD

**Issue by Joshuaalbert** [lofar-astron/factor#198]
I'm getting this error and checking input bands step.

```
File "/net/para34/data1/albert/software/pipeline_software/factor/factor/lib/band.py", line 369, in chunk_input_files
    itertools.repeat(use_compression) ))
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 250, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
RuntimeError: Table DataManager error: Data Manager class WEIGHT_SPECTRUM_dm is not registered
```
Is this to do with factor expecting a column that only gets created with newer runs of prefactor?

**Comment by darafferty** [comment]
I suspect this error has something to do with the Dysco library not being picked up properly. Did you enable compression? If so, can you try without it?

**Comment by Joshuaalbert** [comment]
It was the issue indeed, I wish dysco worked here though given the speed up it is supposed to provide. Perhaps it is because I'm running on rh7.
