### ISSUE TITLE
error

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#20]
Maybe related to the facet the fact that all my chunks for the first block are > 50% flagged) ? (and thus is cannot find the data parameters as there is not usable data for the entire first 2 MHz freq block) ?

INFO - factor - Determining imaging parameters for each direction...
Traceback (most recent call last):
  File "/usr/local/bin/runfactor", line 5, in <module>
    pkg_resources.run_script('Factor==1.0', 'runfactor')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/Factor-1.0-py2.7.egg/EGG-INFO/scripts/runfactor", line 59, in <module>
    test_run=options.t, reset_directions=reset_directions)
  File "/usr/local/lib/python2.7/dist-packages/Factor-1.0-py2.7.egg/factor/process.py", line 71, in run
    test_run, reset_directions)
  File "/usr/local/lib/python2.7/dist-packages/Factor-1.0-py2.7.egg/factor/process.py", line 613, in _set_up_directions
    bands[0].chan_width_hz, bands[0].nchan, bands[0].timepersample,
AttributeError: 'Band' object has no attribute 'timepersample'

**Comment by AHorneffer** [comment]
If there is no time-chunk left that has more than 50% unflagged data, the Factor fails!
I can put a more explicit error message in there tomorrow or so. (I don't trust myself with code right now.)

**Comment by rvweeren** [comment]
I see. I removed the first (bad) block and then the problem is resolved. Possible solutions would be that it should try the next block, or completely not copy over that particular band so that it does not appear in the chunks directory. Or remove it from chunks directory after it discovers that there are no time chunks with good data for a particular band. (For manual runs we do not have worry too much about it but for full automatic processing these bad bands need to be caught somewhere, maybe even in pre-factor)

**Comment by AHorneffer** [comment]
My preferred solution would be to issue an explicit warning and then stop Factor. Of course that would mean that an automatic pipeline needs to be re-started manually.
I can also kick bands with no data left in them out of the list of (frequency-)bands, but that would mean that you don't know which frequency-coverage your result will have unless you actually look at the log-files. (And my experience is that if things don't fail, then nobody looks at log-files.)

**Comment by rvweeren** [comment]
Stopping would be fine.

Although, at some point we need some sort of process (thinking about 3000+ fields of Tier-1 survey data) that removes and finds bad stuff automatically. (maybe in pre factor) BTW printing to the stdout in red would grep the attention of users. [for example]([http://i.stack.imgur.com/AgqpA.png)

**Comment by AHorneffer** [comment]
Well, then try out the recent version. (Yes, the error message should be in red. :-) )

**Comment by rvweeren** [comment]
Excellent! I'll update as soon as my current factor run finishes. I presume we can close this issue then.
