### ISSUE TITLE
Zero flux calibrator

### ISSUE THREAD

**Issue by duyhoang-astro** [lofar-astron/factor#204]
Perhaps, I have multiple issues here. But the reported error is about the zero flux in the facet calibrator. I am running FACTOR on one of the facets, facet_patch_1123. Its calibrator flux written in direction file, facet_direction.txt, is 0.100080330484, and this was also read by FACTOR (reported in the log, linked [facet.log](https://www.dropbox.com/s/pdveur2epmkrpgt/factor_665.log?dl=0)). However, FACTOR crashed because it found NaN Jy for 'Effective flux density'. This is not the case, because the facet_patch_1123 calibrator does have a 'bright' source in it, as shown in image below.
![facet_1249](https://cloud.githubusercontent.com/assets/11923709/24289385/610cb652-1081-11e7-9dee-bd22d9987193.png)

Does any one know why there is this mismatch?

I am not sure if the facet layout is related to the above issue. But the target within the big circle seems to belong to both facets (1123 and 1249)?

**Comment by duyhoang-astro** [comment]
Correction: Factor actually did not find effective flux for the calibrator 1123, even though the generated factor_direction.txt shows that the calibrator flux is 1037.222 mJy. The above value 0.100080330484 is the radius of the calibrator region (in degree).

**Comment by darafferty** [comment]
The error is due to the fact that the 1123 calibrator lies outside of its facet, as Factor will not find any clean components for it in this case. Can you decrease the size of the target circle so that the calibrator is inside its facet? 10-20% or so should do it.

**Comment by duyhoang-astro** [comment]
@darafferty: Yes, it is exactly what you said. I reduced the target circle (not to overlap the 1123 calibrator) and the selfcal is running. Thanks.
