### ISSUE TITLE
Re-imaging outside factor after the Selfcal OK step

### ISSUE THREAD

**Issue by soumyajitmandal** [lofar-astron/factor#205]
Hi everyone,

is there a way to re-image 'target' source after the first **facet-imaging** step. As far as I know, the files to be used for re-imaging can be gathered in the 'faceimage' directory (which is basically created after **image1** step). But I do not know if there is a way to find these files after the facet imaging in the **Selfcal OK** step. If so, what are these files?

**Comment by AHorneffer** [comment]
You mean after only the `facetselfcal` pipeline ran, but before the `facetimage` pipeline ran? Only if you copied the measurement-sets before Factor deleted them to save disk space!

If you meant imaging after `facetimage` pipeline ran, then have a look at: http://www.astron.nl/citt/facet-doc/operations.html#facetimage

**Comment by soumyajitmandal** [comment]
I actually meant right after the <code> facetselfal </code> step. Previously, I have used these files which were named as <code>*mssort-average5</code> and they were about 30 Gb in total for one facet. So these files are not saved anymore?
