### ISSUE TITLE
Selfcal fails for fainter and distant facets

### ISSUE THREAD

**Issue by eretana** [lofar-astron/factor#206]
Hello. I found that factor has problems with the selfcal for fainter and distant facets. 
For example, in the attached image something when wrong in the third iteration.
This do not occur with the old factor, and it increasing manually the sol intervals do not help.
An option is to transfer the solutions from a nearby brighter facet. But, I'm wondering there is an alternative before starting transferring
![ds9](https://cloud.githubusercontent.com/assets/17938191/24471334/17d9bd6e-14c2-11e7-8074-a0b959edfeb5.png)
 the solution? 
Cheers, Edwin.
PS: In the image, ds9, altered the order in the images, the last two images are actually the first ones from the selfcal cycle. The others are in correct order.

**Comment by rvweeren** [comment]
Can you show the checkfactor images? (makes it more clear where it goes wrong and also shows the masks)

(i.e. it went wrong wen it was adding the slow gains in the solve?)

**Comment by eretana** [comment]
Hello.
Do you mean the wsclean_pre and wsclean_post images? They have not been created yet. It failed in the smooth_amps_spline step in selfcal.
I did not show the mask, but I did use appropriate masks for this case  and in the others as well. I used a skymodel from a previous old factor run.
Cheers, Edwin.

**Comment by rvweeren** [comment]
No, the DDE selfcal images, option "c" in checkfactor

**Comment by darafferty** [comment]
Fainter calibrators should be handled better by default now (since preapply_first_cal_phases = True and preaverage_flux_Jy = 1.0 by default, both of which improve the S/N). Please try the new version and reopen this issue if there are still problems.
