### ISSUE TITLE
big cal region, sources removed

### ISSUE THREAD

**Issue by gkokotanekov** [lofar-astron/factor#208]
Hi all,

I include two very bright sources in one calibration region, resulting in a ~1 deg size.

The problem is: the sources seem to get removed when image11 is made.

Do you have a clue what might be causing this?

<img width="621" alt="11" src="https://cloud.githubusercontent.com/assets/1955160/24794514/430f6ab8-1b86-11e7-968f-0362db5612b7.png">

**Comment by rvweeren** [comment]
Something went wrong at image01 ? (were the sources properly cleaned in image01  and was the mask ok?)

**Comment by gkokotanekov** [comment]
The cleaning seems ok for image01.

Here is (the central part of) image01 and its mask:

<img width="697" alt="screen shot 2017-04-07 at 21 38 59" src="https://cloud.githubusercontent.com/assets/1955160/24817050/5402b9b0-1bdb-11e7-95c6-0d366fb5c874.png">

<img width="697" alt="screen shot 2017-04-07 at 21 38 16" src="https://cloud.githubusercontent.com/assets/1955160/24817060/58058240-1bdb-11e7-98a5-0e495df882e6.png">

**Comment by rvweeren** [comment]
Hmmm, weird. Do the solutions derived from 01 show anything strange ?

**Comment by rvweeren** [comment]
Can you also show the checkfactor images (keystroke "c") ? (just to have a better comparison)

**Comment by gkokotanekov** [comment]
I did this experiment above with 10SB.
Now I tried with 40SB and Factor runs as expected, i.e. no sources removed any more.

**Comment by darafferty** [comment]
Good to know -- It could be the handling of just one band (10 SB) is incorrect, but running it on such a little amount of data is not really supported anyway...
