### ISSUE TITLE
changing of in solint_ph solint_amp factor_directions.txt not possible with killing factor first

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#21]
For a "fresh" factor, one cannot edit the factor_directions.txt file if one wants to update solint_ph solint_amp manually. It already has the settings of " factor_directions.txt " loaded in memory (if you press "y" at "Facet and DDE calibrator regions saved. Please check that they are OK before continuing.Continue processing (y/n)? "). 

(if you press n, and restart then factor_directions.txt is overwritten)

So the only way to  a "fresh" factor run with the need to update factor_directions.txt is to 
1. start factor
2. edit factor_directions.txt once it is created
3. press "y"
4. kill it.
5. restart.

Better would be to reload factor_directions.txt again after step "3" so the user has had a chance to edit that file before pressing "y" and there is no need to kill it.

**Comment by darafferty** [comment]
I added another read of the directions file after the user continues, so you should be able to edit the file  and FACTOR will pick up the changes. I also added a bit more info on what it's doing when you do or don't continue.
