### ISSUE TITLE
aliased source

### ISSUE THREAD

**Issue by FedericaSavini** [lofar-astron/factor#216]
Hello everybody,

I have an issue with a low-dec field. In my init-sub images I got an outlier source. At first, I created a sky model for it and added a line in the direction file for factor.

outlier 04h39m31.1592s,23d10m47.388s empty empty 512 1 120 LD empty empty /lofar4/stnv039/A478/skymodels/outlier.skymodel True 1 4000

FORMAT = Name, Type, Ra, Dec, I, Q, U, V, MajorAxis, MinorAxis, Orientation, ReferenceFrequency='147500000.0', SpectralIndex='[]'
J043703.0+212953, GAUSSIAN, 04:37:03.0072, +21.29.53.268,    0.4129, 0, 0, 0, 16.6, 6.0, -27.1, , [-0.73]
J043459.5+215536, GAUSSIAN, 04:34:59.5272, +21.55.36.624,    1.2470, 0, 0, 0, 57.9, 13.9, 12.6, , [-0.73]
J043506.5+215513, GAUSSIAN, 04:35:06.5712, +21.55.13.764,    1.0288, 0, 0, 0, 63.9, 12.4, 12.9, , [-0.73]
J043444.3+221058, POINT   , 04:34:44.3664, +22.10.58.404,    1.6410, 0, 0, 0,     ,     ,      , , [-0.73]
J043559.5+231649, POINT   , 04:35:59.5584, +23.16.49.872,    0.3235, 0, 0, 0,     ,     ,      , , [-0.73]
J043658.9+231253, POINT   , 04:36:58.9296, +23.12.53.496,    0.4877, 0, 0, 0,     ,     ,      , , [-0.73]
J043700.8+231252, POINT   , 04:37:00.8976, +23.12.52.056,    0.6355, 0, 0, 0,     ,     ,      , , [-0.73]
J043845.9+214901, POINT   , 04:38:45.9192, +21.49.01.128,    0.3304, 0, 0, 0,     ,     ,      , , [-0.73]
J043856.7+215158, POINT   , 04:38:56.7600, +21.51.58.752,    1.7528, 0, 0, 0,     ,     ,      , , [-0.73]
J043855.9+215310, POINT   , 04:38:55.9248, +21.53.10.896,    0.5130, 0, 0, 0,     ,     ,      , , [-0.73]
J043856.8+223653, POINT   , 04:38:56.8440, +22.36.54.000,    0.6986, 0, 0, 0,     ,     ,      , , [-0.73]
J044028.0+224015, GAUSSIAN, 04:40:28.0200, +22.40.15.060,    0.9727, 0, 0, 0, 9.7, 5.5, -30.3, , [-0.73]
J043931.1+231047, GAUSSIAN, 04:39:31.1592, +23.10.47.388,    5.5746, 0, 0, 0, 14.1, 3.9,  -42.6, , [-0.73]

However, self-cal on some facets was failing and it was hard to explain why that outlier source (5 Jy) would cause all these problem. So widening the search, we found a 3C source (3C123, 270 Jy) at the same RA but 7 degrees northern of where the source appears in the init sub images. It looks like an aliased source, since the position changes from image to image in init subtract, and so does in a second pointing of the same field.

I am not sure how to deal with this. I hope you can help!
Thank you!

<img width="511" alt="facets" src="https://user-images.githubusercontent.com/24634920/30701013-8a74e6e4-9ee9-11e7-9fad-a89cf2c9470b.png">
<img width="410" alt="initsub" src="https://user-images.githubusercontent.com/24634920/30701051-a2ca1c46-9ee9-11e7-8503-43551b155dd1.png">
<img width="1440" alt="121mhz-l596049 l594753" src="https://user-images.githubusercontent.com/24634920/30701072-ae8d60ec-9ee9-11e7-906f-75c3bdb29193.png">
<img width="1440" alt="l596049-121mhz 148mhz" src="https://user-images.githubusercontent.com/24634920/30701075-aeb283ea-9ee9-11e7-926c-47f49d019f1a.png">
<img width="974" alt="facet_89" src="https://user-images.githubusercontent.com/24634920/30701076-aecda2f6-9ee9-11e7-8e7c-cc70822f628f.png">

**Comment by duyhoang-astro** [comment]
In cases like this, I often set Factor to run on the outlier sources first. This can be done by moving the outlier source info to the first lines of the direction file (factor_directions.txt, but still below the comment lines.) . In your run, it seems that Factor starts from some facets that are close to the pointing centre first. And since the outlier source has not been subtracted (or residuals are still high), that causes problems in the amplitude calibration steps... Maybe you could try to run Factor on the outlier sources first...

**Comment by rvweeren** [comment]
It turns out this is the Sun.
