### ISSUE TITLE
checkfactor fails to show updates after step 73 in selfcal (keeps showing merger_selfcal_parmdbs)

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#22]
At some point in the selfcal (after the first few cycles have been done), checkfactor keeps showing  Current step: merger_selfcal_parmdbs, while it still is doing more selfcal iterations. First few selfcal iterations are handled fine but then the update "fails" and (once it goes out of the selfcal part it does show new updates).

<img width="448" alt="checkfactorproblem" src="https://cloud.githubusercontent.com/assets/3879473/13905609/0d057160-ee9b-11e5-89b0-ee68bcf7881f.png">

**Comment by darafferty** [comment]
Yeah, this issue is due to the way the pipeline handles loops - there's no easy way to get the current step while its looping. But maybe we can use some of the info (mapfile names) in the statefile to infer it.

**Comment by darafferty** [comment]
I changed checkfactor to use the mapfile of the previous step to infer the current step name. It should work OK for loops except in cases in which the previous step was the last step of the loop. In these cases, it can't know whether the loop stopped or restarted until the next step finishes, so it could be wrong for a short time.

**Comment by rvweeren** [comment]
Ok thanks, that's good enough. I'll close this issue.
