### ISSUE TITLE
poly2sky script problems

### ISSUE THREAD

**Issue by tikk3r** [lofar-astron/factor#224]
There's a comma missing between `-f` and `--fits_mask` in the argument parsing section:
https://github.com/lofar-astron/factor/blob/daf1a090730b4341900aa4c16d552a04558ce29f/factor/scripts/poly2sky.py#L135
should read
```Python
    parser.add_argument('-f', '--fits_mask', help='Filename of fits mask', type=str, default=None)
```
The `interp` argument is also not specified/used in `main`. Neither affect pipeline runs, but it crashes on this when running it as a standalone script.

**Comment by darafferty** [comment]
Thanks! Should be fixed now.
