### ISSUE TITLE
Python argument types in ParmDB._getValues did not match C++ signature

### ISSUE THREAD

**Issue by tikk3r** [lofar-astron/factor#225]
Trying some further out sources (with international station) the pipeline crashes at `convert_merged_selfcal_parmdbs` with the following error:

```
2018-10-24 21:09:22 ERROR   node.lofar7.strw.leidenuniv.nl.python_plugin: Python argument types in
    ParmDB._getValues(parmdb, str, numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray, bool, bool)
did not match C++ signature:
    _getValues(LOFAR::BBS::PyParmDB {lvalue}, std::string parmnamepattern, double sfreq, double efreq, double freqstep, double stime, double etime, double timestep, bool asStartEnd=True, bool includeDefaults=False)
    _getValues(LOFAR::BBS::PyParmDB {lvalue}, std::string parmnamepattern, double sfreq=-1e+30, double efreq=1e+30, double stime=-1e+30, double etime=1e+30, bool asStartEnd=True, bool includeDefaults=False)
2018-10-24 21:09:22 INFO    node.lofar7.strw.leidenuniv.nl.python_plugin: Total time 1.7829s; user time: 0.9904s; system time: 0.4249s
```

I'm using v3_2_2 of the LOFAR software and commit `daf1a09` of factor (October 1st). Two other sources went fine. One is at the phase center and one is about 0.5 degree away. This error shows up for a couple of sources about 1.5 degrees away.

Is this related to my software install or did something go wrong during calibration? It made the *02-image.fits through *42-image.fits and they all contain the source.

**Comment by darafferty** [comment]
I'm not sure, but I suspect it has something to with the frequency and time grids being wrong somehow. Can you make available the *.merge_phase_parmdbs file, the *.smooth_amp2 file, and the file listed in facetselfcal/facet_patch_XX/mapfiles/expand_preapply_parmdbs.mapfile if this mapfile exists? I can then try it myself and see if I can reproduce the problem.

**Comment by tikk3r** [comment]
The expand_preapply_parmdbs.mapfile does not exist there. I have uploaded the parmdbs here: https://owncloud.strw.leidenuniv.nl/index.php/s/C35n47OLmvrObxe

**Comment by darafferty** [comment]
Thanks -- I think I fixed the problem (by reading the *. smooth_amp2 file in smaller blocks -- likely there is a bug in lofar.parmdb that limits how much can be read in some cases). Can you update and retry (you should be able to simply restart Factor without resetting anything)?

**Comment by tikk3r** [comment]
Yep, that looks like it fixes it. It's now at the `prepare_imaging_data` step. Thanks again.

**Comment by tikk3r** [comment]
It finished the facet perfectly, so it worked.
