### ISSUE TITLE
facetselfcal: NaN in pre_average step

### ISSUE THREAD

**Issue by tvanhateren** [lofar-astron/factor#227]
I'm running factor on some test data from the lofar archive.
However it is crashing on some facets when the pre_average step is performed.
![Factor-status](https://user-images.githubusercontent.com/47851187/55620472-458e1e80-579b-11e9-9034-d2210059f45b.png)
[facet_patch_807.out.log](https://github.com/lofar-astron/factor/files/3047392/facet_patch_807.out.log)
The data coming out of pre-factor looks normal, and many of the facets calibrate just fine.

**Comment by darafferty** [comment]
Ah yes -- I just encountered this myself. I've committed what I hope is a fix. Are you using the v2.0 prerelease (i.e., the current master, compatible with prefactor v3.0)? If so, can you update to the latest version of the master branch and try it again? (A simple restart should work, no need to delete anything.)

**Comment by tvanhateren** [comment]
Yes, I was/am using the master branch, and I can confirm that the fix works for me.
