### ISSUE TITLE
solution smoothing uses ~80% of processing time in DDE selfcal

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#23]
I solved used the HD option and a solution interval of solint_amp = 1. (working with a 70 Jy source) The smoothing of these solutions takes longer than calibration (4+ hrs for a single smooth). 
Even using 'LD' and solint_amp = 1 already causes a noticeable slow down due to the smoothing.

I think the main problem is that (1) the lofar.parmdb interface is slow (not fully sure) and (2) the smoothing is not run in parallel (in the manual scripts the smoothing is run in parallel as each block has its own instrumentdb). Not entirely clear what the right solutions is but we need to improve performance.

For example,  we might try reading all solutions at once in a numpy array and then smooth  (to avoid the lofar.parmdb interface as much as possible, I think these many "parms[…]" are slow) and run the smoothing in parallel (maybe via pp, as we do it with the clock-tec fitting).

**Comment by tammojan** [comment]
To work around the parmdb interface you could access the values from the table itself. If you don't change the intervals that should work.

**Comment by rvweeren** [comment]
BTW the relevant script is [smooth_amps.py](https://github.com/lofar-astron/factor/blob/master/factor/scripts/smooth_amps.py)

**Comment by AHorneffer** [comment]
I didn't notice any serious time-consumption from smooth_amps.py in my processing.

It would help to know if most of the time is spent in the lofar.parmdb interface or if it is indeed the smoothing itself.
There are only 6 calls to the lofar.parmdb interface:

> pdb = lofar.parmdb.parmdb(instrument_name)
> parms = pdb.getValuesGrid('*')
> antenna_list = set([s.split(':')[-1] for s in pdb.getNames()])
> pdbnew = lofar.parmdb.parmdb(instrument_name_smoothed, create=True) 
> pdbnew.addValues(parms)
> pdbnew.flush()

**Comment by darafferty** [comment]
My feeling is that it is not the calls to lofar.parmdb -- as you say, there are just a few calls, and the parmdbs are not very large (< 10 MB?). I suspect its the smoothing, which is easy to parallelize over channels with the multiprocessing module (I'm testing it now).

**Comment by darafferty** [comment]
I've tested it and it seems to work, so I've committed it to the master branch. Reinout, can you try it on your HD solutions? You can run the script by hand in IPython from the facet selfcal directory (e.g., dir_working/results/facetselfcal/facet_patch_285) with:

```
from factor.scripts import smooth_amps
smooth_amps.main('L158196_SB035_uv.dppp.dpppcopycol_chunk11_122DBB3E0t_0g.merge_amp_parmdbs2', 'test_smooth')
```

**Comment by rvweeren** [comment]
Does help a bit, but not what I would expect. It indeed uses many more CPUs, but the usage per CPU is low as it seems to "wait" all the time, the processes are listed as being in "S" mode quite often (which is silly since I am reading from a super fast PCI SSD cad). This seems related to accessing the info in the parmdb. I think that even a call like "parms[gain + ':' + pol + ':Real:'+ antenna]['values'][:, chan]" is slow, maybe the "parms" is not an array loaded in memory and it performs some very slow operations each time at this step ( and the parms[] calls are performed many times during a smooth).

**Comment by tammojan** [comment]
I'm afraid that a call to parmdb may do some interpolation to get the parameters onto a grid.

**Comment by rvweeren** [comment]
just checked:

parms = pdb.getValuesGrid('*')

parms is indeed not a numpy array. 

Maybe we should do

array = parms.values()

Do all our computations and then write the result back ?

**Comment by darafferty** [comment]
I think I see the problem: multiprocessing pickles the arguments for each process, one of which was the full parms (which is just a dict of numpy arrays). So, it was writting the full parms dict to disk for every channel, so there was a lot of I/O.

I've changed it to only pass the solutions for the each channel, so it should mean a lot less I/O (by a factor of `nstat*npol*nchan`!). Can you try it again?

**Comment by rvweeren** [comment]
Much better now! It took 15 min to smooth (compared to 4 hrs before).
