### ISSUE TITLE
aliasing artifacts when using casa as facet imager

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#24]
To my surprise I noticed some aliasing in factor when I used casapy as facet imager.
(so -not- wsclean)

Attached figure shows the low-res verification images after subtracting of the facet from the full-res data. Left is the verification image when I used `facet_imager = casapy` and the right one with `facet_imager = wsclean`. Not really sure what is going on, but I suspect that the casapy ftw run on the full-res data does not use enough wplanes. I am trying to figure out how it computes the number of planes used. David, could you point to that ? (also for the DDE selfcal part, how does it determine the number of w-planes ? I remember that for our manual scripts this was hardcoded in an awkward way and maybe some of this propagated into factor? (we should compute this based on image size, freq, and cell size, as wsclean does)

<img width="827" alt="artifactfromcasaftw" src="https://cloud.githubusercontent.com/assets/3879473/13930635/173350cc-ef76-11e5-8428-5ebe1c4f580c.png">

**Comment by darafferty** [comment]
I think we are using the same method as the scripts (in lib/direction.py in set_wplanes(), both for selfcal and for the full facet image):

```
    def set_wplanes(self, imsize):
        """
        Sets number of wplanes for casa clean

        Parameters
        ----------
        imsize : int
            Image size in pixels

        """
        wplanes = 1
        if imsize > 512:
            wplanes = 64
        if imsize > 799:
            wplanes = 96
        if imsize > 1023:
            wplanes = 128
        if imsize > 1599:
            wplanes = 256
        if imsize > 2047:
            wplanes = 384
        if imsize > 3000:
            wplanes = 448
        if imsize > 4095:
            wplanes = 512

        return wplanes

```

I believe Andre said WSClean calculates it as:

```
maxW = the maximum w value of all gridded data
cMinW = normally 0 (it will only be set to -maxW if the image made is complex, i.e. XY or YX)

maxL = width * pixelSizeX_in_radians * 0.5,
maxM = height * pixelSizeY_in_radians * 0.5,
lmSq = maxL * maxL + maxM * maxM;

if(lmSq < 1.0)
   radiansForAllLayers = 2 * M_PI * (maxW - cMinW) * (1.0 - sqrt(1.0 - lmSq));
else
   radiansForAllLayers = 2 * M_PI * (maxW - cMinW);

nwlayers = ceil(radiansForAllLayers);
```

Does this look right? If so, I can add it to factor.

**Comment by rvweeren** [comment]
Yes (I guess maxW is in units of lambda). 

BTW the minimum should be 64 for casa (it gives warnings that things might not be accurate if you use a values less than 64, but larger than 1): 64 does not take much more computing time than 1 so I think can we can safely use that as the minimum value.

The only way I can see this going wrong is that if the number of wplanes gets so high we run out of memory. This is of course completely system dependent (but artificially lowering it also means we are making an error, one would need to switch to wsclean in this case). What would a typical value be for a 4096 image ? (got stuck with "M_PI", what is this ? 3.14 ?)

**Comment by darafferty** [comment]
Ah, we were using wplanes = 1 for all isolated, point-like calibrators (because their image size = 512). I have changed it as you suggested so that they get at least 64.

Not sure what M_PI is -- I can probably find out from the wsclean source code.  From one of my runs, for a 4800 x 4800 pixel image and 220 subbands, it seems that wsclean used ~ 700 wplanes.

**Comment by rvweeren** [comment]
Ok, ~700 sounds very reasonable.

**Comment by rvweeren** [comment]
Wondering if the aliasing issue with casapy (ftw) subtract is caused by the fact that the number of w-planes is set according to the image size (not the full FoV). However, it will be impossible to increase the number of w-planes to a value appropriate for the full FOV (with 1.5 arcsec pixels size), we will run out of memory. (so we might have to live with it, or simply use wsclean)

**Comment by rvweeren** [comment]
Close this for now.
