### ISSUE TITLE
plotting of (tec) phases, too crowded, need a longer time (x-axis)

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#26]
We need a much longer x-axis for plotting the tec phase solutions. It is difficult/impossible to judge the (distant) RS stations now and spot problems: [1 x number of stations size] plot grid.

So something that looks more like this [example](http://lofar.strw.leidenuniv.nl/wiki/lib/exe/detail.php?id=p209_55_factor&media=p209_55_3c295_phasesols.png)

**Comment by rvweeren** [comment]
Ok, I played a bit with the plotting code. This can be easily accomplished by changing to the code below in the function solplot_tec in  [plot_selfcal_solutions.py](https://github.com/lofar-astron/factor/blob/master/factor/scripts/plot_selfcal_solutions.py). Same change for  solplot_scalarphase. 

 An example image is shown below

```
#Nr = int(np.ceil(np.sqrt(Nstat)))
#Nc = int(np.ceil(np.float(Nstat)/Nr))

Nr = int(Nstat)
Nc = 1

f, ax = plt.subplots(Nr, Nc, sharex=True, sharey=True, figsize=(12,72))
```

![test_tec](https://cloud.githubusercontent.com/assets/3879473/14051124/e8485a40-f296-11e5-82fc-0723c5fb6043.png)

**Comment by twshimwell** [comment]
That looks much better.

**Comment by darafferty** [comment]
OK, I've made the changes above.
