### ISSUE TITLE
hardcoded cell size of 1.5arcsec

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#28]
The cell size of 1.5arcsec was based on my original Toothbrush dataset which did not included RS210. With RS210 included might be we have to go to 1.0arcsec for optimal results (because with RS210 the longest baseline is significantly increased). Would it be possible for the user to overwrite the default 1.5 arcsec via the parset ?

**Comment by rvweeren** [comment]
Related to changing the 1.5arcsec cell size could you also make the robust value (during DDE selfcal and facet imaging, e.g., "robustselfcalimage" and "robustfacetimage") parameters that can be set in the parset ? 

And also for the uv-range. For galactic fields we need to have full control over the uv-range, during DDE calibration, DDE imaging, and facet imaging. So "uvselfcal", "uvselfcalimage", "uvfacetimage".

**Comment by darafferty** [comment]
The cellsize, robust, taper, and uv options are now available on the reimage branch. See my comment on issue #5 for details.
