### ISSUE TITLE
Stopping criteria selfcal

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#29]
Hi David

Could you add the stopping criteria I developed to the selfcal? You DR criteria works but I think this can be further improved. (I still see clear improvements in the  abs(min(image)/max(image)) in the selfcal, but your dynamic range criteria fails to notice that)

So as long as one of the two criteria, dynamic range OR abs(min(image)/max(image)), keeps improving stay inside the selfcal loop. My criteria should help to further remove small local artifacts around the calibrator source (that is not captured by looking at the overall rms). It should be very easy to add this to the code.

**Comment by darafferty** [comment]
I've added the min/max criterion as suggested to the existing dynamic range one. Currently, an improvement of 1.25% or more (in either criteria) is required to continue looping.

**Comment by rvweeren** [comment]
Great! I'll close this issue.
