### ISSUE TITLE
disks usage for calibrated facets

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#32]
I've noticed that after a facet is calibrated there a significant amount of disks space that is used for that facet, even though I put:
keep_avg_facet_data = False
keep_unavg_facet_data = False

For example I see:

L343226_SBgr025-10_uv.dppp.pre-cal_chunk9_12656E813t_0g.mssort_into_Groups
L343226_SBgr025-10_uv.dppp.pre-cal_chunk9_12656E813t_0g.mssort_into_Groups_blavg.ms
L343226_SBgr025-10_uv.dppp.pre-cal_chunk9_12656E813t_0g.mssort_into_Groups_corrdata.ms

There might be a reason why these files are kept ?

**Comment by darafferty** [comment]
No, these should be deleted. I've added them to the cleanup list. There will still be significant disk usage by the files needed to reset a facet that's been through the subtraction operation (at the moment, I delete them by hand when I'm sure they're not needed).

**Comment by rvweeren** [comment]
We can also delete the *full1*.fits files.

BTW what are the file/ms names it uses for the reset ?

**Comment by darafferty** [comment]
The reset files are the "shift_diff_model_to_field" ones.

**Comment by rvweeren** [comment]
I general we should have a look at cleaning up stuff (and further reduce disks usage). Removing the reset dependence on "shift_diff_model_to_field" would make a huge difference.

(maybe we need to have a miminize_disks_usage = T/F switch)

**Comment by darafferty** [comment]
My feeling is that we can just delete the "shift_diff_model_to_field" files and always regenerate them if a reset is required. And if we then also clean up all the stuff like the full1 images, we will have low disk space usage by default (and not need an option for this).

**Comment by AHorneffer** [comment]
As already hinted at during the telecon yesterday: my suggestion would be to move away the files that are still needed by Factor (i.e. those for which we keep the mapfiles) and them remove the pipeline directory. That will remove everything that is no longer needed. (Also the files for which we cannot know the exact file name, like the random directories for casa.)

**Comment by rvweeren** [comment]
Agreed, sounds like a good way to clean things up

**Comment by rvweeren** [comment]
I noted that the "full1" fits files made with wsclean are not yet removed. Can these be added to the clean-up list ? (they are never used once a facet finished successfully)

They can take up a considerable amount of disk space (in particular because of the wideband clean as it stores all the channel maps).

**Comment by darafferty** [comment]
The "shift_diff_model_to_field" files are deleted now (on the reimage branch only at the moment, as the new subtract reset pipeline still needs testing). I still need to add the full1 images to the cleanup list.

**Comment by darafferty** [comment]
The full1 images should be deleted now as well.

**Comment by rvweeren** [comment]
Disk usage has hugely improved in the reimage branch, only a few GB per facet now in the selfcal (with a 60 SB run). Closing this.
