### ISSUE TITLE
clean components placed on artifacts for a source that is on the facet boundary

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#34]
Factor tried to avoid a source at facet boundary, but after the FFT subtract negative emission appears close to that location. I think the problem is that there are clean components placed on the artifacts at the right side of the source. (because artifacts at the right side of the source are picked up by the mask).

The problems seems to be that the avoidance radius around the source is way too tight. Needs to be a least 3-4 times as large I think, see second attached image with a red circle that has 3x the radius of the current factor avoidance circle. (not sure how that avoidance radius is computed….but it is clearly too small at the moment)

<img width="888" alt="sourceavoidance" src="https://cloud.githubusercontent.com/assets/3879473/14085792/e76623c2-f4ef-11e5-955f-413fe864282e.png">

<img width="301" alt="sourceavoidance2" src="https://cloud.githubusercontent.com/assets/3879473/14085791/e75b8ee4-f4ef-11e5-80b3-cb19413ce53c.png">

This is the 25 arcsec image calibrated against the TGSS, showing the facet layout. At this resolution and depth, the artifacts that show up in the facet image are not revealed.

<img width="250" alt="sourceavoidance3" src="https://cloud.githubusercontent.com/assets/3879473/14088740/2419283c-f4ff-11e5-965a-baea801fca68.png">

**Comment by darafferty** [comment]
I have adjusted the minimum size to scale with the square root of the flux of the source, so that brighter sources get larger minimum region sizes (e.g., a 0.3 Jy source will have a region about 3 times larger than before). Let me know if it needs tuning.

**Comment by rvweeren** [comment]
Thanks for the quick update. I'll let you know if further changes are required (but this might be sufficient). I'll close this for now.
