### ISSUE TITLE
Multiscale cleaning for full facet

### ISSUE THREAD

**Issue by AHorneffer** [lofar-astron/factor#39]
I only get Factor to do multiscale cleaning on the full facet image when I explicitly switch it on in the directions.txt file. 

But if I interpret the code correctly the default should be that Factor figures out on its own that there is at least one extended source present and switches on multiscale cleaning. Does that work for anyone?

**Comment by darafferty** [comment]
Some tuning is probably needed (lower the large_size_arcmin value or perhaps set weight=False in get_source_sizes). Do you have a case in which it should definitely be turned on that could be used for tuning?

**Comment by AHorneffer** [comment]
In the attached skymodel in the center there is NGC891 (at ra = 02h22m33.4  dec = +42d20m57) and 3C66b (at ra = 02h23m10  dec = +42d59m20). 
I just noticed that Factor indeed does multiscale cleaning on 3C66 (I had that explicitly switched on in the directions file since ages), but it doesn't do it on NGC891.

[L115633_SBgr005-11_uv.dppp.pre-cal.wsclean_low2-model.merge.gz](https://github.com/lofar-astron/factor/files/197879/L115633_SBgr005-11_uv.dppp.pre-cal.wsclean_low2-model.merge.gz)

**Comment by darafferty** [comment]
I tuned the parameters, so it should now turn on multiscale cleaning for sources with sizes above ~6 arcmin. NGC891, 3C66, and 2 other sources exceed this size in above skymodel. Probably still needs more testing/tuning, but it should hopefully pick up the obvious sources now.

**Comment by AHorneffer** [comment]
Thanks.
(Not sure if I manage to test that next week, though.)

**Comment by adrabent** [comment]
In one of my facets where a large radio galaxy is present, multiscale was turned on.
This seems to work quite well, although a lot of different scales [0, 3, 7, 25, 60, 150] have been computed. This tooks nearly ~2 days per image (32 CPUs).

**Comment by AHorneffer** [comment]
Old story: when to do multiscale cleaning (and clean-mask generation) and when not to.

In the example below the decision not to do multiscale is apparently wrong. On the other hand the source is less than 4 arcminutes in diameter, as you can see from the model map from the initsubtract step.

As an intermediate step I suggest to print out for which facets it is going to do multiscale cleaning.

![selfcal_images_for_facet_patch_327m_scaling_noise_ _0 246_mjy_beam](https://cloud.githubusercontent.com/assets/900708/20104671/211132b6-a5cf-11e6-92c9-0ffcfa1fa22c.png)
![initsubtract_high2-model_facet_patch_327m](https://cloud.githubusercontent.com/assets/900708/20104672/2112e534-a5cf-11e6-8546-b2d8e345eb9b.png)

**Comment by darafferty** [comment]
Indeed. Though maybe it's not so much the lack of multiscale clean but rather the fact that the wavelet module was not used during masking? They're both activated at the same size at the moment, but perhaps the wavelet module should be activated at smaller scales?

**Comment by darafferty** [comment]
Actually, I guess the decision to use the wavelet module should be related to the rms_box value (which is set to 80 pixels). So, if there is a source larger than ~1/2 the size of the rms_box, or ~ 1 arcmin, the wavelet module should be used.

**Comment by AHorneffer** [comment]
Yes, in this example it was the lack of the wavelet module, this happened during selfcal. (I was just too lazy while typing.)
I now manually switched on multiscale clean and the wavelet module for those facets. But I can do another run with only the wavelet module.

P.S. I still think it is a good idea to print out when multiscale clean or the wavelet module is used for a facet.

**Comment by AHorneffer** [comment]
continued in: #159
