### ISSUE TITLE
Skip successful steps when re-running.

### ISSUE THREAD

**Issue by AHorneffer** [lofar-astron/factor#4]
When Factor is re-run it currently executes each step again, and only the (generic-)pipeline notices that it already ran.
Successful steps should not be started...

**Comment by darafferty** [comment]
The scheduler should now skip running the generic pipeline on previously completed operations. It will still run the finalize() method so that the direction objects are properly updated.

**Comment by darafferty** [comment]
This seems to be working well in my testing, so I will close this issue for now.
