### ISSUE TITLE
smoothing on outlier fields with user model given

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#46]
Just checking: -no- smoothing should be done for outlier fields -with- a skymodel given by the user.

Because in this case the source might go through the sidelobes and the amplitudes could be very close to zero (like Ateam subtraction). The current smoothing codes includes for example:

```
            # Clip extremely low amplitude solutions to prevent very high
            # amplitudes in the corrected data
            low_ind = numpy.where(amp < 0.2)
            amp[low_ind] = 0.2
```

which would create all sort of problems in this scenario.

Also because in this case the flux normalization for the source could be different (true vs apparent flux and that could create average amplitudes that systematically deviate from 1.0, for example if CygA would be an outlier source, with a skymodel given the gain is likely to be < 0.1).

(for outlier fields -without- a user specified sky model it is best to still do smoothing as it needs to go through a DDE selfcal cycle and needs to image)

**Comment by darafferty** [comment]
Indeed - I've now removed this clipping when no normalization is done. Probably it can be removed entirely once the improved smoothing and outlier rejection (issue #31) is ready .
