### ISSUE TITLE
simulation pipeline

### ISSUE THREAD

**Issue by Joshuaalbert** [lofar-astron/factor#47]
There is a gaping need for a simulation pipeline that:
1) takes a model with given compact and diffuse emission,
2) propagates this through a given atmosphere introducing WKB approximated phase changes (ie no reflection)
3) computes visibilities
4) calls a calibration and imaging pipeline

This will at least be useful for:
1) isolating erroneous results generated through calibration and imaging
2) comparing quality of various imagers/solvers
3) investigating the effects of various structure in the ionosphere on solutions

Timeline and Who:
Francesco and I intend starting work in late April/ early May 2016. We are able to speed up the process by taking an inventory of past work by individuals in this area. Alex Mepchev is on board for helping with ray tracing techniques. We'll meet soon to discuss.

**Comment by rvweeren** [comment]
Closed (for now) due to inactivity.
