### ISSUE TITLE
Bright sources on the edge of the calibrator region

### ISSUE THREAD

**Issue by mhardcastle** [lofar-astron/factor#51]
It's possible for a calibrator region to be chosen, centred on a bright source, which has another reasonably bright source just at its edge, leading to poor calibration solutions. The facet selection code needs to be able to do what we did manually and either recentre or resize the calibrator region in those cases.

**Comment by Joshuaalbert** [comment]
I wrote my own facet selector with uniformity constraints. I meant to submit the script. 
On 9 Apr 2016 10:22, Martin Hardcastle notifications@github.com wrote:It's possible for a calibrator region to be chosen, centred on a bright source, which has another reasonably bright source just at its edge, leading to poor calibration solutions. The facet selection code needs to be able to do what we did manually and either recentre or resize the calibrator region in those cases.

**Comment by twshimwell** [comment]
I dont suppose you can upload a few pictures of the calibrator regions and facet regions selected by the existing scripts in comparison to your ones Josh? I think the ability to automatically tweak the the facet sizes and centre to increase the number of sources and flux within the calibrator region is important.

**Comment by Joshuaalbert** [comment]
Here is a comparison of direction selection on my field, goods-north. Mainly, it tries to find a uniformly spread distribution with brightest sources separated the most, and orders them such that distant bright facets are first (they should be done sequentially in unit groupings) and then pair wise distant fainter sources next, so that parallel processing in groupings lead to decent results. My script uses pybdsm to extract sources with 100snr.

This one is created with my script.
![goods-n_myscript0](https://cloud.githubusercontent.com/assets/14807032/14458947/4326170a-00b5-11e6-9f7f-c59cce55c9aa.png)

This one is the default parset.
![goods-n_builtin_6sep](https://cloud.githubusercontent.com/assets/14807032/14462167/1b764638-00c6-11e6-827c-1192c883dab5.png)

This one is created using default but with 20arcmin max_seperation, 
![facets_builtin_20arcminsep](https://cloud.githubusercontent.com/assets/14807032/14459015/ba5c191e-00b5-11e6-87c2-34bddb87de84.png)

**Comment by rvweeren** [comment]
Interesting differences with Josh's method. The layout is more uniform indeed. Would be nice to do a full factor run comparison (i.e., with ~40 blocks, so it does not take forever), keeping everything the same, except the facet layout.

One could directly feed in these new facet positions to factor by updating factor_directions.txt.

**Comment by rvweeren** [comment]
Ah wait, this already seems to be a full blown comparison? As this shows the full mosaic. Josh can you put the fits images on the Leiden ftp server (or somewhere else) so we can have a closer look at the differences ?

**Comment by mhardcastle** [comment]
By the way this isn't what the original issue was about: I was talking about the issue where the region imaged for the calibrator isn't optimal, e.g. because it's too small to include a nearby bright source, which is mostly separable from the choice of calibrators in the first place. But I think something like Josh's suggestion would be useful as well for truly automated reduction.

**Comment by rvweeren** [comment]
Better split these issues (Josh could you open an issue "overall facet layout" and move your stuff there so we can keep track of things separately?)

I agree, that once the calibrators are determined it would be helpful to optimize the box-size and placement. If I look at the selfcal images I also often see nearby sources that with a little shifting/resizing of the calibrator boxes could be included to help the calibration. It think this should be done after the overall facet placement (to prevent things from getting too complicated, so  a "final calibrator box" optimization step.)

**Comment by mhardcastle** [comment]
Right, so I figured out what was going on in my dataset. The option flux_min_for_merging should have caused this bright source to be picked up. But because it was also resolved, it was ignored when the merging was done. The logic in make_directions_file_from_skymodel() is to drop all sources larger than size_max_arcmin and only pick sources to be merged from that filtered list. What we really want, I think, is to ensure that each field has flux_min_jy in compact sources but extended sources are still considered when merging is done. (Just making size_max_arcmin bigger solves the problem for this particular direction but also creates directions that just contain resolved sources in the calibration region, which is probably not desirable.) I don't think I am fluent enough in LSMtool to code this up myself without more thought, though.

**Comment by darafferty** [comment]
Ah, yes - that makes sense. I'm working on it now. Once the extended sources are merged properly, do you think we still need to shift/resize the calibrator boxes? I gave that some thought but didn't come up with a good way to do it yet.

**Comment by mhardcastle** [comment]
Well, in principle we could still get a situation where a relatively bright source (though still below flux_min_for_merging) lay in the border of the calibrator image where it wouldn't get imaged properly. My idea in that case was to do something iterative, like:

<pre>while any source is in border:
    include that source in merge-and-recentre-and-resize
    if facet gets too big, break # ie give up and hope for the best</pre>

which should catch all but pathological cases. But this would be fiddly to implement, I guess.

**Comment by darafferty** [comment]
OK - that should work. I'll have a go at it at some point soon.

Also, I've added the merging of extended sources. It will do the calibrator selection as before but at the end will add back any extended sources above flux_min_for_merging, merge them with calibrators within the given max separation, and lastly filter any extended sources that weren't merged. Martin, can you try it on your field and let me know if it still doesn't pick up that edge source?

**Comment by darafferty** [comment]
By the way, the updated merging is only on the reimage branch ATM.

**Comment by mhardcastle** [comment]
Great, I'll give it a go. Yes, I'm using the reimage branch at the moment,

**Comment by mhardcastle** [comment]
... that seems to solve the problem, yes.

**Comment by rvweeren** [comment]
Seems to be addressed (if not reopen)
