### ISSUE TITLE
union of masks and casapy regions files

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#53]
Do union of the masks and casapy region files both for facet imaging and for DDE selfcal imaging.

(easy in casapy just mask=['mask1],'region1'] )

**Comment by darafferty** [comment]
The merging of the masks (for selfcal and facet imaging for both casapy and wsclean) is now available on the reimage branch. Once it's been tested, I'll merge it into the master branch.

**Comment by rvweeren** [comment]
Confirmed this works. Closed.
