### ISSUE TITLE
mask missing in DDE selfcal images after image42_iter0 + panning large images

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#55]
1. A minor bug, the masks disappear after image42, see below
   (confirmed for multiple facets)

(strangely enough for another run (and different facet) I do not see the problem and the mask shows up correctly)
1. Some of these images are quite large and do not fit on my screen (because there are many selfcal iterations). So I need to scroll down/pan around/zoom. How can I do this ?

(to clarify the matplotlib window grows larger than my screen, it can be resized to some extent but I still miss images below row four)

<img width="406" alt="aplpy" src="https://cloud.githubusercontent.com/assets/3879473/14570273/7303c86a-0311-11e6-8030-bc4b962e9c65.png">

**Comment by rvweeren** [comment]
I think I figured out the reason for the disappearing mask. I used checkfactor on a older factor run and probably certain "products" were not created and hence the mask did not show up. With a fresh run of the latest factor the problem is not there so this is not a bug. Still have to check if the "large window" problem shows up, if it does I'll open a new issue for that one.

**Comment by darafferty** [comment]
Yes, earlier version did not make copies of all the masks so some are missing. As to the large window problem, I just encountered it myself. I've set a maximum size for the window now and added more columns, so hopefully this won't be a problem any more.
