### ISSUE TITLE
casa poly-type region

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#59]
Bit surprised why the casapy region file needs to be of type "POLY". Is this because of the wsclean masks ? Are you not doing a mask-region union with  rg.fromtextfile()  ? 

region = "mycasaregion.rgn"
imageout = "pybdsmcasa.mask" # input mask file from pybdsm, and output
ia.open(imageout)
myRGN = rg.fromtextfile(filename=region, shape=ia.shape(), csys=ia.coordsys().torecord())
im.regiontoimagemask(mask=imageout, region=myRGN)
ia.close()

As far as I know rg.fromtextfile supports all casapy regions files.
(for casapy imaging you do not need the above as you can just specify the mask "list", including regions)

I might be overlooking something though regarding the poly-type (if you use the regions in some other way as well) ?

**Comment by darafferty** [comment]
Yeah, the only reason is that I wanted to add the merging to the existing masking script rather than calling casapy to merge, so I wrote a simple parser to read the region file. Is there a way to import the casapy tools without calling casapy with a script?

**Comment by rvweeren** [comment]
Not sure, I remember Bas at some point managed to import some casa modules, but that was about 4(!) yrs ago. After some googling I came across this:

https://newton.cx/~peter/2014/02/casa-in-python-without-casapy/

(Bas probably did something along these lines)

BTW the poly region limitation is likely to surprise people as the old scripts did allow any casa region type, the most common type that I noticed people using is the "circle", and I've often seen people using multiple regions in a "combined" region file as well.

**Comment by astrofle** [comment]
Kasper van Dam (works with Huib) wrote a wrapper to the CASA toolkit: 
https://github.com/kaspervd/casanova

**Comment by darafferty** [comment]
It turned out to be fairly easy to just extend my parsing script to support box and ellipse type regions. I think that covers the region types that you can make in casaviewer. If not, let me know.

**Comment by rvweeren** [comment]
I think so.

Does it then also work with "composite" region files? Example below.

#CRTFv0 CASA Region Text Format version 0
ellipse [[23:44:35.71300, +000.27.21.3947], [67.4404arcsec, 60.4667arcsec], 90.00000000deg] coord=J2000, corr=[I], linewidth=1, linestyle=-, symsize=1, symthick=1, color=magenta, font="DejaVuSans", fontsize=11, fontstyle=normal, usetex=false
box [[23:43:52.76560, +000.16.16.2847], [23:43:34.47076, +000.20.36.7498]] coord=J2000, linewidth=1, linestyle=-, symsize=1, symthick=1, color=magenta, font="DejaVu Sans", fontsize=11, fontstyle=normal, usetex=false
poly [[23:44:10.75018, +000.11.55.8177], [23:43:41.60271, +000.06.58.1444], [23:43:34.78096, +000.11.32.5636], [23:44:28.42499, +000.16.11.6283]] coord=J2000, corr=[I], linewidth=1, linestyle=-, symsize=1, symthick=1, color=magenta, font="DejaVu Sans", fontsize=11, fontstyle=normal, usetex=false

**Comment by darafferty** [comment]
Yes, it should work with composite region files (as long as they have only poly, box, or ellipse regions).

**Comment by rvweeren** [comment]
Ok, as far as I can tell those are the only regions we use, so what you suggest should be ok and cater all our needs.

**Comment by rvweeren** [comment]
Tested for ellipse, box, polygon. All works.
