### ISSUE TITLE
peeling is not working (all branches)

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#61]
This is not related in specific to the reimage branch but a more general problem. It seems that the solutions it finds during peeling are wrong for some reason (I noticed it before but thought my 3C295 model was not very accurate but apparently the problem relates to the peeling solve).

I obtained very different solutions for 3C295 for these two cases:
1. just do the normal selfcal cycle for 3C295 (amplitudes are rather flat and around 1 and well behaved after the final solve). Save the best model after the last iteration. Convert to BBS format.
2. run from start again but now do a peeling step (instead of 1), provide the BBS model that was produced by 1. The gain and TEC solutions should look very similar (as one uses the same model and solves for the same parameters). Instead I get -very- different amplitude solutions for the long baselines. I also checked the TEC solutions, they are also different for the long baselines. Much more noisy in some cases and "incoherent trends" for some of the longer baselines.

It almost looks to me that factor does not use the BBS model provided by the user when peeling? Or solves in the wrong way? Maybe it does not clean the sourcdb's ? (because the selfcal cycle use FFTs and with the peeling you're using a skymodel). Or when peeling it solves out of a column ? Instead of the skymodel ?? Just mentioning some possibilities….

This is my skymodel (jus the first entries of the patch):

format = Name, Type, Patch, Ra, Dec, I, Q, U, V, MajorAxis, MinorAxis, Orientation, ReferenceFrequency='127243914.414262', Spe
ctralIndex='[]'

# CLEAN component list converted from: L343226_SBgr025-10_uv.dppp.pre-cal_chunk9_12656E813t_0g.casa_image42.model
# Mask: L343226_SBgr025-10_uv.dppp.pre-cal_chunk9_12656E813t_0g.casa_image42.mask
# Total flux in CLEAN components: 81.39 Jy
# Percentage of total flux kept: 100.00%

, , patch-0, 00:00:00, +90.00.00
patch-0-0, POINT, patch-0, 14:11:20.1856, +52.11.57.5640, 0.046246, 0.0, 0.0, 0.0 ,0.0,0.0,0.0, 127243914.414262, [-0.700000]
patch-0-1, POINT, patch-0, 14:11:21.0014, +52.11.59.0623, 0.122792, 0.0, 0.0, 0.0 ,0.0,0.0,0.0, 127243914.414262, [-0.700000]
patch-0-2, POINT, patch-0, 14:11:20.5119, +52.11.59.0634, 0.028959, 0.0, 0.0, 0.0 ,0.0,0.0,0.0, 127243914.414262, [-0.700000]
patch-0-3, POINT, patch-0, 14:11:21.1646, +52.12.00.5619, 0.045590, 0.0, 0.0, 0.0 ,0.0,0.0,0.0, 127243914.414262, [-0.700000]
patch-0-4, POINT, patch-0, 14:11:21.0015, +52.12.00.5623, 0.002479, 0.0, 0.0, 0.0 ,0.0,0.0,0.0, 127243914.414262, [-0.825913]
patch-0-5, POINT, patch-0, 14:11:20.8383, +52.12.00.5626, 0.004951, 0.0, 0.0, 0.0 ,0.0,0.0,0.0, 127243914.414262, [-0.825913]
patch-0-6, POINT, patch-0, 14:11:20.6751, +52.12.00.5630, 0.050923, 0.0, 0.0, 0.0 ,0.0,0.0,0.0, 127243914.414262, [-0.700000]
patch-0-7, POINT, patch-0, 14:11:20.5120, +52.12.00.5634, 0.004951, 0.0, 0.0, 0.0 ,0.0,0.0,0.0, 127243914.414262, [-0.825913]

**Comment by rvweeren** [comment]
These are the different amplitude solutions I obtain (case 1 first image, case 2 second image). They should be almost identical if the peeling works properly. The differences are huge, and the subtraction is very poor (not surprising given that the solutions are wrong in case 2)

![l343226_sbgr025-10_uv dppp pre-cal_chunk9_12656e813t_0g make_selfcal_plots_amp_channel0](https://cloud.githubusercontent.com/assets/3879473/14686026/11cd4006-0705-11e6-897b-f60a5044ef16.png)

![test](https://cloud.githubusercontent.com/assets/3879473/14686031/16e07fcc-0705-11e6-8915-d8e6cbe8ca70.png)

**Comment by darafferty** [comment]
Strange. The solve is pretty straightforward. It uses the following BBS parsets:
- [factor/parsets/facet_dirdep_phaseonly_solve_skymodel.parset](https://github.com/lofar-astron/factor/blob/master/factor/parsets/facet_dirdep_phaseonly_solve_skymodel.parset)
- [factor/parsets/facet_dirdep_phaseonly_apply.parset](https://github.com/lofar-astron/factor/blob/master/factor/parsets/facet_dirdep_phaseonly_apply.parset)
- [factor/parsets/facet_dirdep_amponly_solve_skymodel.parset](https://github.com/lofar-astron/factor/blob/master/factor/parsets/facet_dirdep_amponly_solve_skymodel.parset)

You can see the setting for other parameters (e.g., Solve.CellSize) in results/facetpeel/facet_patch_XX/pipeline.parset for the solve_ampphase11 (phase only) and solve_ampphase11 (slow gain) steps. They all look OK to me (doesn't mean they really are, of course). 

I wonder if the use of multiscale clean could be screwing up the model you made from the selfcal image? Maybe casapy2bbs doesn't handle the extended components correctly?

**Comment by rvweeren** [comment]
I doubt that, casapy2bbs does not know/care about multiscale since it just converts non-zero pixel values to a skymodel. I will modify the sky model (making it a point sources) and run again and see if the solutions differ. (I am starting to suspect that it ignores what is in the skymodel….)

**Comment by rvweeren** [comment]
I checked and at the solutions do change when I change the skymodel….very weird. That would point to me using the wrong model from the ".model.tt0/1" images. Or a significant discrepancy between BBS predict and casapy FFT predict.

Just to confirm the last/best model image created during a normal selfcal cycle is something called

L343226_SBgr025-10_uv.dppp.pre-cal_chunk9_12656E813t_0g.casa_image42.model.tt0/1 ? 

(it does seems to overwrite mage42.model.tt0/1 for each iteration ?)

**Comment by darafferty** [comment]
Yes, it overwrites all the image42 files (it just deletes L343226_SBgr025-10_uv.dppp.pre-cal_chunk9_12656E813t_0g.casa_image42.\* before running casapy), so the casa_image42.model.tt0/1 are the last ones created.

**Comment by rvweeren** [comment]
Ok, I'll will have to do more testing to find out what is going on.

**Comment by rvweeren** [comment]
I hacked the code to avoid multiscale clean and generated my best 3C295 skymodel after factor selfcal.

`~/scripts/facet-calibration/casapy2bbs.py L343226_SBgr025-10_uv.dppp.pre-cal_chunk9_12656E813t_0g.casa_image42.model 3C295testcc.skymodel`

Then I did a new factor run (providing precisely the same) data and the new 3C295testcc.skymodel and now set peel_flux_Jy to a low value to that factor attempts to peel the sources with that skymodel

The solutions look very -different- between these runs for the most distant RS stations. Based on this clean comparison it is very clear that there is major flaw somewhere in code (possible factor, but it could also be BBS or the script that converts model images to bbs format). This difference happens at the selfcal stage I am trying to isolate the cause. It possible that (1) not the same data is used to solve (different averaging for example, phase shifts), (2) the model predict is wrong for the BBS skymodel, (3) BBS solves for different parameters for example (or forgets to apply the tec), or (4) casapy2bbs is flawed.

I checked in detail and think we can exclude (3).  Also I doubt (1) is the case, because that should show up in the images that are made. So for now my preliminary conclusion is that the MODEL_DATA predict is different for the casapy FFT from an image, compared to the BBS predict from the skymodel.
Note that even the TEC solutions look different (see RS310 for example), and that would also point to a problem with the model predict. 

David: is there any difference in phase shifting or averaging when it tries to peel (at the solve stage) vs normal facet selfcalibration ?

Given that the main differences in the solutions are on the log baselines that must tell us something…(probably again points to an issue with the model predict or conversion from model image to bbs format skymodel)

Amplitude solutions from solve from .model image (casa fft)
![nopeelamp0](https://cloud.githubusercontent.com/assets/3879473/14943195/8cd29208-0fa0-11e6-915c-6069cc75af22.png)

Amplitude solutions from solve from 3C295testcc.skymodel 
![peelamp0](https://cloud.githubusercontent.com/assets/3879473/14943196/9471f3dc-0fa0-11e6-8fbd-25a463da953c.png)

TEC solutions  from .model image (casa fft)
![nopeeltec](https://cloud.githubusercontent.com/assets/3879473/14943212/bfbd6eea-0fa0-11e6-8173-4b4a7a1f8a53.png)

TEC solutions  from 3C295testcc.skymodel 
![peeltec](https://cloud.githubusercontent.com/assets/3879473/14943216/cc91b0ae-0fa0-11e6-9811-5b024f385456.png)

**Comment by rvweeren** [comment]
Amplitude difference between casa FFT and BBS model predict. (note the source is ~80 Jy, coloring is according "antenna1" in casaplotms)

<img width="475" alt="ampdiff" src="https://cloud.githubusercontent.com/assets/3879473/14943405/71e0fc86-0fa6-11e6-8f9a-9ebc032ee78c.png">

**Comment by rvweeren** [comment]
And this is how model data looks for reference (one of the two)

<img width="577" alt="amp" src="https://cloud.githubusercontent.com/assets/3879473/14943433/50998600-0fa7-11e6-8f39-ed54d5d9dfdc.png">

(so we have about a max of 1% difference in the amplitudes ….actually a bit more as the amplitudes drop with uvdistance)

**Comment by rvweeren** [comment]
Also checked the phases, difference are again small in the models. So the difference of about a factor of ~2 in the amplitude gain solution for the distant RS is hard to reconcile with the <~ 1% difference in the predicted model data. Hmm, that would argue that the casapy2bbs and the model predicts (both casa and bbs) are fine.

Totally puzzled. I'll try to solve against both these different sets of model data that should give more info.

**Comment by darafferty** [comment]
> David: is there any difference in phase shifting or averaging when it tries to peel (at the solve stage) vs normal facet selfcalibration ?

Ah -- I think you've hit on the problem! When comparing the peeling and selfcal parsets, I just realized that the peeling one, when used in the facetpeel operation (i.e., to peel a calibrator in a facet instead of an outlier source), will phase shift to the facet center, not to the calibrator position! (This isn't an issue with outliers, as these two positions are the same.) So the averaging must play havoc on the long baselines...

This error came about because I repurposed the outlierpeel parset for the facetpeel one but forgot to change the phase center. Should be fixed now (I'm testing it as well on my Groth strip field with 3C295).

**Comment by rvweeren** [comment]
Oh, that's easy to overlook and good that we catch this now! (these are the sorts of subtle errors that always worry me as they are very difficult to catch). I rerun and see if this fixes the problem.

**Comment by rvweeren** [comment]
Yes, this made the difference! Solutions look normal now, identical to the DDE selfcal ones. Took some time, but problem seems to be fixed. I'll close this after I confirm that the full facet images ok and the subtract worked.

**Comment by rvweeren** [comment]
Ok, works all the way to the end! The facet image looks **much** better now.  

I have one idea (to be tested) for further improvement to minimize "rounding/avg" errors for very strong sources: 

\1. Could we (optionally) obtain the peeling solutions on the full resolution data -without- phase shifting/avg ? (Would that be difficult ? Or does that create all kind of bookkeeping problems?)
\2. Directly subtract the source from the full res data with these solutions

(we then have zero difference between the data and the gain solutions during solve and subtract, which is optimal to obtain high dynamic range)

\3. then add back rest field, phase shift and apply the solutions for the facet imaging, etc, i.e., proceed as normal.

**Comment by darafferty** [comment]
Great! My test run is still going, but I'm looking forward to getting some good results... 

It shouldn't be hard to implement the strategy above, and I guess if we can use DPPP gaincal it would be fast, too.

**Comment by rvweeren** [comment]
BTW This is the difference between peeling my "own" model (_left_), made with factor during DDE selfcal, (_right_, and then converted to a BBS skymodel) and the two component model (_middle_, which we use in prefactor). 

All three images are "full2-MFS.fits"

<img width="868" alt="diff2two" src="https://cloud.githubusercontent.com/assets/3879473/14964977/bf083740-1078-11e6-96ff-d4fb6e78e1fe.png">

Note, all peeling images are after today's bug fix (before the fix things looked much worse compared to these images).

So for very  bright sources in the field (~10-20+Jy), it is worth first to have factor have a go a it. Then convert the best .model.tt0 image from factor to BBS format and the turn on the peeling with the new model. This produces better images than during DDE selfcal as you avoid much of the wsclean deconvolution and aliasing problems that you would encounter in DDE selfcal for such a bright sources.

So, if you're trying to peel 3C295 you need to feed something better than the two component model from prefactor (it's simply not sufficiently detailed). 

I've my model attached if you want to try it (it should not be used in prefactor because the flux-scale is probably not fully accurate, i.e., it does not contain the Saife & Heald spectral coefficients) but for peeling purposes this it should work much better than the prefactor model (this model was only made from 2 blocks at 120 MHz, so it can likely be improved further). 

[3C295testcc.skymodel.gz](https://github.com/lofar-astron/factor/files/245753/3C295testcc.skymodel.gz)

**Comment by darafferty** [comment]
Very nice! My run on 3C295 (with the prefactor model) is still going (it takes forever on our nodes for some reason); once it finishes I will try your model. I went ahead and added it to factor/skymodels and renamed the prefactor one so that only the new one will be used.

**Comment by rvweeren** [comment]
Related to building a model with factor. It is possible to have switch disabling the multiscale clean in the casa image in the DDE selfcal? (so force multiscale=[0]). At the moment multiscale is always enabled and I have the problem with these Gaussians components unnecessarily increasing the number of clean components. (I manually hacked factor to force multiscale=[0] but it would be easier to have a switch to force this without having to go into the source code each time).

**Comment by darafferty** [comment]
I've added an option called "selfcal_scales" under [imaging] that allows one to specify the scales. Set it to "[0]" to disable multi scale clean.

**Comment by rvweeren** [comment]
Perfect, that's quite useful for other reasons as well.
