### ISSUE TITLE
Facets should be chosen with uniformity of coverage in mind

### ISSUE THREAD

**Issue by mhardcastle** [lofar-astron/factor#63]
Placeholder issue for the discussion on this point that took place in issue #51 (which is about something else).

Josh mentioned some code for doing this: I would be happy to test on my field (which has a rather asymmetric distribution of bright sources) with a view to eventually incorporating it in factor as an option.

**Comment by Joshuaalbert** [comment]
Thanks for opening this issue. I've been meaning to. I can send you the code tomorrow. It takes the high2 images and produces a directions file which the factor takes and tesselates. 
Is there an issue already about the incorperation of all subbands to make deeper images to avoid faint and/or steep sources?
On 20 Apr 2016 22:03, Martin Hardcastle notifications@github.com wrote:Placeholder issue for the discussion on this point that took place in issue #51 (which is about something else).

Josh mentioned some code for doing this: I would be happy to test on my field (which has a rather asymmetric distribution of bright sources) with a view to eventually incorporating it in factor as an option.

**Comment by twshimwell** [comment]
yeh the deep image issue is https://github.com/lofar-astron/prefactor/issues/7

**Comment by mhardcastle** [comment]
Josh, if you can get the code to me today that would be great as I have some time to work on this over the coming few days.

**Comment by Joshuaalbert** [comment]
Sorry, forgot to send it yet. I'll just pack it up nicer and send to 
you.

**Comment by Joshuaalbert** [comment]
Martin, I'll have to send it tomorrow. I was cleaning up the code, but 
haven't finished yet. However, I have to do another few things before 
sleeping. Tomorrow it's on my todo list.

Josh

**Comment by mhardcastle** [comment]
No worries, I'll be working on this stuff again next week.

**Comment by Joshuaalbert** [comment]
Hi Martin,

I have a facet selector that incorporates uniformity, and tries to order 
things appropriately. Sorry it took a while but I've at least taken the 
time to prove mathematically that this is the most uniform selection. 
Ordering is in decreasing background rms. Where should I send it?

Cheers,
Josh

**Comment by Joshuaalbert** [comment]
I will upload the script to my own github and then it can be grabbed and integrated by whomever is qualified.

**Comment by mhardcastle** [comment]
Hi Josh,

yes, that would work well. We were just talking about how to integrate helper scripts like this one into factor at yesterday's telecon. Can you post a link to the repository here when you have uploaded it?

Cheers

Martin

**Comment by Joshuaalbert** [comment]
Hi Martin,

Very good, here is the repo: 
https://github.com/Joshuaalbert/RadioAstronomyThings

**Comment by Joshuaalbert** [comment]
Hi, I don't seem to have commit and push privileges to the factor repo so I forked factor and modified the directions.py file as given here:
https://github.com/Joshuaalbert/factor/blob/patch-1/factor/directions.py

**Comment by tammojan** [comment]
The github-way is then to make a pull request from there to here; then someone with push access can just press a green button to merge it.

**Comment by Joshuaalbert** [comment]
okay sounds good, let me know which branch you merge it to :)

**Comment by darafferty** [comment]
Thanks, Josh. I made the pull request myself and merged your changes into the master branch. I'm quite interested to try it out!

**Comment by darafferty** [comment]
I've now added an option ("minimize_nonuniformity" under [directions]) that can be used to enable Josh's version.

**Comment by rvweeren** [comment]
Josh's version is implemented so this can be closed.
