### ISSUE TITLE
small holes self calibration and facet maps

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/factor#65]
In my new factor run of a facet I get some artefacts I have not seen before. Attached is a plot with three images. The bottom left is from a factor run on the 12th April (using the up to date version at that time). The top left and top right are from a run from the 21st April (using the up to date version at that time) where the left is the clean image and the right is the dirty image. As you can see the runs from the 21st April have very odd little holes in the emission from extended sources... 

![weird-wsclean-clean](https://cloud.githubusercontent.com/assets/12065270/14739068/8ef31890-0885-11e6-94c2-46376534efa0.png)

**Comment by darafferty** [comment]
Hmm.  I wonder if these could be aliasing artifacts? It was during that period that we increased the image and model padding and decreased `-nwlayers-for-size`. Which version of WSClean are you using?

**Comment by twshimwell** [comment]
Yeh I wondered if it could somehow be related to the aliasing changes. I am using version wsclean v1.11.

**Comment by darafferty** [comment]
Ah, sorry - I just noticed that you gave the version in the title. Is this the first facet in the reduction or have others been processed before this one?

**Comment by twshimwell** [comment]
This is the first facet.

**Comment by rvweeren** [comment]
Then -nwlayers-for-size should not matter (as it has never run the FFT subtract before for another facet). So -nwlayers-for-size  cannot be related to this.

( -nwlayers-for-size is only used in the WSClean FFT subtract)

**Comment by rvweeren** [comment]
Do you see these holes in the DDE selfcal images made with casa (presuming you selfcalirbated on this source) ?

**Comment by twshimwell** [comment]
The source for the self calibration is a different one but yeh I do also see such features in the image of the calibrator region (shown below with left being the newer factor and right being the older factor). The little holes in the calibrator map are also there in the facet map at the same position.

<img width="714" alt="screen shot 2016-04-23 at 9 27 48 am" src="https://cloud.githubusercontent.com/assets/12065270/14759955/b211456c-0935-11e6-8132-f03c3b6d94f4.png">

**Comment by twshimwell** [comment]
(they seem to be present throughout the self calibration cycle although its a little hard to tell in the 02 image as the artefacts dominate)

**Comment by rvweeren** [comment]
If they are present in the selfcal images then it cannot be a wsclean issue….

**Comment by twshimwell** [comment]
hmm yeh it cant be. I wonder if it could be that for some reason clean components that were subtracted have not been added back.

**Comment by darafferty** [comment]
Did you rerun with a new working directory? If not, maybe the previous run has subtracted an improved model but the new run is not aware of this (because the state got confused somehow)?

**Comment by twshimwell** [comment]
Hmm im not sure what is happening. I have just done a completely fresh run using the reimage branch. There were no restarts of the pipeline so this is just factor taking the subtracted products through facet calibration. Again I see these little holes in the map self calibration map (and I expect the facet map when it is finished).

**Comment by adrabent** [comment]
I see also negative holes or bowls.
It looks like that in the self-calibration cycle it might have not been cleaned deeply enough.

The mask is more or less set properly. I'm using the reimage branch.
![negative_bowl](https://cloud.githubusercontent.com/assets/19146990/14951264/415163e8-1047-11e6-9ce7-906c4670b32a.png)

**Comment by twshimwell** [comment]
Hey Alexander, your bowls around the source look a little different from the ones I was seeing. Yours look like cleaning residuals (yeh it is perhaps not deep enough cleaning here -- the full2 image I think cleans deeper so by comparing the two you could see if that residuals are indeed due to cleaning depth) but the ones I was seeing don't look like cleaning issues.

**Comment by adrabent** [comment]
Hi Tim, thanks for the comment.
In the full2 image it looks even worse. I already put selfcal_clean_threshold = True.
We should then maybe move this issue to another section.

**Comment by darafferty** [comment]
Tim, it seems that the holes in your first image are uniformly spaced -- almost on a grid. Furthermore, judging by eye, they seem to be spaced about 25" apart, which is the cell size of the low-resolution image from the initial subtraction. Can you check your sky models for this facet and see if any low-res components are in there? Maybe they got removed somehow?

**Comment by twshimwell** [comment]
It could be the case that the lowres ones are not getting adding back in perhaps. Here is a few of these holes in the self calibration image together with the _low2_model*fits made in the subtraction.

<img width="823" alt="screen shot 2016-05-02 at 3 10 59 pm" src="https://cloud.githubusercontent.com/assets/12065270/14955165/4a1f09ea-1078-11e6-880e-b107536f8009.png">

**Comment by twshimwell** [comment]
And here is one of the images from the facet image which shows some holes (the full mfs image is nearly ready) together with the low2 model image where this time the colour scale lets you see the strength of the clean components 

<img width="819" alt="screen shot 2016-05-02 at 3 21 15 pm" src="https://cloud.githubusercontent.com/assets/12065270/14955354/b01fca8a-1079-11e6-81fa-fa576f448d8e.png">

It seems to me that the locations of the holes match very well the locations of the clean components. However, in this case the hole on the right and left have approximately similar sizes but the clean components corresponding to the hole on the right are much larger.

**Comment by darafferty** [comment]
Strange, it does appear that some low-res components are missing from the facet sky model that's added back. The facet sky models should be filtered only on position -- not by name or flux, etc. If you look at the contents of one of the facet sky models (named something like L158196_SB035_uv.dppp.wsclean_low2-model.make_facet_skymodels_all in the facetselfcal/facet_patch_XXX directory), do you see any components with "_1" in the names? I think these are the low-res model components. If not, can you also check for these in one of the full skymodels (the ones given as input to Factor in the parset)?

**Comment by twshimwell** [comment]
Yeh, I'm just looking at them in a bit more detail. It seems to be related to the low res clean components after all (my previous posts an hr ago are a bit misleading). If I look at the same freq band I see a good correlation between holes and low res components.

<img width="1352" alt="screen shot 2016-05-02 at 4 22 28 pm" src="https://cloud.githubusercontent.com/assets/12065270/14956844/1baf33f0-1082-11e6-9b96-e03daa8e62ec.png">

**Comment by rvweeren** [comment]
I've also seen some weird holes (I first thought aliasing artifacts, but they look more like holes, although I not fully sure it related to the same issue). They could also be clean components not being added back. BTW It is very important that if there are clean component placed on artifacts near bright sources that these are **all** added back before DDE selfcal as otherwise the calibration cannot correct them (so the calibrator source size region/image needs to be large enough to encompass all _artifact clean components_).

**Comment by twshimwell** [comment]
In those files I do see ones called component_XXX_1 and also componenet_2.

Here is another example showing excellent correspondence between the low res components and the holes.

<img width="820" alt="screen shot 2016-05-02 at 4 34 36 pm" src="https://cloud.githubusercontent.com/assets/12065270/14957124/d52c4fba-1083-11e6-952d-5f2870451588.png">

**Comment by darafferty** [comment]
So there are low-res components in the sky models I guess (and they must have been added back with all the others). Can you check whether some of the specific components that match the holes are in the facet sky models?

**Comment by twshimwell** [comment]
I have checked the factor files called _low2_facet_smkymodels_all\* and the low resolution clean components that appear to correspond to the positions of holes are indeed present in these files and they have names like component-???_1

**Comment by twshimwell** [comment]
Is it possible that the names of the sources get too long in the files containing the sources and then they get missed? I remember an issue like this before when we were trying to use the manual facet calibration scripts together with factor scripts.

**Comment by eretana** [comment]
Hello. This hole issue was also present in the old facet-cal scripts as well. I saw them around the facet calibrators. 

![hole1](https://cloud.githubusercontent.com/assets/17938191/14976316/d3900f52-110a-11e6-8896-7c3031fa20f0.png)
![hole2](https://cloud.githubusercontent.com/assets/17938191/14976317/d392c1c0-110a-11e6-8f4e-8f1184adafbf.png)

**Comment by mhardcastle** [comment]
These are simply residual amplitude artefacts. There are a number of effects that can produce negative holes in radio maps -- we're focussing here on the ones specific to Factor...

**Comment by eretana** [comment]
Yes. I'm aware that the focus here is Factor. I just wanted to point I where saw these holes before.

**Comment by twshimwell** [comment]
I did a test where I reduced the length of the source names in the input sky models (just changing component to comp) but that wasn't the cause.

**Comment by darafferty** [comment]
Could the low-res components have been subtracted twice somehow? I've no idea how this could happen, but it would explain things, I suppose.

I've looked through the changes between April 12 and 21, but I don't see anything that could cause this issue. One thing you could do is revert back to the April 12th version and try it again (with "`git checkout 087f9b967f8828f1438b7703aa2741017d3809f4 .`"), to see whether it is something with the data or not.

**Comment by twshimwell** [comment]
OK, ill have a go with that and let you know.

**Comment by twshimwell** [comment]
Hmm I think I managed to get revert to the older version of factor (github continues to confuse me but if I do git branch now it says I have "(HEAD detached at 087f9b9)"). I still have the little holes which also confuses me as I didn't have them before April 12th.

Assuming I have managed to revert to the old github version of factor I wonder if somehow the data I put into factor has changed (I cant think how it would have changed). I will try starting from before the subtract on a group of subbands to see.

**Comment by twshimwell** [comment]
I redid the source subtraction and ran factor again using the April 12th version. This time I could not see the holes in the image... No idea how this happened but this suggests that the measurement sets I was putting into factor were somehow a little messed up but factor is fine.
