### ISSUE TITLE
wsclean imaging does not use facet_robust?

### ISSUE THREAD

**Issue by mhardcastle** [lofar-astron/factor#66]
I am using the reimage branch and have in my parset:

[imaging]
make_mosaic = True
facet_imager = wsclean 
facet_robust = [-0.5]

But the wsclean imaging of the facets is being done with a robust of -0.25, the default value of selfcal_robust. I want -0.5 for comparison with my earlier runs. Before I dig into the code, am I actually correct that this is a bug, or am I doing something wrong?

**Comment by darafferty** [comment]
Yeah, I guess it's a bit confusing. The facet options are used only during reimaging.  So the facet imaging during facetselfcal uses the same parameters as the selfcal imaging.  To change the facet imaging, you need to set reimage_selfcaled=True under [imaging] and wait for the facet to be reimaged. 

However, I remember now that the wsclean robust is a bit different than the casa one (-0.5 -> -0.25?), so I guess it would be good to be able to specify it separately from the selfcal one. Do you think we allow the user to set the taper and cell size separately as well? Seems a bit dangerous (one could end up subtracting a low-resolution model, for example).

**Comment by rvweeren** [comment]
Yes, wsclean follows the "AIPS standard" if I am correct. Casa robust = 0.0  equals wsclean robust=-0.5

**Comment by mhardcastle** [comment]
Oh I see, I thought that was possible. reimage_selfcaled is True by default now, isn't it? So I should eventually get a robust -0.5 version?

Yes, it would be better to use -0.5 as standard. Somehow that's changed between my previous run and this one with the reimage branch.

**Comment by mhardcastle** [comment]
(I don't think we want the user to be able to set taper and cell size for the facet imaging; possible that it's worth exposing the robustness, but with -0.5 as the default.)

**Comment by darafferty** [comment]
Yes, reimage_selfcaled is on by default, so it should produce the robust -0.5 image. 

I will add the wsclean robust option. It should make things clearer even if it's not used much.

**Comment by darafferty** [comment]
I added an option for this as "selfcal_robust_wsclean" under [imaging](default is -0.5).

**Comment by mhardcastle** [comment]
Thanks, I will test and report back next time I restart.

**Comment by mhardcastle** [comment]
Problem solved!
