### ISSUE TITLE
make_selfcal_images hangs

### ISSUE THREAD

**Issue by wndywllms** [lofar-astron/factor#67]
make_selfcal_images in the facetselfcal step consistently hangs

It seems to be because I'm using matplotlib 1.5 and the aplypy calls produce a lot of warnings:
"This has been deprecated in mpl 1.5, please use the
axes property.  A removal date has not been set."

Suppressing the warnings in make_selfcal_images.py allows the pipeline to run without hanging.
import warnings
warnings.filterwarnings("ignore")

Perhaps this is more of a pipeline bug because the script runs successfully.

Also, in debugging this, I noticed that the 
`if __name__ == '__main__'`
section is wrong (copied from make_facet_skymodel.py I guess). Not a problem for factor, but it means you can't run it independently.

**Comment by rvweeren** [comment]
Good to know. I am still using mpl 1.3.1 (the Ubuntu 14.04 default) but was thinking to upgrade to mpl 1.5.1. What aplypy version do you use?

**Comment by wndywllms** [comment]
aplpy v1.0

**Comment by darafferty** [comment]
Yeah, this is a known bug in the pipeline, but it can't easily be fixed so we just have to work around it (by suppressing or redirecting output as above). I'll fix the script.
