### ISSUE TITLE
masking thresholds changed in reimage branch?

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#68]
Noticed that the masking (using standard options, no region files, etc.) is performing rather poorly in the reimage branch (misses bright parts of sources). Attached just one example. Did something change here with respect to the master branch related to thresholds? (in particular images 12/22 often have incomplete masks, almost looks like the threshold is set too conservatively)

(cannot exclude a few cases of bad luck, but overall it seems the thresholds are not well tuned well for my dataset)

<img width="306" alt="mask" src="https://cloud.githubusercontent.com/assets/3879473/14833953/bfef70c2-0bcf-11e6-9135-0a498e8a671d.png">

**Comment by rvweeren** [comment]
Could also be that the default thresholds are poorly tuned and that only shows up now (because we made these aplpy images now where the mask is always shown). Going back to older runs I see that often the masking is too conservative and misses too much of the source structure. (did not spot that at that time because you have to dig inside the directories to find the masks and doing that for every facet was too cumbersome).

**Comment by rvweeren** [comment]
After processing 6 directions I see problems with 5 directions for the masking. It is always seems too conservative in particular for somewhat (few beams) extended calibrator sources.

**Comment by mhardcastle** [comment]
Yes, I agree (also in reimage branch).

In my case it's made more obvious by the changes I asked for to get extended sources into the calibrator field. Attached an example around 3C303: in this case there are clear short-baseline artefacts in the final image.
[calimage.pdf](https://github.com/lofar-astron/factor/files/238047/calimage.pdf)

**Comment by darafferty** [comment]
Yeah, the reimage and master branches use the same thresholds, which are also the same as those used in the [selfcalv19 script](https://github.com/tammojan/facet-calibration/blob/master/selfcalv19_ww_cep3.py). The progression is (threshpix, threshisl):
- 02: 10, 6
- 12: 15, 15
- 22: 15, 15
- 32: 10, 10
- 42: 10, 10

So indeed the 12 and 22 images have higher thresholds.

**Comment by rvweeren** [comment]
Ah I remember I was playing with these settings. In my selfcal20.py (which is the "best" version I had) and which I used for my A2256 reduction I have:

02: 10, 6
12: 8, 7
22: 8, 7
32: 10, 10 
42: 8, 8

That fully explains why in 12/22 images in particular the mask was missing so much. Can you update the code to these values? I believe these values are definitely better.

**Comment by darafferty** [comment]
Done (reimage branch only -- I intend to merge this branch into the master one soon).

**Comment by rvweeren** [comment]
Testing it now. Should be able to confirm tomorrow whether resolves the issue.

**Comment by rvweeren** [comment]
Looks better now.

**Comment by adrabent** [comment]
I also tested the new settings.
But when starting from low resolution the masking is not conservative enough anymore.
It starts to pick up the artifacts:

![new_pybdsm_settings](https://cloud.githubusercontent.com/assets/19146990/14950940/15778484-1045-11e6-9eaa-ffead8677df9.png)

**Comment by twshimwell** [comment]
Eeek. That doesnt look good. The masking for the 02 image seems the same in both the new parameters and the old parameters though so this must always have been an issue here I guess. 

Perhaps we need different masking parameters for the 02 and 12 images when doing the low-to-high resolution self calibration from when just doing the full resolution self calibration.

**Comment by darafferty** [comment]
Yeah, it went wrong at the 02 image, I suspect because atrous_do was activated in the masking (it doesn't look like the wavelet module is needed here, but maybe atrous_do should never be used for image02?). Alexander, can you try running it again with atrous_do in the factor_directions.txt file set to False for this calibrator? If that fixes it, I will have a look at tuning the automatic activation of this setting.

**Comment by adrabent** [comment]
I've restarted the facet with atrous_do = False. It has not finished yet, but I looks like that it doesn't work: 
![new_pybdsm_settings_2](https://cloud.githubusercontent.com/assets/19146990/14967037/efc7e35e-10a4-11e6-8499-b2a849b8e544.png)

**Comment by rvweeren** [comment]
But it looks a bit better at least, let it continue for now. Judge the **final** iteration, at intermediate stages things do not have to optimal yet.

**Comment by adrabent** [comment]
This is the current status:

![new_pybdsm_settings_3](https://cloud.githubusercontent.com/assets/19146990/14977136/ee46e80a-1111-11e6-8587-66ff3d43aa8c.png)

It doesn't seem to converge at all. From the 42 image it is clearly visible that it cleaned an artifact. The noise of the calibrator field is twice as high as usual. Typically a level of 150muJy is reached.

**Comment by darafferty** [comment]
Did it stop after image42_iter0 or is it still going? 

By the way, I fixed the problem with overplotting of the 42 images on top of the second row of 22 images. I also changed the way Factor sets atrous_do, so hopefully it should not turn it on in this case now.

**Comment by adrabent** [comment]
It stopped there, but the calibration looks quite bad.
Shall I rerun the facet with default settings again?

**Comment by rvweeren** [comment]
Hmm yes. It might very well be there is no unique set of thresholds (as one observation has stronger artifacts than another one). That would be rather unfortunate as it complicates fully automatic runs. For now we could make these masking thresholds adjustable by the user (maybe via a single scaling factor?). David what do you think ? (ideally we should handle this automatically but not sure how difficult it will be to get this intelligence in, does not seem trivial to me)

**Comment by darafferty** [comment]
Yeah, a user-adjustable scaling factor seems reasonable. As you say, it would be ideal to add some intelligence (e.g., masks should typically have smooth edges, so if you find a jagged one like Alexander's image12 mask then increase the thresholds), but it would likely be quite difficult to implement.

**Comment by rvweeren** [comment]
The failure of the masking is essentially a PyBDSM issue, as apparently PyBDSM thinks this island is real…. 

David: I have an "idea" we could try to address some of this. Looking at the negative values around the sources should give a good handle on what to trust and what not. If you multiply the image by -1\* then you could play the game of adjusting the thresholds such that none of the "negative" (now positive) stuff is picked up in the island. You could then use these thresholds on the normal image. The idea is that for calibration artifacts the positive artifacts have the same magnitude as the negative ones… (positive artifacts are easily confused with source structure BUT we could use the information given by the negative artifacts). Obviously this needs testing, experimenting…just an idea.

(My selfcal thresholding  is also based on looking at negative residuals….it's quite a powerful way to determine how good the calibration is as you can avoid source emission)

Alex: could you run PyBDSM on this image ("manually") and play with the settings and see why it picks up the artifacts in the island mask and how to change the settings so that it avoids it ? (would be good to share this image as a test case…)

**Comment by darafferty** [comment]
Interesting idea! For starters, I could try some experiments outside of PyBDSM and then think about how to implement this inside it (an adaptive threshold might be hard to interpret when doing cataloging, but maybe one could instead adjust the local noise to achieve the same result).

**Comment by adrabent** [comment]
I restarted the facet again, and now atrous_do is False and I achieve the same results as in the plots I showed before.
I did the pybdsm test for the lowest resolution image first (image01)
Standard factor with atrous_do = T
##############################
![atrous_do_true](https://cloud.githubusercontent.com/assets/19146990/15008759/ce85cdfc-11e2-11e6-9cd1-2f73ca28a03a.png)
tresh_isl = 8, tresh_pix = 12: 
![atrous_do_true_8_12](https://cloud.githubusercontent.com/assets/19146990/15008772/e07890a8-11e2-11e6-82ba-07451ac216d9.png)
tresh_isl = 10, tresh_pix = 14: 
![atrous_do_true_10_14](https://cloud.githubusercontent.com/assets/19146990/15008778/e91612b2-11e2-11e6-91b4-505b236b8533.png)

Standard factor with atrous_do = F
##############################
![atrous_do_false](https://cloud.githubusercontent.com/assets/19146990/15008783/f4010cfe-11e2-11e6-8aca-1658d6a2f745.png)
tresh_isl = 8, tresh_pix = 12: 
![atrous_do_false_8_12](https://cloud.githubusercontent.com/assets/19146990/15008792/ff353b40-11e2-11e6-9836-ae152d36f55b.png)
tresh_isl = 10, tresh_pix = 14:
![atrous_do_false_10_14](https://cloud.githubusercontent.com/assets/19146990/15008796/07467376-11e3-11e6-91f8-e0fabcabf286.png)

At least at this stage atrous_do = T is not the limiting factor, to me it seems that the tresholds just need to be set slightly more conservative...

The runs of the high-resolution image are ongoing ...

**Comment by adrabent** [comment]
Run for the medium resolution: image11
Standard factor with atrous_do = F
##############################
![image1_atrous_do_false](https://cloud.githubusercontent.com/assets/19146990/15009375/5202e496-11e6-11e6-9918-2be1f270105c.png)
... but I can set the treshold unreasonably high until tresh_isl=20 and thresh_pix=21 it will always pick up the artifacts 
![image1_atrous_do_false_20_21](https://cloud.githubusercontent.com/assets/19146990/15009460/c42c0eb2-11e6-11e6-9251-2a7fb8ebff58.png)

The same for the high-resolution image22:
Standard factor with atrous_do = F and tresh_isl=20 and thresh_pix=21
##############################
![atrous_do_false_20_21](https://cloud.githubusercontent.com/assets/19146990/15009420/8b670744-11e6-11e6-9212-ae9945532bfd.png)

But I believe that this comparison is not really fair, since the data is not properly calibrated at the stages of image11 or even image21, since the artifacts reach a quite strong "flux" level ...

**Comment by darafferty** [comment]
Alex, can you make image01 and image11 available somewhere (or send them to me)? I'd like to test Reinout's idea on them.

**Comment by darafferty** [comment]
I've added an experimental option ("selfcal_adaptive_threshold" under [imaging]) that will try to adjust thresh_isl so that it is 3 sigma above the maximum negative value. Alex, can you give it a try on your facet? (My tests on your image01 and image11 suggest that it should work a lot better, but I'm not sure if it will also work as well on the later selfcal images.)

**Comment by darafferty** [comment]
BTW, the above option is only on the reimage branch for now.

**Comment by adrabent** [comment]
The new option does a rather good job:
![new_pybdsm_settings](https://cloud.githubusercontent.com/assets/19146990/15038895/9f03aad0-1297-11e6-8157-c89a8545c910.png)

Still the reached noise level is rather high, but at least it was not cleaning at the artifacts.

**Comment by darafferty** [comment]
Great! I've tried the new option on a few sources too, and it's worked very well.

**Comment by rvweeren** [comment]
For me it also worked quite well.

**Comment by rvweeren** [comment]
We need a bit more testing, but it looks to me we want to make selfcal_adaptive_threshold = True by default.

**Comment by darafferty** [comment]
I agree -- so far I've had no problems with it.

**Comment by adrabent** [comment]
I now have one example, where it seems to not pick up a quite bright double-source close to the calibrator at the very beginning, but starts to pick it up later (slowly).

![calibrator_field_372](https://cloud.githubusercontent.com/assets/19146990/15140780/fff13e94-169c-11e6-93ff-0c6cb7bbb21f.png)

In principle, it seems to "converge" somehow.

**Comment by rvweeren** [comment]
Interesting case, could you provide David with these images ? (David: Any idea why the rms_box does not take care of this ?)

**Comment by darafferty** [comment]
Hmm. Likely the adaptive threshold scaling needs to be adjusted a bit. So, do please send me the images (the first three in the sequence are probably enough).

**Comment by darafferty** [comment]
OK, I lowered the threshold a bit -- it was too conservative before. Alex, can you try it again on the facet above?
