### ISSUE TITLE
Configurability of checkfactor

### ISSUE THREAD

**Issue by mhardcastle** [lofar-astron/factor#69]
It's useful (to me at least and perhaps to others) to be able to use FITS and image viewers other than the built-in default in checkfactor. I've added some parset-defined options to the code in the reimage branch that implement this. For example, in my parset I now have:

[checkfactor]

facet_viewer=ds9
ds9_load_regions=True
ds9_limits=0 0.1
image_display=eog

which specifies that the fits image viewer for facets is ds9, that the facet region file should be loaded, that the limits should be set to 0 and 0.1 Jy, and that pngs should be viewed with the eog command. The defaults are unchanged so if you don't have a checkfactor section in your parset everything stays as it is. Note that the ds9_... options rely on pyds9 being installed -- if you don't have it then a new ds9 will be spawned with the FITS image but the other parts won't work. If you do have pyds9 then checkfactor will re-use a previously opened ds9.

Opening this issue to let people know about the changes and to collect bug reports / enhancement requests. I believe the necessary changes to parset.py shouldn't affect the running of factor itself.

**Comment by darafferty** [comment]
Great! I prefer ds9 as well (but casaviewer was so much easier to implement!).

**Comment by mhardcastle** [comment]
I guess everyone's happy with this, closing.
