### ISSUE TITLE
standard settings in factor parset

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/factor#71]
Perhaps not so much an "issue" but it would be good to have standard settings for a factor parset which we think its going to produce the best results for a normal field. To start a discussion on this below is one possible setup (using the options available in the reimage branch).

```
[global]
# keep_avg_facet_data = False
# keep_unavg_facet_data = False
# exit_on_selfcal_failure = True
# skip_selfcal_check = False
# max_selfcal_loops = 10
# preaverage_flux_Jy = 0.0
# multiscale_selfcal = True
# TEC_block_MHz = 10
# peel_flux_Jy = 100.0 
# solve_min_uv_lambda = 80.0
# spline_smooth2D = True
# solve_all_correlations_flux_Jy = 5.0

[imaging]
# make_mosaic = True
# reimage_selfcaled = True
# wsclean_image_padding = 1.6
# wsclean_model_padding = 1.4
# max_peak_smearing = 0.05
# facet_imager = wsclean (is casa really faster for large bandwidths? If so then thats prob better)
# wsclean_nbands = 2
# selfcal_cellsize_arcsec = 1.5
# selfcal_robust = -0.5
# selfcal_robust_wsclean = -0.5
# selfcal_min_uv_lambda = 80.0
# facet_cellsize_arcsec = [1.5]
# facet_robust = [-0.5]
# facet_taper_arcsec = [0.0]
# facet_min_uv_lambda = [80.0]
# selfcal_clean_threshold = True

[directions]
# max_radius_deg = 5.0
# flux_min_for_merging_Jy = 0.1
size_max_arcmin = 2.0
separation_max_arcmin = 7.0
flux_min_Jy = 0.3
# ndir_max = 25
# ndir_process = all
# ndir_selfcal = all
# faceting_radius_deg = 2.5
# check_edges = True
# transfer_radius_deg = 0
# groupings = 1:0
```

**Comment by darafferty** [comment]
I think `peel_flux_Jy` should be lower (this the the flux of the calibrator in the highest-frequency band, so 100 Jy would mean 3C295 would not be peeled, for example). 

Also, is 25 facets really enough for a typical observation?

**Comment by mhardcastle** [comment]
I have flux_min_Jy=0.35, flux_min_for_merging=0.1 (which however may be the default), size_max_arcmin=0.8, separation_max_arcmin=9.0, ndir_max = 40.

It might be good to try to converge on some settings for a low-resolution re-imaging:  taper to 20 arcsec and image with 5-arcsec pixels with robust 0?

**Comment by twshimwell** [comment]
For the low resolution imaging at say 20". I was thinking of having a much more negative robust parameter, like -1.0 or -1.5, as the sidelobes get really very high.

With the peel_flux_Jy option, I guess if factor doesnt have a model for these peel sources it stops? If so then I wonder whether factor needs a database of models with sources where the peeling will be done because otherwise people may not know where to get their models from (this could just be TGSS for now and we could update it as we go through).

With regards to the number of facets I'm not really sure. I guess 25 may be on the short side, I think Wendy used 28 for Bootes (which had a good ionosphere). So perhaps 30?

**Comment by mhardcastle** [comment]
Bear in mind that the total includes outlier facets which don't count towards the final image. I have 6 of those in my field.

Good point about the sidelobes, I haven't tried this but you're probably right.

**Comment by wndywllms** [comment]
For Bootes I had 34 in the end, including a few that would probably be outliers in factor, so I think at least 35 or even 40 as Martin has.

**Comment by mhardcastle** [comment]
Also of course this is a maximum. You're just giving the code the freedom to do that many facets if it finds that many appropriate sources. Typically you will have fewer.

**Comment by twshimwell** [comment]
Oh yeh I forgotten about outliers. OK, maybe 40 then.

**Comment by darafferty** [comment]
If the calibrator flux exceeds peel_flux_Jy but no model was given, Factor will continue and treat it as a normal facet. It would be nice to include the sky models for bright sources. I can go ahead and add the few that we have already.

**Comment by rvweeren** [comment]
>  It would be nice to include the sky models for bright sources

Yes, ideally factor (like the prefactor repository) contains a directory with standard skymodels for bright sources to be peeled (over time we can start populating this, right now we can add our primary calibrator from the  prefactor repository)

**Comment by darafferty** [comment]
I added the prefactor sky models to factor/skymodels and a simple check for an appropriate one (if no sky model is given and a source exceeds peel_flux_Jy and is within 1 arcmin of one of the sky models in this directory, that sky model will be used for peeling).

**Comment by mhardcastle** [comment]
Reimaging: I am using

<pre>
[imaging]
make_mosaic = True
facet_imager = wsclean 
facet_cellsize_arcsec = [1.5, 4.0]
facet_taper_arcsec = [0, 20]
facet_robust = [-0.5, -1.0]
selfcal_robust_wsclean = -0.5
</pre>

**Comment by mhardcastle** [comment]
... and my final directions section was

<pre>
[directions]
flux_min_jy = 0.3
flux_min_for_merging_jy = 0.1
size_max_arcmin = 0.8
separation_max_arcmin = 9.0
ndir_max = 40
check_edges = True
</pre>

This generated 31 directions, of which 6 were outlier facets, including one on 3C295 that I put in by hand. This run is now nearly complete (half-way through reimaging): run time, using casa as the facet imager, for the full bandwidth is likely to be slightly over one month using PBS mode on 4 16-core, 64-GB nodes. (In this mode it is actually somewhat more efficient to use more, smaller facets since otherwise very often most nodes are standing idle while one large facet is imaged.)

**Comment by darafferty** [comment]
Most of these settings are now close to the defaults (or are no longer valid), so closing this issue.
