### ISSUE TITLE
selfcal_clean_threshold warning, not a valid imaging option

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#74]
Minor issue, I get this warning:

WARNING - factor:parset - Option "selfcal_clean_threshold" was given in the [imaging] section of the parset but is not a valid imaging option

**Comment by mhardcastle** [comment]
Fixed. (There's some scope for streamlining the parset parsing code so that this can't happen, but not a priority for anyone right now I guess.)

**Comment by rvweeren** [comment]
Still get the warning …. (in the latest reimage branch)

**Comment by mhardcastle** [comment]
Looking more carefully, the warning I got and fixed was for selfcal_robust_wsclean, which David had just added. My bad. There was a missing comma in the code, which I've fixed now. Who knew this was even valid python? I didn't:

<pre>
In [1]: list=['foo', 'bar' 'baz', 'wombat']
In [2]: print list
['foo', 'barbaz', 'wombat']
</pre>

**Comment by mhardcastle** [comment]
(check it works for you and then close.)

**Comment by rvweeren** [comment]
Yes thanks, warning is gone.
