### ISSUE TITLE
local_scratch_dir in NDPPP parsets?

### ISSUE THREAD

**Issue by mhardcastle** [lofar-astron/factor#75]
Trying to debug one of these annoying errors where the pipeline framework thinks something is wrong but there isn't an actual error message (and rerunning gets everything going again fine). So far my only clue is that these events seem to be correlated with pipeline steps that produce a lot of output, like NDPPP.

Anyway, I am wondering whether it could be confused by the constant warnings about 'local_scratch_dir':

<pre>
*** WARNING: the following parset keywords were not used ***
             maybe they are misspelled
    [local_scratch_dir]
</pre>

There doesn't seem to be such an option to NDPPP. Should we get rid of this in the parset?

**Comment by darafferty** [comment]
The local_scratch_dir is only used in the [custom DPPP script](https://github.com/lofar-astron/factor/blob/master/factor/pipeline/recipes/nodes/dppp_scratch.py). This script writes the output to the local disk on the node and speeds things up somewhat here in Hamburg but probably isn't used anywhere else (actually, it might be worth trying on your cluster, Martin, as I think you have a similar setup to ours). As far as I know, those warnings should be harmless, but it would indeed be cleaner to remove them (with if-then statements) if the custom script is not being used (it's picked up only when clusterdesc_file = PBS).

**Comment by darafferty** [comment]
I've finally addressed this in the new master (with if-then statements). Reopen if the warnings still appear.
