### ISSUE TITLE
Error in merging two different nights

### ISSUE THREAD

**Issue by soumyajitmandal** [lofar-astron/factor#76]
Hello all,

I was trying to merge two different nights of observation for the lockman hole field and I faced this error saying: operands could not be broadcast together with shapes (260,) (130,). 

Factor was working well till the phase calibration. It also made till image02. When it started the amplitude calibration, it failed. The reason is for one of the nights a particular antenna was flagged. This can be the case for multiple nights. See the parmdbplot of the merged parmdb: 

CS301
![cs301](https://cloud.githubusercontent.com/assets/18718701/14918010/08100566-0e22-11e6-9c0d-0c54e6e7d5ce.png)

CS302
![cs302](https://cloud.githubusercontent.com/assets/18718701/14918011/082d8438-0e22-11e6-81da-5bb61d2859e9.png)

they have different time samples.
the code: smooth_amps.py fails at the point: _norm_factor = 1.0/ (numpy.mean(amplist))_

**Comment by soumyajitmandal** [comment]
In this case I was using the "reimage" branch. Is this a known issue?

**Comment by AHorneffer** [comment]
Hmmm... Having different antennas active at different time-steps is indeed not foreseen in Factor. (So in a sense you are using Factor outside specs. ;-) )

I'll look into "smooth_amps.py" later today. But I don't have time to really go through all the code again, so it might fail again at another step.

**Comment by rvweeren** [comment]
If this fix is confirmed to work, we probably need the same fix for the spline smoothing (smooth_amps_spline.py, which I think should become the default soon)

**Comment by soumyajitmandal** [comment]
I am running Factor at this moment. Will let here know soon.

**Comment by soumyajitmandal** [comment]
I am using the "reimage" branch after this fix for 2 different runs: 

a) Abell 1914 (which is working till this point without any errors, masking seems also better this time. will post few images soon. 

b) merging 2 nights for the lockman hole where I am getting this following error: <code> The option spline_smooth2d must be enabled to use XY and YX correlations during the slow gain solve </code>. It crashes immediately after making the direction.txt file, so no additional logs are there.

I have put spline_smooth2D = True in my parset. Basically I am using similar parsets for both the runs, but the later is is giving this error.

**Comment by AHorneffer** [comment]
I had the same problem, see issue: #78

**Comment by darafferty** [comment]
Does it still give the error when spline_smooth2D = True? (It's not clear to me from the above comment.)

**Comment by soumyajitmandal** [comment]
hmm.. I have put spline_smooth2D = True , and as Andreas said, solve_all_correlations_flux_Jy = 999.0. 
But I still get the error. :-/

**Comment by darafferty** [comment]
Strange -- I can't reproduce this problem. It works fine for me with spline_smooth2D = True and solve_all_correlations_flux_Jy = 999.0. Are both options under the [calibration] section of the parset? Can you double check that they're not misspelled?

**Comment by rvweeren** [comment]
I also do not notice a problem.

**Comment by soumyajitmandal** [comment]
hmm.. I started from scratch to make sure the files are not corrupted, and rerun. will let know about the status soon.

**Comment by soumyajitmandal** [comment]
Its working. I guess just resubmitting was not a very good idea.

**Comment by soumyajitmandal** [comment]
The fix in the smooth_amps.py (also in the smooth_amps_spline.py) works! I have managed to go through amplitude calibration as well. :) 

But it now fails while plotting (<code> plot_selfcal_solutions.py </code>) the *merge_selfcal_parmdbs giving the same error: operands could not be broadcast together with shapes (130,) (260,). For one of the antennas time sample is 3500 and the other one is 7000.

**Comment by AHorneffer** [comment]
Can you let me/us know in which line of code this happens?
(Anyhow I'm not sure that I'll manage to fix that this week.)

**Comment by soumyajitmandal** [comment]
hmm. I think it fails here: <code> axsp[istat][0].plot(times, normalize(phase01-phase01_ref_chan), color='orange',  marker=fmt, ls=ls, label='Gain:0:1:Phase',mec='orange') </code>  (line 380)

**Comment by twshimwell** [comment]
Maybe a bit of a nasty fix  but an perhaps just do something simple to make the phase01 and phase01_ref_chan arrays the same size. Maybe just add a line before to get the max size of phase01 and phase01_ref_chan and then in the normalise bit just use up to that element.
