### ISSUE TITLE
solve_all_correlations active by default

### ISSUE THREAD

**Issue by AHorneffer** [lofar-astron/factor#78]
In the reimage branch: When commenting out the "spline_smooth2D" and "solve_all_correlations_flux_Jy" options in the Factor parset, then I (and apparently Jit also) get the error message: 

> ERROR - factor - The option spline_smooth2d must be enabled to use XY and YX correlations during the slow gain solve

Only after setting "solve_all_correlations_flux_Jy" to a value larger than the largest flux of a facet calibrator (I chose 999 Jy) was I able to run Factor without 2d spline smoothing.

**Comment by darafferty** [comment]
Yes, this is the intended behavior, as the default is to solve for all correlations for sources above 5 Jy. Once the spline smoothing has been tested some more (and before merging the reimage branch into master), I will set the default spline_smooth2D to True.
