### ISSUE TITLE
reimaging with multiple resolutions: is wsclean_ft necessary each time?

### ISSUE THREAD

**Issue by mhardcastle** [lofar-astron/factor#81]
I'm just running through a second reimage with lower resolution, which is working fine. But for the low-res imaging almost all the time is taken up by the wsclean_ft step. If I understand correctly this is just restoring the subtracted model (ie reversing the subtract at the end of the original facet imaging) and so it should not need to be repeated for each set of wsclean parameters; it could just be done once per facet. Is that correct?

**Comment by darafferty** [comment]
Yes, that's right -- the predict step is the same for each set of imaging parameters and indeed could be skipped (along with model corrupt step). I was just lazy and did it the easy way for the first version -- I intend to change it at some point soon.

**Comment by darafferty** [comment]
I've added the ability to reuse the averaged, calibrated data from either facetselfcal or facetimage (from full-resolution runs only, to ensure that there is not too much averaging) in subsequent facetimage operations. The data will be reused automatically if present (to keep them, set "keep_avg_facet_data = True", which is the default).

**Comment by mhardcastle** [comment]
Great! Were the data needed already saved before these changes? i.e. is it worth me stopping my run, currently about half-way through the low-res re-image, so I can pull the changes over and start it again?

**Comment by darafferty** [comment]
It should be OK to stop your run -- if the data weren't kept, then it should just continue as before. Of course there is some (considerable!) risk that I've introduced some new bugs, so perhaps better to check that they exist first. The data are the files in the mapfiles/concat_averaged_compressed.mapfile of the full-resolution facetimage pipelines. So, if those files exist, it should use them upon restart.

**Comment by darafferty** [comment]
One thing to be aware of (that I forgot to mention before) is that no additional averaging is done to the data that are reused before imaging (so imaging at lower resolution is slower than it should be). I am working now to put in this averaging step. So, you might wait until it's done.

**Comment by darafferty** [comment]
OK, the additional averaging is in there and should work now. As expected, it is much faster for low-resolution images.

**Comment by mhardcastle** [comment]
My restarted low-res reimaging doesn't appear to pick up the data from the high-res run for reuse, although the mapfiles exist.

**Comment by darafferty** [comment]
Hmm. Do the files referenced in the mapfiles also exist? If so, they should be picked up and used (the check is done in the check_existing_files() method of the operation -- it just checks each file with os.path.exists()).

**Comment by darafferty** [comment]
I added some basic logging for this check that might help debug it.

**Comment by mhardcastle** [comment]
OK, it seems that the files in the mapfiles don't exist, which I would have checked earlier if I had read your original comment more carefully! I guess they were not preserved in the version of the code I was running at the time of the first reimage. So I have no way of testing this feature in this run, but hopefully it will be some use to someone else.

**Comment by rvweeren** [comment]
closed as it is implemented (if it is not working re-open issue)
