### ISSUE TITLE
Merged datasets: preliminary results

### ISSUE THREAD

**Issue by soumyajitmandal** [lofar-astron/factor#83]
Hey all,

I have made images of 2 facets after merging two different observation. Here are some images from that run. The left column shows the facet full2.image of the merged nights and the right column shows the facet full2.image of a single night (this data is one of the merged ones). The region shows the area I have provided the noise for.

a)) <img width="1440" alt="screen shot 2016-05-10 at 14 18 45" src="https://cloud.githubusercontent.com/assets/18718701/15146909/0ac9f97a-16be-11e6-8739-38ecc13be308.png">

<code> rms noise: 324 microJy/beam & 284 microJy/beam </code> respectively
The merged one looks worse here (!) A very bright calibrator (14 Jy) with a complex structure (3 component).

b)) <img width="1434" alt="screen shot 2016-05-10 at 14 15 37" src="https://cloud.githubusercontent.com/assets/18718701/15146906/07c6607e-16be-11e6-8af7-02f825b5d704.png">
<code> rms noise: 161 microJy/beam & 215 microJy/beam </code> respectively
 For a fainter calibrator, the merged once in better. 

Now I am running factor only for the bright calibrator for the other night (the other one from the merged once).

**Comment by rvweeren** [comment]
Maybe the problem with the bright facet is that the mask is not good ?  (there seems to be sort of a ghost as well close to the source, to the bottom right)

**Comment by soumyajitmandal** [comment]
hmm...I think providing a better source model at the beginning would help as well. 

This image shows the comparison of two different observations processed separately. The right one shows the same observation as shown also in the right in the first image. 

![ds9](https://cloud.githubusercontent.com/assets/18718701/15177973/39715b0a-1773-11e6-8b7b-4bc4b3763f4a.jpeg)

**Comment by AHorneffer** [comment]
It looks to me like one noise / artefact peak gets picked up during the facet calibration, so it is indeed in a way a problem with the mask.
But I think that providing a starting model for the facet calibrator might be the best / easiest way to proceed. (Give it a model from the Factor runs of a single night.)

**Comment by soumyajitmandal** [comment]
Yes I have created a model from the image42.model (from one of the successful runs in the Factor workshop) and also created a separate region file for masking. I am running it at this moment.

**Comment by rvweeren** [comment]
Closing this for now as this is not a factor bug (we need to open a separate issue if there are problems with the plotting script for merged datasets)
