### ISSUE TITLE
wsclean output to be logged

### ISSUE THREAD

**Issue by mhardcastle** [lofar-astron/factor#84]
Is there any way of getting the wsclean output -- which presumably appears on stdout -- to be logged somewhere? ideally in real time, without buffering?

**Comment by AHorneffer** [comment]
If you look into the pipeline directory (something like: `.../work/results/facetselfcal/facet_patch_XXX/`) then you can find in there a `logs` subdirectory with `logs/<timestamp>/pipeline.log` files. (The timestamp is the time when this pipeline was started.) In that pipeline.log you can find the output of all processes, i.e. including wsclean, after each process has finished.

AFAIK Currently there is no way to view the output while wsclean is running.

P.S. Don't complain to me that the pipeline.log is big and it is hard to find the needed information in there. **evilgrin**
P.P.S. Maybe it is easier this way: the log-file for one of my processes is:
`.../work-part/results/facetselfcal/facet_patch_515/logs/2016-05-06T12:12:06/pipeline.log`

**Comment by mhardcastle** [comment]
Sure, it's kind of hard to work with factor for any length of time without knowing about the pipeline log. It was specifically the idea of being able to see the log while it's running that I was asking about (this is for profiling purposes more than anything else -- a wsclean with full bandwidth and padding can now take 24 hours).

I guess I can put a wrapper around wsclean to sort this out in a hacky way.

**Comment by AHorneffer** [comment]
Well, the logging of the pipeline framework is one of my pet-peeves, that I more or less regularly raise at the CITT telecons.  But I guess until we find some developer who can work on that we will be stuck with that.
