### ISSUE TITLE
clean.outertaper fixed to 20 arcsec

### ISSUE THREAD

**Issue by AHorneffer** [lofar-astron/factor#85]
In the facetimage parsets when imaging with casa the `clean.outertaper` parameter is fixed to `20 arcsec` (but only used when `taper_facet_arcsec is > 0`).
I guess that is not intended, or is it?

(Sorry, I'm too busy now to be sure that a quick fix by me wouldn't make things worse.)

**Comment by darafferty** [comment]
Ah -- good catch. Should be fixed now.
