### ISSUE TITLE
Reducing full1 and full2 imaging time

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/factor#88]
Perhaps something to consider in the future when we start trying to make things faster.

The full1 and full2 imaging is presently very slow. At the moment we do the full1 imaging to produce a mask which is then used in the full2 imaging which is cleaned deeper. I was wondering about perhaps instead of completely reimaging from strach with full2 we simply copy the full1 files and then continue the clean using the clean mask. Not sure how much this would speed up the imaging because you still need to stop and start the imaging but perhaps worth investigating?

**Comment by mhardcastle** [comment]
Does this work? It seems possible that the full1 images will include clean components from bright artefacts around point sources which would be excluded by the mask.

I agree it's very, very slow with the padding.

**Comment by twshimwell** [comment]
I must confess I have never tried with wsclean but I do this with other imagers sometimes. Has anyone tried it with wsclean?

The issue you mention is certainly the concern with doing something like this. To mitigate it you can incrementally improve the masking by not cleaning so deep at first and then gradually cleaning deeper and improving the masking. But that may require stopping and starting a fair bit which would be time consuming I imagine.

**Comment by rvweeren** [comment]
I think Andre is working/planning on a "restart" option (not there yet). If that works we might do something like this and gradually build up the mask and clean deeper (as SPAM does). Basically at every major cycle the mask needs to be updated. On the other hand, the source detection might start to add considerably to the computing budget (in some cases there are extended sources and PyBDSM can spend quite a while on them if you are unlucky)

So in the end this might help reducing the computation time somewhat, but it is not going to be a game changer.

**Comment by twshimwell** [comment]
OK. Thanks for the info. I was just testing it and noticed it doesn't seem to do it yet too.

I'll close this issue for now but perhaps something to consider again once this functionality gets into wsclean.
