### ISSUE TITLE
averaging of the data

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/factor#9]
Presently I think factor averages the data according to:

```
target_bandwidth_mhz = 0.25 * 2048.0 / facet_imsize
target_timewidth_s = 30.0 * 2048.0 / facet_imsize
```

which assumes that 0.25MHz and 30secs are the correct averaging for 2048 1.5" pixels (26' radius). However, at 25’ and 5” resolution there is a lot of smearing at this averaging from both time and bandwidth smearing. For example, I find that at 150MHz bandwidth smearing and averaging of 0.25MHz means that at a radius of 25' the source will have 94% of its peak flux due to bandwidth smearing and 30sec averaging will mean the source has 89% of its peak flux due to time smearing. So, the combined effect means we only recover 84% of the peak flux at 25' radius and the images are square so in the corners the effect will be much worse (35' separation) with time smearing leaving on 79% of the peak flux and bandwidth smearing leaving  89% of the peak flux so combined we only recover 70% of the peak flux in the corners of the images.

Maybe we should average even less (15sec and 0.125MHz would give 0.98 (bandwidth smear) *0.97 (time smear ) =0.95 of the peak flux remaining at 25'. Or perhaps there should be an option in the parset about the amount of averaging because this increases the data size significantly and many factor users will not mind blurring their sources a little as long as the target  remains intact. 

I have pasted formulas (which are an approximation) I used for calculations below or see  http://adsabs.harvard.edu/full/1989ASPC....6..247B

```
def time_smearing2(delta_T,delta_Theta,resolution):
    # delta_T = time in secs, delta_Theta = distance from pointing centre, resolution = resolution. Units of delta_Theta and resolution must be the same as they cancel.
    Reduction = 1-1.22E-9*(delta_Theta/resolution)**2.0 * delta_T**2.0
    print 'At radius %s and resolution %s the source will have %s percent of its flux if data smoothed to %s sec'%(delta_Theta,resolution,Reduction,delta_T)
    return


def bandwidth_smearing2(resolution,freq,delta_Theta,delta_freq):
    # resolution=resolution, freq = frequency, delta_freq = frequency resolution and delta_Theta = distance from phase centre. Units of resolution cancel with units of delta_Theta and units of frequency cancel with delta_freq.
    beta = (delta_freq/freq) * (delta_Theta/resolution)
    gamma = 2*(np.log(2)**0.5)
    Reduction = ((np.pi**0.5)/(gamma * beta)) * (scipy.special.erf(beta*gamma/2.0))
    print 'At radius %s, with resolution of %s and at frequency of %s a source will only have %s percent of its flux if data smoothed in freq to %s'%(delta_Theta,resolution,freq,Reduction,delta_freq)
    return
```

**Comment by darafferty** [comment]
I made the averaging calculations more general and added an option (max_peak_smearing under [global]) that sets the maximum desired smearing. The default is 0.15, matching the previous value. This setting only applies to the facet imaging; selfcal always uses 0.15 (the previous smearing limit). Do these values look OK?

Note that to keep smearing below 0.05, we can't make images larger than ~ 2048 pixels as the full-resolution data that we give FACTOR are usually already averaged too much for that (to 0.1MHz and 8 s). It will painful indeed to image the full FOV with < 5% smearing...

**Comment by rvweeren** [comment]
Yes, and since we the user can specific it now via max_peak_smearing we can close this issue.

**Comment by twshimwell** [comment]
Thanks
