### ISSUE TITLE
Work on original MS files

### ISSUE THREAD

**Issue by nudomarinero** [lofar-astron/factor#90]
Currently factor seems to work on copies of the MS files given in the "dir_ms" parameter. Although this is OK in many cases, it could be interesting to have an option to work straight away on the MS files and skip the copy step.

This is useful for example when the user uses an object storage solution like S3 in AWS, a Ceph cluster, or Swift in OpenStack. The MSs are safely stored in the object store and a working copy is already transferred to the working nodes by custom means. Hence, there is no need to make an additional copy.

I think that a possible way to do that is to let the user copy the MS files into the working directory and let factor know that the copy of the data is not necessary. Is it possible to implement that?

**Comment by darafferty** [comment]
This option is probably also needed for the "unarchive" functionality (see issue #89), since we probably don't want to archive the original MS files, just those in the working directory. Hence, if you want to run Factor again after restoring from an archive, the input MS files would be located in the working directory.

**Comment by AHorneffer** [comment]
A copy of the data is only made if the input MSs need to be chunked in time. If they already are in short time chunks, then only symbolic links are done.

So my suggestion would be to put chunked files into S3. ;-)

**Comment by nudomarinero** [comment]
Given that factor works on the chunked files I see a couple of useful improvements to deal with this:
- If the files are not stored in chunked format there could be an option to remove the files from the "dir_ms" directory as the chunking step is finished. This would solve the space problems in the case that I was describing before.
- Optionally offer a way to chunk the data in a way that is compatible with factor. The data could be chunked as a previous step to factor and stored in this format. This would allow to use the symbolic link functionality mentioned by @AHorneffer.

**Comment by nudomarinero** [comment]
I have seen that there is a new option in the factor parset related to chunking called: ```chunk_size_sec``` 
If the time specified is larger than the length of the longest dataset factor will not copy the data. Would this solve the duplication of the data?

On the other hand. If I have the data already chunked by factor (in the typical chunks/Band_115.92MHz/... directories). Is it possible to input those bands in a clean run of factor? If so, how could that be done?

**Comment by nudomarinero** [comment]
I have tried to enter the factor chunked data as input. All the chunks were copied in the same directory and the direction independent calibration solutions were copied inside each band. The models are copied in the same directory.
The data is linked instead of copied (each ms with an additional "_chunk0" suffix) but at some point factor failed with the error:
```A direction-indpendent sky model was not found for the following bands: Band_115.92MHz, Band_117.87MHz, Band_119.82MHz, Band_121.78MHz, Band_123.73MHz, Band_125.68MHz, Band_127.64MHz, Band_129.59MHz, Band_131.54MHz, Band_135.45MHz, Band_139.35MHz, Band_141.31MHz, Band_143.26MHz, Band_145.21MHz, Band_147.17MHz, Band_149.12MHz, Band_151.07MHz, Band_153.03MHz, Band_154.98MHz, Band_156.93MHz, Band_158.89MHz, Band_160.84MHz, Band_162.79MHz, Band_164.74MHz, Band_166.70MHz, Band_170.60MHz, Band_172.56MHz, Band_174.51MHz, Band_176.46MHz```
It looks like it did not find the sky model with the old regular name. However, I could specify the model in the parset for at least one MS of each band and it does not fail. So I suppose that this is a way to input chunked data that works.
