### ISSUE TITLE
reduce channelsout for major WSClean speed up

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/factor#91]
Just realized we can achieve a **major** wsclean speedup (factor 2-4!) by reducing channelsout. I've done some testing and for sources < 10 Jy we can reduce the number of output channels by about a factor of 4. 

At the moment channelsout = nbands 

We could change this to channelsout= nbands/4.

The only issue we have to be careful with is to make sure there are no rounding issues, when we do the full resolution FFT predict step (i.e., how wsclean channelizes the data via channelsout)  . So channelsout should be a multiple of the total number of channels contained in the "ms for facet imaging" . Because it that case the full resolution dataset's bandwidth will be channelized (by wsclean) in an identical way. For example, in simple case that the "ms for facet imaging" are not averaged (and have the same freq. resolution as the full resolution data) there are no restrictions on channelsouts.

The above change should have little to no effect on the output quality because:
-  if we have > 10+ Jy sources we probably need to peel them anyway 
-  WSClean shows dynamic range errors for 10+ Jy sources due to other issues (so even with channelsout = bands the image will not look good, again meaning we probably need peeling if we want to reduce the number of artifacts to a minimum)

**Comment by darafferty** [comment]
OK, I've removed the old wsclean_nbands option and added a new one called wsclean_nchannels_factor that sets channelsout as:

channelsout = nbands / wsclean_nchannels_factor

channelsout is then adjusted so that it is a divisor of the total number of channels after averaging for the facet imaging step and is not allowed to exceed nbands. The wsclean_nchannels_factor option defaults to 4.

**Comment by twshimwell** [comment]
Great! Just tried this but get indentation error. I think on line 160 there is an 's' that shouldn't be there.

**Comment by twshimwell** [comment]
(of parset.py)

**Comment by darafferty** [comment]
Oops, sorry -- errant keypress. Should be fixed now.

**Comment by AHorneffer** [comment]
Note to self: check if this does take proper care of missing frequency bands?

**Comment by mhardcastle** [comment]
Just to note, here seems as good as anywhere, that a test of CASA 4.5 on a large facet with full bandwidth suggests a substantial speedup over the old wsclean implementation -- perhaps a factor 3 (need to dig in the statistics.xml). The nchannels change to wsclean may therefore make them roughly comparable....

**Comment by twshimwell** [comment]
The run of factor I am doing using wsclean_nchannels_factor = 4 crashes and complains about nchan_per_band not being defined in direction.py. Is this supposed to be an nchan_per_block?

**Comment by gheald** [comment]
I saw the same nchan_per_band error yesterday. I think you need to modify line 260 of factor/lib/direction.py such that nchan_per_band becomes nchan

**Comment by darafferty** [comment]
Yeah, George reported it to me yesterday. Should be fixed now.

**Comment by rvweeren** [comment]
Thinking a bit more, it might be worthwhile to strategically "add" and empty block at the edge so we can always divide the number of blocks by either (3), 4, 5, or 6. For example, with 29 blocks we would be forced to use channelsout=29. However, just adding an empty block would increase the number of blocks to 30 and then we can use channelsout=6 or 5  (wsclean_nchannels_factor=5, wsclean_nchannels_factor=6) leading to a huge speed up in the imaging.

**Comment by AHorneffer** [comment]
Well, you should check what WSClean does with a bock of fully flagged data. If it is included in the calculations for the frequency coverage or not.

**Comment by rvweeren** [comment]
Flagged data is included.

**Comment by darafferty** [comment]
I've added an option ("wsclean_add_bands" under [imaging]; default is True) to insert extra flagged bands in WSClean jobs to allow the total number of bands to be a evenly divided by wsclean_nchannels_factor. I've done only limited testing so far, but it seems to work fine for both imaging and predict.

**Comment by rvweeren** [comment]
#117
