### ISSUE TITLE
Masking extended emission

### ISSUE THREAD

**Issue by AnnalisaB** [lofar-astron/factor#94]
Hi all,
I have seen few cases where the diffuse emission gets lost in the selfcal steps
(example attached). 
I have switched on the adaptive selfcal option (selfcal_adaptive_threshold = True)
Has anyone experienced (and fixed) the same? 

Thanks!
Annalisa 

<img width="619" alt="screen shot 2016-06-04 at 20 53 03" src="https://cloud.githubusercontent.com/assets/19752027/15801510/cbb19e26-2a97-11e6-9734-ab8ecac8cd4c.png">

**Comment by AHorneffer** [comment]
Yes, I have similar problems with pyBDSM not  working well on extended emission.

You can specify a casa-style region-file with the clean region for the extended source in the directions file. (Actually twice: once for the calibrator images and once for the full facet.) The actual clean mask will be the merge result of the output of pyBDSM and the region file that you specify. (So you only need to specify the extended emission by hand.)
