### ISSUE TITLE
separate skymodel for calibrator search and facet boundaries

### ISSUE THREAD

**Issue by AHorneffer** [lofar-astron/factor#95]
Currently Factor uses the skymodel that was subtracted from the visibilities also for the search for facet calibrators (if no directions file is given) and to adjust facet boundaries so that they don't bisect a source. (It uses the skymodel that was subtracted from the highest frequency band.) It would be good if one could specify a different skymodel for these tasks. That way one could compute a deeper skymodel (from combining all images and then doing source detection, from another (deeper) imaging step, or whatever) and use this for calibrator search and the facet boundaries.

**Comment by darafferty** [comment]
I added an option for this under [directions] called 'faceting_skymodel'. At the moment, the sky model has to be in makesourcedb (BBS) format and grouped into patches by source (which can be done in PyBDSM by setting bbs_patches = 'source' in the write_catalog task).
