### ISSUE TITLE
Reimaging on multiple nodes

### ISSUE THREAD

**Issue by mhardcastle** [lofar-astron/factor#97]
When reimaging on multiple nodes, there is no need to operate on a group (e.g. select 4 directions at a time, do them all, move on once the last direction is done). It would be preferable to keep the nodes busy. Is this possible?

**Comment by darafferty** [comment]
That would indeed be possible, but we would need a way to assign the nodes to the directions adaptively (when using the PBS mode), so that when one direction finishes the next one would get its node. We could probably to do this in the scheduler -- I'll look into it.

**Comment by darafferty** [comment]
I've changed the scheduler so that this is now done for reimaging (when a facet image finishes, the next one in line is immediately started with the previous one's resources).

**Comment by mhardcastle** [comment]
The changes to the scheduler seem to be working, thanks.
