### ISSUE TITLE
bug in merging in setup directions 

### ISSUE THREAD

**Issue by wndywllms** [lofar-astron/factor#98]
in the final 'Merging extended sources within 7.5 arcmin of calibrators...' step in setting up the directions I get a
ValueError: 'facet_patch_372' is not in list
(more log/traceback below)

I've fixed this with commit https://github.com/lofar-astron/factor/commit/74dec196c8141bf5423c1f1d783b3223b58f2938. The reason being that you only want to search around the calibrator positions to merge any extended sources into the calibrator patch. I seem to have two calibrators within directions_separation_max_arcmin of an 'extended source' (but not of each other - partly because the path positions were not updated after the merging of calibrator sources) and they get merged so one falls out the list.

INFO - factor - Building local sky model for source avoidance and DDE calibrator selection (if desired)...
INFO - factor:directions - Found 749 sources through thresholding
INFO - factor - Setting up directions...
INFO - factor - No directions file given. Selecting directions internally...
INFO - factor - Removing sources beyond a radius of 3.78129831448 degrees (corresponding to a diameter of 2.0 \* FWHM of the primary beam at 166.111755371 MHz)...
INFO - factor:directions - Found 586 sources with sizes below 0.8 arcmin
INFO - factor:directions - Found 113 sources with flux densities above 0.1 Jy
INFO - factor:directions - Merging sources within 7.5 arcmin of each other...
INFO - factor:directions - Found 36 sources or merged groups with total flux densities above 0.3 Jy
INFO - factor:directions - Kept 36 directions in total
INFO - factor:directions - Merging extended sources within 7.5 arcmin of calibrators...
Traceback (most recent call last):
  File "/home/wwilliams/scripts/git/factor/bin/runfactor", line 70, in <module>
    reset_operations)
  File "/home/wwilliams/.local/lib/python2.7/site-packages/FACTOR-1.0-py2.7.egg/factor/process.py", line 73, in run
    test_run, reset_directions, reset_operations)
  File "/home/wwilliams/.local/lib/python2.7/site-packages/FACTOR-1.0-py2.7.egg/factor/process.py", line 587, in _set_up_directions
    max_radius_deg=max_radius_deg, dry_run=dry_run)
  File "/home/wwilliams/.local/lib/python2.7/site-packages/FACTOR-1.0-py2.7.egg/factor/process.py", line 783, in _initialize_directions
    flux_min_for_merging_Jy=dir_parset['flux_min_for_merging_jy'])
  File "/home/wwilliams/.local/lib/python2.7/site-packages/FACTOR-1.0-py2.7.egg/factor/directions.py", line 232, in make_directions_file_from_skymodel
    in calibrator_names])
ValueError: 'facet_patch_372' is not in list

**Comment by darafferty** [comment]
Fix seems to work fine in my testing, so closing the issue.
