### ISSUE TITLE
no averagin in fieldmosaic

### ISSUE THREAD

**Issue by AHorneffer** [lofar-astron/factor#99]
When generating the visibilities for the awimager-cal the data should be averaged quite a bit. (We are only interested in the PB image, not the actual image itself.)
In the current version of the fieldmosaic this averaging is not done. The lines:

```
concat_data.argument.avg.freqstep                      =   {{ facetselfcal_freqstep }}
concat_data.argument.avg.timestep                      =   {{ facetselfcal_timestep }}
```

have empty arguments (facetselfcal_freqstep and facetselfcal_timestep are not set).

**Comment by darafferty** [comment]
Yes, just discovered this problem myself. It's due to the field object not having those selfcal parameters defined. Maybe just define the freqstep so that there is 1 channel per band and the timestep so that there is 120 sec per sample?

**Comment by darafferty** [comment]
Should be fixed now (see  https://github.com/lofar-astron/factor/commit/9d92b6df8735752ea9c12f7a749b5832728624de and https://github.com/lofar-astron/factor/commit/baa3cb20bc5ca21199112a44ab34a80e1d8c0843).

**Comment by AHorneffer** [comment]
Hmmm... is it possible that this averaging never actually worked?
Even in my old code I cannot find to which value that was supposed to be set.

I guess timesteps of 120 sec are O.K. 1 channel per band sounds a bit too much, that would be 2 MHz per channel and I don't know how much the beam changes per MHz. Maybe 1 MHz or 0.5 MHz per channel is better.

**Comment by gheald** [comment]
Isn't the default timescale for the Aterm computation for the Aprojection in the awimager 5 min? (And that was chosen to capture the temporal variation in the beam term.) If so then I would assume that averaging to 300 sec would be fine.

**Comment by AHorneffer** [comment]
Good point! 
Do you have an idea how fast the beam changes in frequency? Or: is averaging to 2 MHz bins O.K.?

**Comment by rvweeren** [comment]
2 MHz bins should be ok (2/150~ small)
